### ISSUE TITLE
NZBGet chunk NameError

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#10]
```
 4601 13-Jan-2020 16:40:58 - DEBUG   :: mylar.searcher.2229 : SEARCH-QUEUE : [PAYLOAD-NONE] Download URL: https://api.nzbgeek.info/api?t=get&id=24560044fc832fad981b1e5aac85079a&apikey=xYOUDONTNEEDTOKNOWTHISx [VerifySSL: True]
 4602 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2249 : SEARCH-QUEUE : Status code returned: 200
 4603 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2271 : SEARCH-QUEUE : filename within nzb: Dr.Strange-Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
 4604 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2288 : SEARCH-QUEUE : [FILENAME] filename (remove chars): Dr.Strange-Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
 4605 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2291 : SEARCH-QUEUE : [FILENAME] nzbname (\s): Dr.Strange-Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
 4606 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2293 : SEARCH-QUEUE : [FILENAME] end nzbname: Dr.Strange-Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
 4607 13-Jan-2020 16:41:06 - DEBUG   :: mylar.searcher.2308 : SEARCH-QUEUE : Cache Directory successfully found at : /opt/mylar.py3/cache
 4608 13-Jan-2020 16:41:06 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
 4609   File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
 4610     old_run(*args, **kwargs)
 4611   File "/opt/pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
 4612     self._target(*self._args, **self._kwargs)
 4613   File "/opt/mylar.py3/mylar/helpers.py", line 3177, in search_queue
 4614     ss_queue = mylar.search.searchforissue(item['issueid'])
 4615   File "/opt/mylar.py3/mylar/search.py", line 1862, in searchforissue
 4616     foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsschec
 4617   File "/opt/mylar.py3/mylar/search.py", line 371, in search_init
 4618     findit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=Is
 4619   File "/opt/mylar.py3/mylar/search.py", line 1489, in NZB_SEARCH
 4620     searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
 4621   File "/opt/mylar.py3/mylar/search.py", line 2494, in searcher
 4622     send_to_nzbget = ss.sender(nzbpath)
 4623   File "/opt/mylar.py3/mylar/nzbget.py", line 72, in sender
 4624     if not chunk:
 4625 NameError: name 'chunk' is not defined
```

**Comment by barbequesauce** [comment]
gah fixed with a6aa94082da437eb5595a7e0d3e501f7330585eb
