### ISSUE TITLE
No such table: provider_searches

### ISSUE THREAD

**Issue by ajw107** [mylar3/mylar3#1004]
**Describe the bug**
I've just updated mylar, and wonder if there is has been a database schema update recently.  As it won't start, stating it can't find the table provider_searches (which indeed does not exists in my db or any of it's recent backups).

**CarePackage**
I am unable to start mylar, so the only thing I can give you is the logs from docker.  Please ignore the error about unable to backup the config, due to the error the config.ini gets deleted for some reason, and then just cycles:
```
mylar-service  | Initializing startup sequence....
mylar-service  | Unable to make proper backup of config file in /config/mylar/config.ini.backup
mylar-service  | Attempting to update configuration..
mylar-service  |     main()
mylar-service  |   File "/app/mylar3/Mylar.py", line 229, in main
mylar-service  |     mylar.initialize(mylar.CONFIG_FILE)
mylar-service  |   File "/app/mylar3/mylar/__init__.py", line 204, in initialize
mylar-service  |     chk = myDB.select("SELECT * FROM provider_searches")
mylar-service  |   File "/app/mylar3/mylar/db.py", line 148, in select
mylar-service  |     sqlResults = self.fetch(query, args).fetchall()
mylar-service  | Attempting to update configuration..
mylar-service  | DB error: no such table: provider_searches
mylar-service  | Traceback (most recent call last):
mylar-service  |   File "/app/mylar3/Mylar.py", line 452, in <module>
mylar-service  |     main()
mylar-service  |   File "/app/mylar3/Mylar.py", line 229, in main
mylar-service  |     mylar.initialize(mylar.CONFIG_FILE)
mylar-service  |   File "/app/mylar3/mylar/__init__.py", line 204, in initialize
mylar-service  |     sqlResults = self.fetch(query, args).fetchall()
mylar-service  |   File "/app/mylar3/mylar/db.py", line 89, in fetch
mylar-service  |     sqlResult = cursor.execute(query)
mylar-service  | sqlite3.OperationalError: no such table: provider_searches
mylar-service  | DB error: no such table: provider_searches
mylar-service  | Traceback (most recent call last):
mylar-service  | log language set to en_US
```

**Environment (please complete the following information):**
 - OS: Docker (Debian based) on ArchLinux
 - Branch / commit: Dev

**Additional information**
Add any other information about the problem here.

**Comment by ajw107** [comment]
Ignore me completely.  I was looking at the master branch by mistake, and I use the dev branch.  I see you are currently working in it, and that is why the error was happening (just updates, and it removed that error, but gave one about `UnboundLocalError: local variable 't_type' referenced before assignment`).  So I will wait until you are all sorted.
