### ISSUE TITLE
Mylar Nightly not starting

### ISSUE THREAD

**Issue by rg9400** [mylar3/mylar3#1011]
**Describe the bug**
I noticed that Mylar has not been able to start the last few days running on dev/nightly tags in Docker (hotio/mylar3:nightly). I use Prowlarr, but I redacted my indexers as some are sensitive. Mylar launches if I go back to 2ba59142ea866ba667e4c4c416436e1bf5b29f02, but fails as soon as I switch to caf9dade5451218dc61509d281e9d331edb8959e

**CarePackage**
```23-Jan-2022 20:17:12 - DEBUG   :: mylar.configure.1014 : MainThread : Log dir: /config/logs
23-Jan-2022 20:17:12 - DEBUG   :: mylar.configure.1082 : MainThread : [Grabbag Directory] Setting One-Off directory to default location: /mnt/media/Comics/Grabbag
23-Jan-2022 20:17:12 - INFO    :: mylar.configure.1130 : MainThread : Ignored Publishers: []
23-Jan-2022 20:17:12 - INFO    :: mylar.configure.1153 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
23-Jan-2022 20:17:12 - INFO    :: mylar.configure.1165 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
23-Jan-2022 20:17:12 - INFO    :: mylar.configure.1169 : MainThread : [COMICTAGGER] Version detected: 1.3.4
23-Jan-2022 20:17:12 - DEBUG   :: mylar.configure.1208 : MainThread : [COMICTAGGER] Setting ComicTagger settings default path to : /config/.ComicTagger
23-Jan-2022 20:17:12 - INFO    :: mylar.configure.1248 : MainThread : Setting DDL Location set to : /config/cache
23-Jan-2022 20:17:12 - DEBUG   :: mylar.writeconfig.872 : MainThread : Writing configuration to file
23-Jan-2022 20:17:12 - DEBUG   :: mylar.writeconfig.906 : MainThread : Configuration written to disk.
23-Jan-2022 20:17:12 - INFO    :: mylar.initialize.212 : MainThread : Checking to see if the database has all tables....
23-Jan-2022 20:17:12 - INFO    :: mylar.dbcheck.1524 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
23-Jan-2022 20:17:12 - INFO    :: mylar.dbcheck.1534 : MainThread : Correcting Null entries that make the main page break on startup.
23-Jan-2022 20:17:12 - INFO    :: mylar.dbcheck.1545 : MainThread : [<class 'int'>]oldconfig_version: 12
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1531 : MainThread : Original provider_order sequence: 0, Experimental, <redacted>
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1534 : MainThread : Provider sequence already pre-exists. Re-loading and adding/remove any new entries
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1546 : MainThread : existing Order count does not match New Order count
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1548 : MainThread : 5 New entries exist, appending to end as default ordering
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1554 : MainThread : 22 entries are enabled.
23-Jan-2022 20:17:12 - DEBUG   :: mylar.provider_sequence.1616 : MainThread : Provider Order is now set : {'0': 'Experimental', '1': 'a', '2': '0', '3': '5', '4': '0', '5': 'a', '6': '0', '7': '5', '8': '5', '9': '0', '10': 'a', '11': '0', '12': '5', '13': ',', '14': '0', '15': 'a', '16': '0', '17': '5', '18': '0', '19': 'a', '20': '0', '21': 'DDL(GetComics)'} 
23-Jan-2022 20:17:12 - INFO    :: mylar.write_out_provider_searches.1650 : MainThread : Experimental was not found in search db. Writing it..
23-Jan-2022 20:17:12 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/Mylar.py", line 451, in <module>
    main()
  File "/app/Mylar.py", line 229, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar/__init__.py", line 218, in initialize
    cc.provider_sequence()
  File "/app/mylar/config.py", line 1618, in provider_sequence
    self.write_out_provider_searches()
  File "/app/mylar/config.py", line 1674, in write_out_provider_searches
    vals = {'active': False, 'lastrun': 0, 'type': t_type}
UnboundLocalError: local variable 't_type' referenced before assignment
```

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] Docker on Ubuntu 20.04 (hotio/mylar3:nightly)
 - Branch / commit: [e.g. Dev/38aksi1] Dev/bb4a86731e5c8ad603fc3b7fed2418773c48eee4

**Comment by evilhero** [comment]
Looks like a problem with the Experimental name in the last big update - probably didn't adjust it correctly.

If you temporarily disable experiemental in your config.ini (``experiemental = False``) - you should be able to boot up clean after that. 

It might be an hr or two before I can look into the exact problem with the Experimental provider, so disabling the provider would let you use the app until the fix goes in.

**Comment by rg9400** [comment]
This is fixed now
