### ISSUE TITLE
RSS TypeError

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#11]
```
 4823 13-Jan-2020 16:46:22 - DEBUG   :: mylar.NZB_SEARCH.633 : SEARCH-QUEUE : Sending request to [32P] RSS for Dr. Strange :
 4824 13-Jan-2020 16:46:22 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
 4825   File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
 4826     old_run(*args, **kwargs)
 4827   File "/opt/pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
 4828     self._target(*self._args, **self._kwargs)
 4829   File "/opt/mylar.py3/mylar/helpers.py", line 3177, in search_queue
 4830     ss_queue = mylar.search.searchforissue(item['issueid'])
 4831   File "/opt/mylar.py3/mylar/search.py", line 1862, in searchforissue
 4832     foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsschec
 4833   File "/opt/mylar.py3/mylar/search.py", line 339, in search_init
 4834     findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=Issue
 4835   File "/opt/mylar.py3/mylar/search.py", line 634, in NZB_SEARCH
 4836     bb = rsscheck.torrentdbsearch(ComicName, mod_isssearch, ComicID, nzbprov, oneoff)
 4837   File "/opt/mylar.py3/mylar/rsscheck.py", line 741, in torrentdbsearch
 4838     AS_Altrem = re.sub("\\band\\b", "", u_altsearchcomic.lower())
 4839   File "/opt/pyenv/versions/3.8.1/lib/python3.8/re.py", line 208, in sub
 4840     return _compile(pattern, flags).sub(repl, string, count)
 4841 TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by barbequesauce** [comment]
Duplicate of #3
