### ISSUE TITLE
'provider_stat' referenced before assignment

### ISSUE THREAD

**Issue by Sparticuz** [mylar3/mylar3#1128]
**Describe the bug**
I seem to be getting this bug during normal new release checks

**CarePackage**
```
25-Mar-2022 14:40:14 - INFO :: mylar.ddl.463 : ThreadPoolExecutor-0_0 : [RSS][DDL] 12 entries have been indexed and are now going to be stored for caching.                                                
25-Mar-2022 14:40:14 - INFO :: mylar.run.107 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] RSS Feed Check/Update Complete                                                                                         
25-Mar-2022 14:40:14 - INFO :: mylar.run.108 : ThreadPoolExecutor-0_0 : [RSS-FEEDS] Watchlist Check for new Releases                                                                                       
25-Mar-2022 14:40:14 - INFO :: mylar.searchforissue.1697 : ThreadPoolExecutor-0_0 : Initiating RSS Search Scan at the scheduled interval of 20 minutes                                                     
25-Mar-2022 14:40:14 - INFO :: mylar.searchforissue.1826 : ThreadPoolExecutor-0_0 : Issues that belong to part of a Story Arc to be searched for : 0                                                       
25-Mar-2022 14:40:14 - INFO :: mylar.nzbdbsearch.933 : ThreadPoolExecutor-0_0 : cur returned. db attached.                                                                                                 
25-Mar-2022 14:40:14 - INFO :: mylar.nzbdbsearch.940 : ThreadPoolExecutor-0_0 : dropped previous rss dataset to ensure we have a clean slate.                                                              
25-Mar-2022 14:40:15 - INFO :: mylar.nzbdbsearch.954 : ThreadPoolExecutor-0_0 : executed insert...now attempting to select                                                                                 
25-Mar-2022 14:40:15 - INFO :: mylar.nzbdbsearch.1044 : ThreadPoolExecutor-0_0 : [RSS-QUERY] Searched through RSSDB looking for 30 Wanted items in 11083 RSS entries. Rough matching to 10 items.          
25-Mar-2022 14:40:15 - INFO :: mylar.searchforissue.2165 : ThreadPoolExecutor-0_0 : rss_results[x]: {'title': 'xXX[REMOVED]XXx', 'link': '266175', 'pubdate': 'Tue, 01 Feb 2022 20:42:33', 'site': 'DDL'
, 'length': '34603008', 'issues': None, 'pack': False, 'info': {'ComicName': 'xXX[REMOVED]XXx', 'Issue_Number': '36', 'ComicYear': '2022', 'SeriesYear': '2018', 'Publisher': 'xXX[REMOVED]XXx', 'IssueDate': '2022-01-01', 'StoreDate': '20
22-01-26', 'IssueID': 'xXX[REMOVED]XXx', 'AlternateSearch': None, 'UseFuzzy': None, 'ComicVersion': None, 'SARC': None, 'IssueArcID': None, 'searchmode': 'want', 'RSS': 'yes', 'ComicID': 'xXX[REMOVED]XXx', 'ComicName_Filesafe': 'xXX[REMOVED]XXx', 'Allo
wPacks': True, 'OneOff': False, 'TorrentID_32P': None, 'DigitalDate': '0000-00-00', 'booktype': 'Print', 'ignore_booktype': True}}                                                                                                
25-Mar-2022 14:40:15 - INFO :: mylar.searchforissue.2182 : ThreadPoolExecutor-0_0 : current_prov: {}                                                                                                       
25-Mar-2022 14:40:15 - ERROR :: mylar.searchforissue.2376 : ThreadPoolExecutor-0_0 : Traceback (most recent call last):                                                                                    
  File "/app/mylar3/mylar/search.py", line 2188, in searchforissue                                                                                                                                         
    foundc['lastrun'] = provider_stat['lastrun']                                                                                                                                                           
UnboundLocalError: local variable 'provider_stat' referenced before assignment                                                                                                                             
Traceback (most recent call last):                                                                                                                                                                         
  File "/app/mylar3/mylar/search.py", line 2188, in searchforissue                                                                                                                                         
    foundc['lastrun'] = provider_stat['lastrun']                                                                                                                                                           
UnboundLocalError: local variable 'provider_stat' referenced before assignment

```
**Environment (please complete the following information):**
 - OS: arch linux, kernel 5.16.5, linuxserver/mylar3:latest
 - Branch / commit: v0.6.6 (master)

**Comment by Sparticuz** [comment]
There is something messing up. I've tried to remove all these, after saving, they come back. Could be something to do with prowlarr? Will post carepackage momentarily.

![image](https://user-images.githubusercontent.com/161913/160198661-c952e24c-4787-4a85-9ad5-f5c307f6b588.png)

**Comment by evilhero** [comment]
Try setting the config.ini value:  ``clear_provider_searches = True``. The provider searches table probably has some weird providers within it which has been the cause previously and we're trying to fix them retroactively unfortunately. The ini value will wipe the table so that it can be regenerated clean.

**Comment by Sparticuz** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/8353783/carepackage.zip)

**Comment by Sparticuz** [comment]
`clear_provider_searches = True` fixed the providers screen. I will let you know if I get the same error in the logs
