### ISSUE TITLE
File Name Parsing Incorrectly (Issue number is "X")

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1130]
**Describe the bug**
I am importing Marvel's Earth X series, which includes an issue X. The title for this issue is thus "Earth X X (2000).cbz" using Mylar's naming convention (or perhaps "Earth X 00X (2000).cbz"?). The other comics are detected just fine, but it doesn't know how to handle the "X" as the issue number in this case, and instead includes it in the series title. No variation of the file name that I've tried entering has worked thus far.

**CarePackage**
[Care Package DL](https://file.io/5tNaKLp5lGD7)

**Environment:**
 - OS: Docker
 - Branch / commit: Master / v0.6.5.2

**Additional information**
Relevant log entries here: 

2022-03-26 08:02:48 | INFO | FAILED  FILES: [{'parse_status': 'failure', 'sub': None, 'comicfilename':  'Earth X X (2000).cbr', 'comiclocation': '/data/media/comics/Earth X  (1999)', 'series_name': 'Earth X X', 'series_volume': 'v1',  'alt_series': None, 'alt_issue': None, 'issue_year': '2000',  'issue_number': None, 'issueid': None, 'scangroup': None, 'booktype':  'TPB/GN/HC'}]
-- | -- | --
2022-03-26 08:02:48 | DEBUG | series title possibly: Earth X X
2022-03-26 08:02:48 | DEBUG | [FILENAME]: Earth X X (2000).cbr

**Comment by evilhero** [comment]
Try it as ``Earth X #X (2000).cbz`` - so that the ``#`` forces mylar to use that as the issue number as opposed to trying to decipher it from the filename.

**Comment by jakem742** [comment]
Thank you! This imported correctly. :) Unfortunately I get an exception when I try to rename the file in Mylar: 

```
ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 3803, in manualRename
    nfilename = renameiss['nfilename']
TypeError: 'NoneType' object is not subscriptable
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>
```

I continue to get this error after rebooting Mylar.
