### ISSUE TITLE
500 error when adding War of the Bounty Hunters arc

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#1136]
ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
<title>500 Internal Server Error</title>
<style type="text/css">
#powered_by {
margin-top: 20px;
border-top: 2px solid black;
font-style: italic;
}

#traceback {
color: red;
}
</style>
</head>
<body>
<h2>500 Internal Server Error</h2>
<p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
<pre id="traceback">Traceback (most recent call last):
File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
self._do_respond(path_info)
File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
response.body = self.handler()
File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
return self.callable(*self.args, **self.kwargs)
File "/opt/mylar3-dev/mylar/webserve.py", line 1230, in addbyid
response = self.addStoryArc(arcid=query_chk['comicid'], cvarcid=query_chk['cvarcid'], storyarcname=query_chk['comicname'],
File "/opt/mylar3-dev/mylar/webserve.py", line 1491, in addStoryArc
comicid_results = mylar.cv.getComic(comicid=None, rtype='comicyears', comicidlist=cidlist)
File "/opt/mylar3-dev/mylar/cv.py", line 186, in getComic
return GetSeriesYears(dom)
File "/opt/mylar3-dev/mylar/cv.py", line 1138, in GetSeriesYears
fc_id = fc['data-ref-id']
File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/site-packages/bs4/element.py", line 1406, in __getitem__
return self.attrs[key]
KeyError: 'data-ref-id'
</pre>
<div id="powered_by">
<span>
Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.0</a>
</span>
</div>
</body>
</html>

running 79c81aa w/git

**Comment by barbequesauce** [comment]
console error:

```
28-Mar-2022 13:41:59 - DEBUG :: mylar.GetComicInfo.334 : mass-add : vari is set to: no
28-Mar-2022 13:41:59 - ERROR :: mylar.excepthook.315 : mass-add : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3-dev/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar3-dev/mylar/importer.py", line 69, in addvialist
    addComictoDB(item['comicid'])
  File "/opt/mylar3-dev/mylar/importer.py", line 142, in addComictoDB
    comic = cv.getComic(comicid, 'comic', series=True)
  File "/opt/mylar3-dev/mylar/cv.py", line 174, in getComic
    return GetComicInfo(comicid, dom, series=series)
  File "/opt/mylar3-dev/mylar/cv.py", line 369, in GetComicInfo
    comic['FirstIssueID'] = dom.getElementsByTagName('id')[0].firstChild.wholeText
IndexError: list index out of range

Traceback (most recent call last):
  File "/opt/mylar3-dev/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/home/mylar/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar3-dev/mylar/importer.py", line 69, in addvialist
    addComictoDB(item['comicid'])
  File "/opt/mylar3-dev/mylar/importer.py", line 142, in addComictoDB
    comic = cv.getComic(comicid, 'comic', series=True)
  File "/opt/mylar3-dev/mylar/cv.py", line 174, in getComic
    return GetComicInfo(comicid, dom, series=series)
  File "/opt/mylar3-dev/mylar/cv.py", line 369, in GetComicInfo
    comic['FirstIssueID'] = dom.getElementsByTagName('id')[0].firstChild.wholeText
IndexError: list index out of range
```
