### ISSUE TITLE
Error Adding New StoryArcs (Exception in GetSeriesYears)

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1147]
**Describe the bug**
Mylar returns a traceback error when attempting to add "[War of the Bounty Hunters](https://comicvine.gamespot.com/war-of-the-bounty-hunters/4045-60780/)" as a new Story Arc.

**CarePackage**
[CarePackage](https://drive.google.com/file/d/1q_HEjsL9VqosKzujhaFjE5otmzYOwFnu/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: docker/master [v0.6.5.2]

**Additional information**
Traceback Error Popup:
```
ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 1230, in addbyid
    response = self.addStoryArc(arcid=query_chk['comicid'], cvarcid=query_chk['cvarcid'], storyarcname=query_chk['comicname'],
  File "/app/mylar3/mylar/webserve.py", line 1491, in addStoryArc
    comicid_results = mylar.cv.getComic(comicid=None, rtype='comicyears', comicidlist=cidlist)
  File "/app/mylar3/mylar/cv.py", line 186, in getComic
    return GetSeriesYears(dom)
  File "/app/mylar3/mylar/cv.py", line 1138, in GetSeriesYears
    fc_id = fc['data-ref-id']
  File "/usr/lib/python3.9/site-packages/bs4/element.py", line 1486, in __getitem__
    return self.attrs[key]
KeyError: 'data-ref-id'
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by jakem742** [comment]
My apologies! Just noticed the existing ticket for this same issue
