### ISSUE TITLE
Files with '_' (underscore) in place of ' ' (space) cause traceback error

### ISSUE THREAD

**Issue by jakem742** [mylar3/mylar3#1157]
**Describe the bug**
The Ultimate Spiderman comics files from GetComics use underscores instead of spaces (eg. "Ultimate_Spider-Man_001_(2000)_(digital)_(Son_of_Ultron-Empire).cbr". When I manually add these files into the relevant folder and press "Recheck Files" on the series I get a traceback error.

**CarePackage**

[CarePackage](https://drive.google.com/file/d/1rnqP-Qg5x6WXc7_lE5MPPO2O-xsMmLnM/view?usp=sharing)

**Environment (please complete the following information):**
 - OS: Linux
 - Branch / commit: docker/master [v0.6.5.2]

**Additional information**
Traceback Error:
```
ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 4220, in forceRescan
    updater.forceRescan(ComicID)
  File "/app/mylar3/mylar/updater.py", line 1128, in forceRescan
    logger.info(module + ' Now checking files for ' + rescan['ComicName'] + ' (' + str(rescan['ComicYear']) + ') in ' + rescan['ComicLocation'])
TypeError: can only concatenate str (not "NoneType") to str
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>

```

**Comment by evilhero** [comment]
Actually in looking in more details at the previous log files and in conjunction with your config, you're getting a few series directory naming collision errors - which basically means you added a series that, due to the limited details in your folder_format string, would have hammered the pre-existing folder for the previous series.  It also looks like you were doing a mass-add missing series via the story arc option.

Normally Mylar will try to append either the book type or some other format (volume, year) if it's available and not used in the other folder - but it can't do that - so it looks like it's just not accepting the location as is - even though the series is being added.

So what you have to do is go into each of those series I listed above, and manually set the folder to the location where you want - keeping in mind that there are other series in your watchlist which would have the same directory if you keep your existing folder format structure.

You should also consider adding more details to your folder format so that these types of situations don't happen as often, although it's not a guarantee, as it can only use the information that's available on CV. As an example, if you add $VolumeN to your folder format, it has to indicate the numeric volume on CV in order for Mylar to use it.

**Comment by jakem742** [comment]
Thanks for the response!

I had been playing around with Story Arcs and did a trial run using "The Thanos Imperative". I don't believe I'd added series for any of the other story arcs, but I was getting confused and will admit to a bit of button mashing aha. It may be that I added the "Ultimates" series to my watchlist which affected this.

The "Ultimates" and "Fantastic Four" series weren't showing in my library, however I could click through to both series from the story arc page and pressing refresh there caused everything to start working again. I'm still not sure exactly what happened, but must've been some issues caused by button mashing on my part. 

I am wondering if the issue was caused by the following order of events:
1. Added "Ultimate Spider Man" to library (from home page)
2. Added "Ultimatum" Story Arc (including Ultimate Spider Man issues)
3. Added Ultimatum story arc to watchlist (?) - Can't remember if I did this, but the fact that series were created means I probably did?
4. Conflict between existing "Ultimate Spider Man" and series created by story arc (possibly?)

A simple refresh of the series in question fixed the problem without adding volume numbers in, but I've added the volume numbers to prevent this happening in future. I do notice that none of these ultimate comics have volume numbers by default.
