### ISSUE TITLE
500 error when clicking grey (i)

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#118]
```
 ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 5715, in IssueInfo
    issuedetails = helpers.IssueDetails(filelocation, IssueID=issueid)
  File "/opt/mylar/mylar/helpers.py", line 1495, in IssueDetails
    issue_data = mylar.cv.getComic(None, 'single_issue', IssueID)
  File "/opt/mylar/mylar/cv.py", line 212, in getComic
    return singleIssue(dom)
  File "/opt/mylar/mylar/cv.py", line 1044, in singleIssue
    issue_info['description'] = drophtml(data['description'])
  File "/opt/mylar/mylar/cv.py", line 1103, in drophtml
    soup = Soup(html, "html.parser")
  File "/home/offspring/.local/lib/python3.7/site-packages/bs4/__init__.py", line 287, in __init__
    elif len(markup) &lt;= 256 and (
TypeError: object of type 'NoneType' has no len()
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.5.0</a>
      </span>
    </div>
    </body>
</html>
```

@brtpob need to know what series & issue number please - likely CV data is missing or incomplete

**Comment by BRTPOB** [comment]
CV was missing the info. I don't remember what series/issue it was, but it was one of the Marvel ones.

**Comment by BRTPOB** [comment]
4050-124822 issue 2 (X-Men/Fantastic Four) (2020). Just reproduced it. The issue shows up, but there's no store date, or anything else but the cover: https://comicvine.gamespot.com/x-menfantastic-four-2/4000-738624/
