### ISSUE TITLE
Generating carepackage from web UI or command line results in traceback.

### ISSUE THREAD

**Issue by DieselTech** [mylar3/mylar3#1203]
**Describe the bug**
Trying to generate a carepackage from either the web UI or command line results in traceback

```
PS C:\Users\Diesel> curl http://192.168.0.100:8090/carepackage -outfile carepkg.zip
curl : 500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/mylar3/mylar/webserve.py", line 7207, in carepackage
    file_to_care = cp.loaders()
  File "/app/mylar3/mylar/carepackage.py", line 103, in loaders
    env_status = self.environment(vers_vals)
  File "/app/mylar3/mylar/carepackage.py", line 112, in environment
    f.write("installation method: %s\n" % (vers_vals['install_type']))
KeyError: 'install_type'
Powered by CherryPy 18.6.1
At line:1 char:1
+ curl http://192.168.0.100:8090/carepackage -outfile carepkg.zip
```

**CarePackage**
That's the problem. Can't generate one. 

**Environment (please complete the following information):**
 - OS: Linux / Docker 
 - Branch / commit: Dev/  835e77572002c2123a708d4fb5a195ed3992ad69 (Nightly) 

**Additional information**
Also reproducible by Ind0r on discord.

**Comment by jakem742** [comment]
I am on the v0.6.7 master (LSIO Docker container), and carepackage generation works just fine. Must be a dev commit.
