### ISSUE TITLE
Error post-processing series with 0000-00-00 Store Date (Publication Date correct)

### ISSUE THREAD

**Issue by Jmatt110** [mylar3/mylar3#1231]
**Describe the bug**
Series: X-Men (1991) has 0000-00-00 as the Store Date. Clicking the 'Show Cover Date' button shows the correct dates. Refreshing the series does not update the Store Dates. Clicking the CV link at the top of the page goes to the correct ComicVine page with the correct issue dates.

Attempting to post-process downloaded issues for this series results in the following errors:

**Logs**
With debug logging enabled, the following is displayed for each issue waiting to be imported.

![image](https://user-images.githubusercontent.com/7138425/172387552-a265038e-a5ae-47db-8fa9-e20231801a54.png)

After repeating the above for each issue, it gets to the end and starts scanning them all again. The following error is shown in the GUI log:

`Job "Folder Monitor (trigger: interval[0:01:00], next run at: 2022-06-07 12:53:25 UTC)" raised an exception
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "C:\Server\Mylar3\mylar\PostProcessor.py", line 3491, in run
    result = PostProcess.Process()
  File "C:\Server\Mylar3\mylar\PostProcessor.py", line 756, in Process
    if any([wv['Status'] == 'Paused', bool(wv['ForceContinuing']) is True]) or (wv['Have'] == wv['Total'] and not any(['Present' in wv['ComicPublished'], helpers.now()[:4] in wv['ComicPublished']])):
TypeError: argument of type 'NoneType' is not iterable`

**Environment**
 - OS: Win 10
 - Branch / commit: Release v0.6.8

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Please post the carepackage as we need to see that in order to see the workflow.

But offhand based on that error, the publication run for that given series is incorrect. If you go to the series details, the publication date range (start - finish) will be provided near the top. I'm guessing that probably has an Unknown value, meaning there's a good chance it didn't finish refreshing the series correctly.

But again, carepackage with debug logging enabled would help more than me guessing.

**Comment by DieselTech** [comment]
You can use a file host like WeTransfer or wormhole.app to upload files that expire after a certain time.
