### ISSUE TITLE
Problem with import when metadata has no issue number associated with it.

### ISSUE THREAD

**Issue by Tam-Lin** [mylar3/mylar3#1232]
**Describe the bug**

I'm trying to rescan my comics folder in a new installation, but am unable to do so.  I think the problem is that the issue was a one-off, and doesn't have any issue data in the ComicBookLover metadata that's already there.  If I disable the "Use Existing Metadata" option on import, things seem to work correctly.

**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 
```

06-Jun-2022 07:19:08 - DEBUG   :: mylar.libraryScan.241 : LibraryScan : Analyzing : <filename>.cbz
06-Jun-2022 07:19:08 - DEBUG   :: mylar.libraryScan.280 : LibraryScan : [IMPORT-CBZ] Metatagging checking enabled.
06-Jun-2022 07:19:08 - INFO    :: mylar.libraryScan.281 : LibraryScan : [IMPORT-CBZ} Attempting to read tags present in filename: /comics/<comicname>/<filename>.cbz
06-Jun-2022 07:19:08 - INFO    :: mylar.IssueDetails.1625 : LibraryScan : Tag returned as being: comment
06-Jun-2022 07:19:08 - INFO    :: mylar.IssueDetails.1750 : LibraryScan : CBL Tagging.
06-Jun-2022 07:19:08 - INFO    :: mylar.libraryScan.288 : LibraryScan : issueinfo: {'metadata': {'title': '<comicname>', 'series': '<seriesname>', 'volume': None, 'issue_number': None, 'summary': 'None', 'notes': 'None', 'year': None, 'month': None, 'day': None, 'writer': None, 'penciller': None, 'inker': None, 'colorist': None, 'letterer': None, 'cover_artist': None, 'editor': None, 'publisher': None, 'webpage': 'None', 'pagecount': 'None'}, 'IssueImage': 'None', 'datamode': 'file', 'metadata_source': {'metadata_source': 'ComicVine', 'metadata_type': 'comicbooklover'}}
06-Jun-2022 07:19:08 - INFO    :: mylar.libraryScan.295 : LibraryScan : [IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
06-Jun-2022 07:19:08 - DEBUG   :: mylar.libraryScan.298 : LibraryScan : [IMPORT-CBZ] Series Name: <seriesname>
06-Jun-2022 07:19:08 - DEBUG   :: mylar.libraryScan.301 : LibraryScan : Dynamic-ComicName: <seriesname>
06-Jun-2022 07:19:08 - ERROR   :: mylar.scanLibrary.629 : LibraryScan : [IMPORT] Unable to complete the scan: 'parsed'
06-Jun-2022 07:19:08 - ERROR   :: mylar.scanLibrary.630 : LibraryScan : Traceback (most recent call last):
  File "/app/mylar3/mylar/librarysync.py", line 627, in scanLibrary
    soma = libraryScan(queue=queue)
  File "/app/mylar3/mylar/librarysync.py", line 318, in libraryScan
    issue_number = i['parsed']['issue_number']
KeyError: 'parsed'

```
**Environment (please complete the following information):**
 - OS: Ubuntu, running docker linuxserver docker image
 - Branch / commit: 0.6.8 (master)

**Additional information**
Add any other information about the problem here.

**Comment by barbequesauce** [comment]
What's the file name?

**Comment by evilhero** [comment]
Comicbooklover is a really old scheme for metadata that I didn't think was being used by anything.  Did you just tag with CBL metadata and not use CR tagging as well? 

Did you edit out the metadata prior to pasting the log snippet, or is that verbatim what the logs provided?

**Comment by Tam-Lin** [comment]
I used ComicBookLover many years ago; the data or lack thereof is probably left over from that.  I choose bad replacements for the metadata; let me fix that.

**Comment by Tam-Lin** [comment]
So I did insert <filename>, <seriesname>, and <comicname>, but other than that, that's a copy of what's in the debug log.

**Comment by evilhero** [comment]
So the metadata within the file is ``{'title': '<comicname>', 'series': '<seriesname>' ``?

If there is no issue number within the filename, the importer will not import it at all.

Now if there's an issue number in the filename, and the metadata is literally xml fields like I just pasted - then that's an issue with the cbl aspect of the importer. In that case, it doesn't surprise me that disabling the metadata aspect of the importer allows it to work without problems as then it's solely relying on filename parsing to determine what it is.

All that being said the importer is going thru a rewrite / refactor so if this is an issue with the cbl aspect it could be addressed in the rewrite.

But again, without seeing the unaltered cbl metadata, or a carepackage showing the workflow of the import of the cbl - the cbl aspect is not going to be accurately represented as not very many people use it (myself being one).
