### ISSUE TITLE
Crash on requirements check when using a custom data dir

### ISSUE THREAD

**Issue by kounch** [mylar3/mylar3#1237]
**Describe the bug**

Crash on requirements check when using a custom data dir

**CarePackage**

[carepackage_5eaffc4547aea74946e31519b4aedcaf11ad9d19_(master).zip](https://github.com/mylar3/mylar3/files/8883537/carepackage_5eaffc4547aea74946e31519b4aedcaf11ad9d19_.master.zip)

**Environment (please complete the following information):**
 - OS: Arch Linux ARM
 - Branch / commit: master

**Additional information**

When using a custom data dir, e.g. mylar3 launched with:

`python3 /var/opt/mylar3/master/Mylar.py --nolaunch --datadir=/var/opt/mylar3/.Mylar`

A crash happens on startup:

```
jun 11 10:06:13 themyscira python3[18291]: Initializing startup sequence....
jun 11 10:06:13 themyscira python3[18291]: Error in sys.excepthook:
jun 11 10:06:13 themyscira python3[18291]: TypeError: RotatingLogger.handle_exception() missing 1 required positional argument: 'exc_traceback'
jun 11 10:06:13 themyscira python3[18291]: Original exception was:
jun 11 10:06:13 themyscira python3[18291]: Traceback (most recent call last):
jun 11 10:06:13 themyscira python3[18291]:   File "/var/opt/mylar3/master/Mylar.py", line 496, in <module>
jun 11 10:06:13 themyscira python3[18291]:     main()
jun 11 10:06:13 themyscira python3[18291]:   File "/var/opt/mylar3/master/Mylar.py", line 462, in main
jun 11 10:06:13 themyscira python3[18291]:     r.loaders()
jun 11 10:06:13 themyscira python3[18291]:   File "/var/opt/mylar3/master/mylar/req_test.py", line 47, in loaders
jun 11 10:06:13 themyscira python3[18291]:     self.check_the_pip()
jun 11 10:06:13 themyscira python3[18291]:   File "/var/opt/mylar3/master/mylar/req_test.py", line 55, in check_the_pip
jun 11 10:06:13 themyscira python3[18291]:     with open(self.file, 'r')as f:
jun 11 10:06:13 themyscira python3[18291]: FileNotFoundError: [Errno 2] No existe el fichero o el directorio: '/var/opt/mylar3/.Mylar/requirements.txt'
```

After that, some features (like Activity/Jobs) do not work properly.

I have temporarily fixed it by copying ```requirements.txt``` from the application dir to the data dir, but it would be nice if the requirements check also tested the program dir

**Comment by kounch** [comment]
Sorry, perhaps i didn't explain myself. I copied the file to stop the exception from happening.

What i am trying to report as a bug is that it looks like that the latest version of mylar3 is trying to search for the `requirements.txt` file at the wrong place (`data_dir`) and that should be fixed.

**Comment by evilhero** [comment]
paste a carepackage.

**Comment by evilhero** [comment]
Update your version if you haven't already, and do another carepackage. Latest master is v0.6.8

**Comment by kounch** [comment]
OK. Give me some minutes while i update and try again. Meanwhile, I was looking at the code, and i think that this is happening because my install is not in a docker.

In `req_test.py` i see this, which would explain what is happening:

`class Req(object):

    def __init__(self):
        self.file = os.path.join(mylar.DATA_DIR, 'requirements.txt')
        if mylar.INSTALL_TYPE == 'docker':
            self.file = os.path.join(mylar.PROG_DIR, 'requirements.txt')`

**Comment by kounch** [comment]
No new updates available. Version is reported as:

Version: 5eaffc4547aea74946e31519b4aedcaf11ad9d19 (master)

New carepackage attached here

[carepackage_5eaffc4547aea74946e31519b4aedcaf11ad9d19_(master)-2.zip](https://github.com/mylar3/mylar3/files/8921644/carepackage_5eaffc4547aea74946e31519b4aedcaf11ad9d19_.master.-2.zip)

**Comment by barbequesauce** [comment]
One more update please
