### ISSUE TITLE
500 internal server error when attempting to recheck files.

### ISSUE THREAD

**Issue by Berserkir-Wolf** [mylar3/mylar3#1276]
**Describe the bug**
Unable to force recheck of files manually.

When pressing the "recheck files" button, an error message appears on screen. It does not appear in the logs, and it references CherryPy encountering a 500 internal server error directly.
The error remains whether connecting locally, remotely, directly, or via reverse proxy.

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Branch / commit: 0.6.9 / master / "Sometimes when you fall, you fly"

**Additional information**
Add any other information about the problem here.

**Comment by Berserkir-Wolf** [comment]
```html
ERROR<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "c:\Python38\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "c:\Python38\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "c:\Python38\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Python38\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Services\Mylar3\mylar\webserve.py", line 4258, in forceRescan
    updater.forceRescan(ComicID)
  File "c:\Services\Mylar3\mylar\updater.py", line 1133, in forceRescan
    logger.info(module + ' Now checking files for ' + rescan['ComicName'] + ' (' + str(rescan['ComicYear']) + ') in ' + rescan['ComicLocation'])
TypeError: can only concatenate str (not "NoneType") to str
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.1</a>
      </span>
    </div>
    </body>
</html>
```

**Comment by Berserkir-Wolf** [comment]
[carepackage_v0.6.9.zip](https://github.com/mylar3/mylar3/files/9336842/carepackage_v0.6.9.zip)

**Comment by evilhero** [comment]
Possibly permissions related due to network mapping, but hard to determine due to logging level.

Mylar has to copy the file from the download location to the cache folder in order to metatag items. You're getting comictagger errors during post-processing thats related to not being able to resolve the pathing properly. In this case, I'm assuming it's trying to move the file from your download network location to the local drive, and failing in accessing said file.

Before any of this, enable debug logging so that full logs are captured. 

Couple things you can try:
- set your Comic Location path to a mapped network drive letter as opposed to the direct UNC mapping.
- delete and readd the series you're trying so that it can try to create the directory without error (ie.  the series directory would then show as a mapped location as opposed to UNC mapping)
- try and download an item using the magnifying glass and see if that works.

There is no need to Recheck Files during post-processing, as the files will update on screen once it's completed (you'll also get a toaster notif) 

You can also try changing your comic location path to a local drive location temporarily, add a series and see if the problem persists when it's local. If it works, then it's a network pathing / permissions problem.

Once you get a debug log showing the error and the lead up, can you post the updated carepackage as the debug logs would be necessary to see what's happening.

As an aside, if you go to the 1st tab of the configuration, you'll probably see some warnings as to your python packages being outdated - did you run the requirements.txt install or was this a previous version of mylar you just updated?

**Comment by Berserkir-Wolf** [comment]
I have Mylar running through nssm - so no mapped drive option (hence UNC path). Issue occurs if I have local drive as download location as well.

The comic location was created by Mylar - permissions there all check out successfully, and the user is part of the group with full rights to that path. I've added direct permissions for the user that Mylar is running as as well (permissions are managed in a local Active Directory instance). Removing and re-adding the comic after having manually moved the files checks them and identifies which issues I have successfully, and allows for successful renaming as well (just to verify permissions).

Magnifying glass search seems to work - I get a "successfully snatched" toast notification.

Only reason I tried to recheck is a bunch of files got snatched but not post-processed, so I manually moved them and wanted to force a process.

No errors showed for python packages, but I've updated the items in requirements and my pip module as well - was a version update of Mylar, not a fresh install.


[New carepackage_v0.6.9.zip with debug logging on](https://github.com/mylar3/mylar3/files/9339935/carepackage_v0.6.9.zip)

**Comment by evilhero** [comment]
Try running mylar without using nssm so you can see the console logging in real-time. You can manually map a network drive to a letter and attach nssm to that, but you can also do it if run via cli. 

There are problems when using UNC pathing in some circumstances, but the fact you're using AD with UNC pathing just increases the scope of what the problem could be. Mylar can't stat the file to get the info it needs, so it's failing at that point (based on the initial log at least). Try to eliminate the extras, and narrow down the problem. If you can't manually post-process an issue, it's an overall issue. 

You're also getting CT errors in relation to creating directories in the cache folder which craps out the metatagging of the post-processing.

Keeping in mind if it downloads the file to a location not local, when it copies it back to the cache folder permissions are probably not what they should be (possibly due to AD, and maybe the way you have your parent / child permissions flowing).

**Comment by Berserkir-Wolf** [comment]
Seems to be stable with a local cache directory and a local DDL folder, despite having the same permissions set on both directories. Seems like UNC pathing errors when using via DFS (shouldn't surprise me, it _is_ a Microsoft product).

Just seemed strange that it was only Mylar having the error, none of the other '*arrs' have it.

Weirdly, running in console (and then via nssm with stderr/stdout/stdin redirected to text files) still shows python module errors, even if I give the service user admin privileges. If I try to `pip install problematic_package` it tells me that it's already installed, so not sure what's going on there. Might be worth migrating mylar across to my TrueNAS box instead of my 2019 one.

**Comment by barbequesauce** [comment]
Try seeing if you have multiple versions of python installed - possibly it's coming from different paths depending on the user account envvars...

**Comment by Berserkir-Wolf** [comment]
Only one version installed, added to system PATH rather than user PATH.
