### ISSUE TITLE
Running a scan causes a traceback and thus import results doesn't show or become populated

### ISSUE THREAD

**Issue by ducky0518** [mylar3/mylar3#1303]
**Describe the bug**
Running a scan import causes an exception (traceback) thus causing the scan to not complete.

<html>
<body>

2022-10-27 16:46:07 | ERROR | Traceback (most recent call last):File "/app/mylar3/mylar/librarysync.py", line 627, in scanLibrarysoma = libraryScan(queue=queue)File "/app/mylar3/mylar/librarysync.py", line 191, in libraryScanwatchcomic = re.sub('[\_\#\,\/\:\;\.\-\!\$\%\&\+\'\?\@]', '', watch['ComicName_Filesafe'])File "/usr/lib/python3.10/re.py", line 209, in subreturn _compile(pattern, flags).sub(repl, string, count)TypeError: expected string or bytes-like object
-- | -- | --
2022-10-27 16:46:07 | ERROR | [IMPORT] Unable to complete the scan: expected string or bytes-like object

</body>
</html>

**CarePackage**
See attached
[carepackage_083c0e0d97f9f4fb85957f1970d33f433e9d2ea9_(python3-dev).zip](https://github.com/mylar3/mylar3/files/9881560/carepackage_083c0e0d97f9f4fb85957f1970d33f433e9d2ea9_.python3-dev.zip)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Branch / commit: [083c0e0d97f9f4fb85957f1970d33f433e9d2ea9] (python3-dev)

**Additional information**
The import results button never shows due to this traceback. Let me know if you need anything else. Thanks!

**Comment by ducky0518** [comment]
FYI - Restarting mylar did fix this issue and it hasn't come back since. Not sure if the information in the carepackage is enough to figure out what happened anyway.
