### ISSUE TITLE
config.ini wiped clean after windows crash

### ISSUE THREAD

**Issue by Roshri** [mylar3/mylar3#1309]
Pretty self explanatory. 
Windows crashed and when I restarted my local machine and tried to fire up mylar, it said config.ini had empty headers
```log language set to en_GB
Initializing startup sequence....
Traceback (most recent call last):
  File "C:\Users\roshr\Documents\WindowsPowerShell\mylar3-0.6.4\mylar.py", line 496, in <module>
    main()
  File "C:\Users\roshr\Documents\WindowsPowerShell\mylar3-0.6.4\mylar.py", line 279, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "C:\Users\roshr\Documents\WindowsPowerShell\mylar3-0.6.4\mylar\__init__.py", line 216, in initialize
    CONFIG = cc.read(startup=True)
  File "C:\Users\roshr\Documents\WindowsPowerShell\mylar3-0.6.4\mylar\config.py", line 591, in read
    self.config_vals()
  File "C:\Users\roshr\Documents\WindowsPowerShell\mylar3-0.6.4\mylar\config.py", line 464, in config_vals
    self.config = config.read_file(codecs.open(self._config_file, 'r', 'utf8')) #read(self._config_file)
  File "C:\CommandLineTools\Python\Python310\lib\configparser.py", line 719, in read_file
    self._read(f, source)
  File "C:\CommandLineTools\Python\Python310\lib\configparser.py", line 1086, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\roshr\\Documents\\WindowsPowerShell\\mylar3-0.6.4\\config.ini', line: 1```

had to create a fresh one from the .zip of the latest release, but, of course now I need to set up everything again.
Probably bad management from my side since I didn't create a backup, but reporting just in case

**Comment by evilhero** [comment]
Yeah there's not much we can do unfortunately about the ini being corrupted during a failed write outside of making sure that people are aware of fhe backup options within Mylar and use those. 

The quick rundown of the built-in backup option can be found in the wiki [here](https://github.com/mylar3/mylar3/wiki/Auto-backups)
