### ISSUE TITLE
On-snatch script fails with TypeError

### ISSUE THREAD

**Issue by labrys** [mylar3/mylar3#1318]
**Describe the bug**
On-snatch script fails with `TypeError: environment can only contain strings`.  The cause is the `mylar_comicname` is stored as bytes.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10] Windows or Linux
 - Branch / commit: [e.g. Dev/38aksi1] Master / 5c1b5e2 

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Post a carepackage with debug logging turned on so we can see what the env's are being passed.

Keep in mind that Mylar copies your current environment before appending its own values to the copy and then writing said copy back to your environment as the sole version. 

It's quite possible that bytes exist in another environment variable outside of Mylar's control.

**Comment by labrys** [comment]
# Given a simple script:

![image](https://user-images.githubusercontent.com/1867464/210899068-26de1fcd-29b2-4e5e-8e78-fcf7688994ed.png)

```python
import argparse
import logging
import sys

log = logging.getLogger(__name__)

parser = argparse.ArgumentParser()
parser.add_argument('args', nargs='*')


def main(args=None):
    """Log all args passed on the command line."""
    logging.basicConfig(filename='test_script.log', level=logging.DEBUG)
    parsed = parser.parse_args(args)
    log.info(f'Script called with {parsed.args}')
    return 0


if __name__ == "__main__":
    sys.exit(main())
```

# After a snatch occurs, script was not triggered and following error appears in logs:

```
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.2981 : SEARCH-QUEUE : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
05-Jan-2023 18:18:11 - INFO    :: mylar.searcher.2999 : SEARCH-QUEUE : nzbprov: experimental
05-Jan-2023 18:18:11 - INFO    :: mylar.searcher.3000 : SEARCH-QUEUE : provider_stat: {'type': 'experimental', 'lastrun': 1672960367.8108609, 'active': True, 'hits': 13, 'id': 101}
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3072 : SEARCH-QUEUE : [PAYLOAD-NONE] Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL: False]
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3101 : SEARCH-QUEUE : Status code returned: 200
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3133 : SEARCH-QUEUE : filename within nzb: Star Wars - Obi-Wan 005 (2022) (Digital) (Kileko-Empire).nzb
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3158 : SEARCH-QUEUE : [FILENAME] filename (remove chars): StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3161 : SEARCH-QUEUE : [FILENAME] nzbname : StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3163 : SEARCH-QUEUE : [FILENAME] end nzbname: StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:18:11 - INFO    :: mylar.searcher.3172 : SEARCH-QUEUE : filen: StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb -- nzbname: Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire are not identical. Storing extra value as : StarWars-Obi-Wan0052022DigitalKileko-Empire
05-Jan-2023 18:18:11 - DEBUG   :: mylar.searcher.3181 : SEARCH-QUEUE : Cache Directory successfully found at : C:\usr\local\github\mylar3\mylar3\cache. Ensuring proper permissions.
05-Jan-2023 18:18:11 - DEBUG   :: mylar.sender.46 : SEARCH-QUEUE : parameters set to {'mode': 'addurl', 'name': 'http://192.168.0.105:8090/api?apikey=52d31ed2f1ad57bd6f2d12b9f130d799&cmd=downloadNZB&nzbname=Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire.nzb', 'cmd': 'downloadNZB', 'nzbname': 'Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire.nzb', 'output': 'json', 'priority': '-100'}
05-Jan-2023 18:18:11 - DEBUG   :: mylar.sender.48 : SEARCH-QUEUE : sending now to http://localhost:8080/api
05-Jan-2023 18:18:13 - INFO    :: mylar.searcher.3648 : SEARCH-QUEUE : sendtosab: {'status': True, 'nzo_id': 'SABnzbd_nzo_93d7l5su', 'queue': {'mode': 'queue', 'search': 'SABnzbd_nzo_93d7l5su', 'output': 'json', 'apikey': '1bfbfe3386c947289a8c52b248b1bcac'}, 'comicid': '142775', 'issueid': '946722', 'apicall': True, 'download_info': {'provider': 'experimental', 'id': '747262031'}}
05-Jan-2023 18:18:13 - DEBUG   :: mylar.fetchData.202 : CP Server Thread-7 : Received API command: downloadNZB
05-Jan-2023 18:18:13 - INFO    :: mylar.searcher.3664 : SEARCH-QUEUE : Successfully sent nzb file to SABnzbd
05-Jan-2023 18:18:13 - DEBUG   :: mylar.script_env.3574 : SEARCH-QUEUE : Initiating on-snatch script detection.
05-Jan-2023 18:18:13 - DEBUG   :: mylar.script_env.3584 : SEARCH-QUEUE : snatch script detected...enabling: C:\Python\3.11\python.exe h:\test_script.py
05-Jan-2023 18:18:13 - DEBUG   :: mylar.script_env.3587 : SEARCH-QUEUE : Executing command ['C:Python3.11python.exe', 'h:test_script.py']
Traceback (most recent call last):
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 2496, in searchforissue
    foundNZB, prov = search_init(
                     ^^^^^^^^^^^^
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 538, in search_init
    findit = search_the_matrix(scarios)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 4209, in search_the_matrix
    return NZB_SEARCH(
           ^^^^^^^^^^^
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 1392, in NZB_SEARCH
    verification(verified_matches, is_info)
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 1442, in verification
    searchresult = searcher(
                   ^^^^^^^^^
  File "C:\usr\local\github\mylar3\mylar3\mylar\search.py", line 3706, in searcher
    snatchitup = helpers.script_env('on-snatch', snatch_vars)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\usr\local\github\mylar3\mylar3\mylar\helpers.py", line 3589, in script_env
    subprocess.call(script_cmd, env=dict(mylar_env))
  File "C:\Python\3.11\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\3.11\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\3.11\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: environment can only contain strings
```

**Comment by labrys** [comment]
# After [labrys:patch-1](https://github.com/labrys/mylar3/tree/patch-1):

```
05-Jan-2023 18:27:07 - DEBUG   :: mylar.searcher.2981 : SEARCH-QUEUE : [FAILED_DOWNLOAD_CHECKER] This is not in the failed downloads list. Will continue with the download.
05-Jan-2023 18:27:07 - INFO    :: mylar.searcher.2999 : SEARCH-QUEUE : nzbprov: experimental
05-Jan-2023 18:27:07 - INFO    :: mylar.searcher.3000 : SEARCH-QUEUE : provider_stat: {'type': 'experimental', 'lastrun': 1672960864.9690135, 'active': True, 'hits': 15, 'id': 101}
05-Jan-2023 18:27:07 - DEBUG   :: mylar.searcher.3072 : SEARCH-QUEUE : [PAYLOAD-NONE] Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL: False]
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3101 : SEARCH-QUEUE : Status code returned: 200
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3133 : SEARCH-QUEUE : filename within nzb: Star Wars - Obi-Wan 005 (2022) (Digital) (Kileko-Empire).nzb
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3158 : SEARCH-QUEUE : [FILENAME] filename (remove chars): StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3161 : SEARCH-QUEUE : [FILENAME] nzbname : StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3163 : SEARCH-QUEUE : [FILENAME] end nzbname: StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb
05-Jan-2023 18:27:08 - INFO    :: mylar.searcher.3172 : SEARCH-QUEUE : filen: StarWars-Obi-Wan0052022DigitalKileko-Empire.nzb -- nzbname: Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire are not identical. Storing extra value as : StarWars-Obi-Wan0052022DigitalKileko-Empire
05-Jan-2023 18:27:08 - DEBUG   :: mylar.searcher.3181 : SEARCH-QUEUE : Cache Directory successfully found at : C:\usr\local\github\mylar3\mylar3\cache. Ensuring proper permissions.
05-Jan-2023 18:27:08 - DEBUG   :: mylar.sender.46 : SEARCH-QUEUE : parameters set to {'mode': 'addurl', 'name': 'http://192.168.0.105:8090/api?apikey=908cd70386a6fa26b06a4e1d07db6cd7&cmd=downloadNZB&nzbname=Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire.nzb', 'cmd': 'downloadNZB', 'nzbname': 'Star.Wars.-.Obi-Wan.005.2022.Digital.Kileko-Empire.nzb', 'output': 'json', 'priority': '-100'}
05-Jan-2023 18:27:08 - DEBUG   :: mylar.sender.48 : SEARCH-QUEUE : sending now to http://localhost:8080/api
05-Jan-2023 18:27:10 - INFO    :: mylar.searcher.3648 : SEARCH-QUEUE : sendtosab: {'status': True, 'nzo_id': 'SABnzbd_nzo_g9qx1ojb', 'queue': {'mode': 'queue', 'search': 'SABnzbd_nzo_g9qx1ojb', 'output': 'json', 'apikey': '1bfbfe3386c947289a8c52b248b1bcac'}, 'comicid': '142775', 'issueid': '946722', 'apicall': True, 'download_info': {'provider': 'experimental', 'id': '747262031'}}
05-Jan-2023 18:27:10 - DEBUG   :: mylar.fetchData.202 : CP Server Thread-10 : Received API command: downloadNZB
05-Jan-2023 18:27:10 - INFO    :: mylar.searcher.3664 : SEARCH-QUEUE : Successfully sent nzb file to SABnzbd
05-Jan-2023 18:27:10 - DEBUG   :: mylar.script_env.3574 : SEARCH-QUEUE : Initiating on-snatch script detection.
05-Jan-2023 18:27:10 - DEBUG   :: mylar.script_env.3584 : SEARCH-QUEUE : snatch script detected...enabling: C:\Python\3.11\python.exe h:\test_script.py
05-Jan-2023 18:27:10 - DEBUG   :: mylar.script_env.3587 : SEARCH-QUEUE : Executing command ['C:Python3.11python.exe', 'h:test_script.py']
05-Jan-2023 18:27:10 - ERROR   :: mylar.script_env.3601 : SEARCH-QUEUE : Invalid Mylar environment variable: 'mylar_comicname' = b'Star Wars: Obi-Wan'
05-Jan-2023 18:27:10 - INFO    :: mylar.searcher.3710 : SEARCH-QUEUE : Could not Successfully submit on-grab script as requested. Please check logs...
```

**Comment by barbequesauce** [comment]
Suggest you edit out your apikeys

**Comment by labrys** [comment]
Thanks for the suggestion, but not necessary, that's a single dev instance that I spun up for this example.

**Comment by barbequesauce** [comment]
That patch has been running clean on my system for two weeks now - if you'd like to PR it I'm happy to merge it in, thanks @labrys !

**Comment by labrys** [comment]
@barbequesauce That doesn't fix the error, it just prevents the crash and logs the error.  The error should be fixed by making sure all environment variables are unicode strings.

**Comment by barbequesauce** [comment]
Noted, I'll take a pass at that over the weekend - thanks again
