### ISSUE TITLE
Scanner breaks down after a while

### ISSUE THREAD

**Issue by ScuttleSE** [mylar3/mylar3#1372]
After running Mylar for a few days, with a lot of scanning of existing folders, the scanner seems to break down and immediatly spit out an errormessage when scanning. Only way to get it running again is to restart Mylar

Scanning a folder:
```

10-Jul-2023 12:58:08 - INFO :: mylar.configure.1120 : CP Server Thread-6 : [DOCKER-AWARE] Docker installation detected.
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1180 : CP Server Thread-6 : Ignored Publishers: []
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1203 : CP Server Thread-6 : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1215 : CP Server Thread-6 : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1227 : CP Server Thread-6 : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1241 : CP Server Thread-6 : [COMICTAGGER] Version detected: 1.3.5
10-Jul-2023 12:58:08 - INFO :: mylar.validateAndCreateDirectory.1830 : CP Server Thread-6 : [DIRECTORY-CHECK] Found ddl location directory: /config/mylar/cache
10-Jul-2023 12:58:08 - INFO :: mylar.configure.1334 : CP Server Thread-6 : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
10-Jul-2023 12:58:08 - INFO :: mylar.comicScan.5779 : CP Server Thread-6 : Now updating config...
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.43 : LibraryScan : Scanning comic directory: /downloads/Incoming/Old-Library
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.158 : LibraryScan : I have successfully discovered & parsed a total of 1 files....analyzing now
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.159 : LibraryScan : I have not been able to determine what 0 files are
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.160 : LibraryScan : However, 0 out of the 0 files are in a cbz format, which may contain metadata.
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.161 : LibraryScan : [ERRORS] I have encountered 0 file-scanning errors during the scan, but have recorded the necessary information.
10-Jul-2023 12:58:08 - INFO :: mylar.libraryScan.169 : LibraryScan : loading in the watchlist to see if a series is being watched already...
10-Jul-2023 12:58:08 - ERROR :: mylar.scanLibrary.623 : LibraryScan : [IMPORT] Unable to complete the scan: expected string or bytes-like object
10-Jul-2023 12:58:08 - ERROR :: mylar.scanLibrary.624 : LibraryScan : Traceback (most recent call last):
  File "/app/mylar3/mylar/librarysync.py", line 621, in scanLibrary
    soma = libraryScan(queue=queue)
  File "/app/mylar3/mylar/librarysync.py", line 191, in libraryScan
    watchcomic = re.sub('[\_\#\,\/\:\;\.\-\!\$\%\&\+\'\?\@]', '', watch['ComicName_Filesafe'])
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```

Scanning the same folder, with the same file in it after restarting:

```

10-Jul-2023 13:00:26 - INFO :: mylar.configure.1120 : CP Server Thread-9 : [DOCKER-AWARE] Docker installation detected.
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1180 : CP Server Thread-9 : Ignored Publishers: []
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1203 : CP Server Thread-9 : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1215 : CP Server Thread-9 : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1227 : CP Server Thread-9 : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1241 : CP Server Thread-9 : [COMICTAGGER] Version detected: 1.3.5
10-Jul-2023 13:00:26 - INFO :: mylar.validateAndCreateDirectory.1830 : CP Server Thread-9 : [DIRECTORY-CHECK] Found ddl location directory: /config/mylar/cache
10-Jul-2023 13:00:26 - INFO :: mylar.configure.1334 : CP Server Thread-9 : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
10-Jul-2023 13:00:26 - INFO :: mylar.comicScan.5779 : CP Server Thread-9 : Now updating config...
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.43 : LibraryScan : Scanning comic directory: /downloads/Incoming/Old-Library
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.158 : LibraryScan : I have successfully discovered & parsed a total of 1 files....analyzing now
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.159 : LibraryScan : I have not been able to determine what 0 files are
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.160 : LibraryScan : However, 0 out of the 0 files are in a cbz format, which may contain metadata.
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.161 : LibraryScan : [ERRORS] I have encountered 0 file-scanning errors during the scan, but have recorded the necessary information.
10-Jul-2023 13:00:26 - INFO :: mylar.libraryScan.169 : LibraryScan : loading in the watchlist to see if a series is being watched already...
10-Jul-2023 13:00:27 - INFO :: mylar.libraryScan.216 : LibraryScan : Successfully loaded 9330 series from your watchlist.
10-Jul-2023 13:00:27 - INFO :: mylar.libraryScan.281 : LibraryScan : [IMPORT-CBZ} Attempting to read tags present in filename: /downloads/Incoming/Old-Library/Richie Rich Dollars and Cents Vol.1963 #108.cbz
10-Jul-2023 13:00:27 - INFO :: mylar.IssueDetails.1657 : LibraryScan : Tag returned as being: xml
10-Jul-2023 13:00:27 - INFO :: mylar.libraryScan.288 : LibraryScan : issueinfo: {'metadata': {'title': 'None', 'series': 'Richie Rich Dollars and Cents', 'volume': '1963', 'issue_number': '108', 'summary': 'None', 'notes': 'Tagged with ComicTagger 1.1.31-rc1 using info from Comic Vine on 2019-04-29 01:08:13.  [Issue ID 212207]\n\nScraped metadata from ComicVine [CVDB212207].', 'year': 'None', 'month': 'None', 'day': 'None', 'writer': None, 'penciller': None, 'inker': None, 'colorist': None, 'letterer': None, 'cover_artist': None, 'editor': None, 'publisher': 'Harvey', 'webpage': 'https://comicvine.gamespot.com/richie-rich-dollars-and-cents-108/4000-212207/', 'pagecount': '37'}, 'IssueImage': 'None', 'datamode': 'file', 'metadata_source': {'metadata_source': 'ComicVine', 'metadata_type': 'comicinfo.xml'}}
10-Jul-2023 13:00:27 - INFO :: mylar.libraryScan.295 : LibraryScan : [IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
10-Jul-2023 13:00:29 - INFO :: mylar.GetImportList.1434 : LibraryScan : tempseries:{'IssueID': '212207', 'ComicID': '31682', 'Issue_Name': None, 'ComicName': 'Richie Rich Dollars and Cents', 'Issue_Number': '108'}
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.638 : LibraryScan : [IMPORT] Parsing/Reading of files completed!
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.639 : LibraryScan : [IMPORT] Attempting to import 1 files into your watchlist.
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.640 : LibraryScan : [IMPORT-BREAKDOWN] Files with ComicIDs successfully extracted: 1
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.641 : LibraryScan : [IMPORT-BREAKDOWN] Files that had to be parsed: 0
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.642 : LibraryScan : [IMPORT-BREAKDOWN] Files that were unable to be parsed: 0
10-Jul-2023 13:00:29 - INFO :: mylar.scanLibrary.643 : LibraryScan : [IMPORT-BREAKDOWN] Files that caused errors during the import: 0
10-Jul-2023 13:00:29 - INFO :: mylar.ThreadcomicScan.5804 : CP Server Thread-9 : Successfully scanned in directory. Enabling the importResults button now.

```

**Comment by evilhero** [comment]
I'm going to guess that because it's failing at loading in the watchlist that a series hasn't finished being added /refreshed and it's failing to convert the seriesname as it's saying it's None.

We can add an allowance to just pass by series that aren't finished being added - I believe that will get around this error.
