### ISSUE TITLE
TypeError in `os.stat` call in `validateAndCreateDirectory`

### ISSUE THREAD

**Issue by OddBloke** [mylar3/mylar3#1376]
**Describe the bug**

I see the following traceback in the logs when any issue of a (recently-added) series attempts post-processing:

```
Jul 18 02:53:57 ringle mylar3[3736292]: 18-Jul-2023 02:53:57 - ERROR :: mylar.excepthook.315 : Thread-12 (Process) : Uncaught exception: Traceback (most recent call last):
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/logger.py", line 337, in new_run
Jul 18 02:53:57 ringle mylar3[3736292]:     old_run(*args, **kwargs)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Jul 18 02:53:57 ringle mylar3[3736292]:     self._target(*self._args, **self._kwargs)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/PostProcessor.py", line 2200, in Process
Jul 18 02:53:57 ringle mylar3[3736292]:     self.Process_next(comicid, issueid, issuenumOG, ml, stat)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/PostProcessor.py", line 3169, in Process_next
Jul 18 02:53:57 ringle mylar3[3736292]:     checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True, module=module)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/filechecker.py", line 1829, in validateAndCreateDirectory
Jul 18 02:53:57 ringle mylar3[3736292]:     if os.path.exists(dir):
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
Jul 18 02:53:57 ringle mylar3[3736292]:     os.stat(path)
Jul 18 02:53:57 ringle mylar3[3736292]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Jul 18 02:53:57 ringle mylar3[3736292]: Traceback (most recent call last):
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/logger.py", line 337, in new_run
Jul 18 02:53:57 ringle mylar3[3736292]:     old_run(*args, **kwargs)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/usr/lib/python3.10/threading.py", line 953, in run
Jul 18 02:53:57 ringle mylar3[3736292]:     self._target(*self._args, **self._kwargs)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/PostProcessor.py", line 2200, in Process
Jul 18 02:53:57 ringle mylar3[3736292]:     self.Process_next(comicid, issueid, issuenumOG, ml, stat)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/PostProcessor.py", line 3169, in Process_next
Jul 18 02:53:57 ringle mylar3[3736292]:     checkdirectory = filechecker.validateAndCreateDirectory(comlocation, True, module=module)
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/app/mylar3/mylar/filechecker.py", line 1829, in validateAndCreateDirectory
Jul 18 02:53:57 ringle mylar3[3736292]:     if os.path.exists(dir):
Jul 18 02:53:57 ringle mylar3[3736292]:   File "/usr/lib/python3.10/genericpath.py", line 19, in exists
Jul 18 02:53:57 ringle mylar3[3736292]:     os.stat(path)
Jul 18 02:53:57 ringle mylar3[3736292]: TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

When _first_ adding and downloading the series, I encountered the error I fixed in #1374 which required a restart of mylar3, so I suspect the issue will stem from that.

**CarePackage**

(I'm going to debug this myself for a bit, will post more info if I run into a wall.)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: Docker latest

**Additional information**
Add any other information about the problem here.

**Comment by OddBloke** [comment]
`ComicLocation` for the series in question is NULL, so that explains where the `None` is coming from.

**Comment by OddBloke** [comment]
Hmm, it looks like I don't have the logs from before the restart to fix the DDL queue, so I can't debug this any further. (I've addressed it by deleting/re-adding the series.)

**Comment by evilhero** [comment]
If Comic Location is NULL, then the problem actually stems from the series not being successfully added.

 It's in an incomplete state, so when you go to post-process because it never completed being added it just NULLS the values until it gets refreshed/corrected or you delete the series (or restart Mylar and it clears them out).

There was an issue where if a series was refreshing while a post-processing run was occurring and the series had temporarily nulled some values, that it would throw an error - but this is a bit different as it's not temporary.
