### ISSUE TITLE
Mylar wont Start searching / downloading

### ISSUE THREAD

**Issue by Galardin** [mylar3/mylar3#1396]
**Describe the bug**
I moved to a new Windows 11(German language) system, and ever since then Mylar wont start downloading. What I did to avoid an older installation of Mylar:
Download zip File from Git-Hub and extract it to C:\Mylar\
Open Git-Bash and run command: py -m pip install -r requirements.txt --> No issues
Start Mylar with .bat File: c:\Python39\python.exe Mylar.py
Enter CV-API Code, set SABNnzbd, configure Serach Provides( Dog & NZBGeeks) -->everything is green in Mylar
but Mylar wont Star searching in the first place

Here is a ?error? message I see in the command line while starting Mylar:
```
Start:
Original exception was:
Traceback (most recent call last):
  File "C:\Mylar\Mylar.py", line 496, in <module>
    main()
  File "C:\Mylar\Mylar.py", line 468, in main
    mylar.start()
  File "C:\Mylar\mylar\__init__.py", line 563, in start
    queue_schedule('search_queue', 'start')
  File "C:\Mylar\mylar\__init__.py", line 721, in queue_schedule
    start(
  File "C:\Mylar\mylar\__init__.py", line 667, in start
    logger.info('[%s] %s', name, before_msg)
TypeError: info() takes 1 positional argument but 3 were given

``` 

**CarePackage**
If I click "CarePackage" I get a new white Page with text in red:
```
Traceback (most recent call last):
  File "c:\Python39\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "c:\Python39\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "c:\Python39\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Python39\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Mylar\mylar\webserve.py", line 7294, in carepackage
    file_to_care = cp.loaders()
  File "C:\Mylar\mylar\carepackage.py", line 103, in loaders
    env_status = self.environment(vers_vals)
  File "C:\Mylar\mylar\carepackage.py", line 131, in environment
    for hiline in hi.stdout.split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'
``` 
and in the command Line:
```
Exception in thread Thread-20:
Traceback (most recent call last):
  File "c:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "c:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Python39\lib\subprocess.py", line 1479, in _readerthread
    buffer.append(fh.read())
  File "c:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 622: character maps to <undefined>
``` 

**Environment (please complete the following information):**
OS: Windows 11 64bit; German language settings
Branch: [master] [v0.7.3]

Thanks for any help

**Comment by evilhero** [comment]
The first error is a bug that was introduced in a PR that went live a little while ago - not sure how we didn't catch it, but we didn't catch it and it went into the master branch, et viola. I'll be releasing an update to both branches shortly to fix this going forward.

The last 2 are probably due to your language I'm guessing. I'm also going to guess that your config.ini has characters in it that are specific to the German language, so Mylar generally assumes English for everything. I'll take a look at the encodings aspect to see if it can get resolved, but from past problems with this type of stuff it's a very time consuming process as I don't speak German, and I have to keep flipping my windows settings to the German language, test, flip back to English, code, test, flip back to German, test, flip back, etc... but I'll try to figure things out.

**Comment by evilhero** [comment]
The queues not starting is fixed in v0.7.4 as of now
