### ISSUE TITLE
Question: How to correct Post-Process with SABnzbd

### ISSUE THREAD

**Issue by Galardin** [mylar3/mylar3#1408]
Hi,

I get an error message in SABnzbd after downloading a comic file, here is the message:
```
Loading config from C:\Mylar\post-processing\sabnzbd\autoProcessComics.cfg
Traceback (most recent call last):
File "C:\Python39\lib\configparser.py", line 789, in get
value = d[option]
File "C:\Python39\lib\collections\__init__.py", line 941, in __getitem__
return self.__missing__(key)            # support subclasses that define __missing__
File "C:\Python39\lib\collections\__init__.py", line 933, in __missing__
raise KeyError(key)
KeyError: 'apikey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Mylar\post-processing\sabnzbd\ComicRN.py", line 22, in <module>
sys.exit(autoProcessComics.processIssue(sys.argv[1], sys.argv[3], sys.argv[7], comicrn_version=comicrn_version))
File "C:\Mylar\post-processing\sabnzbd\autoProcessComics.py", line 54, in processIssue
apikey = config.get("Mylar", "apikey")
File "C:\Python39\lib\configparser.py", line 792, in get
raise NoOptionError(option, section)
configparser.NoOptionError: No option 'apikey' in section: 'Mylar'
``` 
SAB Version: 4.03
Mylar Version: 0.7.4 (master)

In SAB i have a category called "Comics" combined with a script pointing to: c:\Mylar\post-processing\sabnzbd\ComicRN.py
The "autoProcessComics.cfg" looks like this:
```
[Mylar]
host=localhost
port=8090
username=
password=
web_root=
ssl=0
``` 
In Mylar I enabled Post_Processing and "Rename-Files", and set the Comic-Lacation Path to: "y:\05_Comics\"

Sorry I cant create a Care-Package, I only get an error Page.

Not sure if that even is a Mylar Problem, but maybe someone can help.

Thank you

**Comment by evilhero** [comment]
The autoProcessComics.cfg file is missing the ``apikey``value.``username`` and ``password`` are not supported options with that as for security it only uses the apikey. The apikey is on the 2nd tab of the configuration page in Mylar, you need to enable the option and generate a key if there isn't one there already. Just copy that key into the cfg file.

The other aspect is why are you using the comicRN script? Completed Download Handling (CDH) is the method that is recommended and has the least amount of problems when setup. I'm guessing you may have tried CDH and couldn't get it to work, so opted for the ComicRN option? If that's the case, if you post the problem / error we can help get you running with CDH.
