### ISSUE TITLE
unable to manually postprocess a downloaded file

### ISSUE THREAD

**Issue by bradbulger** [mylar3/mylar3#1442]
All of my issues are getting to Snatched status and no further lately. That's a separate problem, but a result of it is that in my configured initial/temporary download folder, I have a whole bunch of .cbr and .cbz files that never made it to their final locations, plus whatever else (renaming?) that postprocessing is supposed to do.

If I enter the path of the directory containing one of these files into the "Path to Manually Run" field of the Manual Post-Processing tab form under Manage, it fails. This is what ends up in the log file:

13-Nov-2023 06:32:43 - INFO    :: mylar.post_process.1743 : CP Server Thread-4 : Starting postprocessing for : Manual Run
13-Nov-2023 06:32:43 - ERROR   :: mylar.excepthook.315 : AUTO-COMPLETE-NZB : Uncaught exception: Traceback (most recent call last):
  File "/home/hd1/mydirectory/apps/mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hd1/mydirectory/apps/mylar/mylar/helpers.py", line 3433, in nzb_monitor
    nzstat = nz.processor(item)
  File "/home/hd1/mydirectory/apps/mylar/mylar/nzbget.py", line 133, in processor
    return self.historycheck(nzbinfo)
  File "/home/hd1/mydirectory/apps/mylar/mylar/nzbget.py", line 246, in historycheck
    history_del = self.server.editqueue('HistoryMarkBad', '', hq[0]['NZBID'])
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1182, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1354, in parse_response
    return u.close()
  File "/usr/lib/python3.10/xmlrpc/client.py", line 668, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 2: 'Invalid parameter'>
 

This is on Ubuntu 22.04.1 LTS
I don't know how to tell what version I'm running. This is a managed box. The app folder is a git clone, the last commit is a merge of python3-dev on 9 May 2023, eca80ef6

I guess there was/is an issue related to trying to rerun postprocessing. Is there any thing I could do to get around that? Like maybe move all the downloaded files into a new directory and try to process that? Or is the history about the individual file names, so that wouldn't change anything?

**Comment by bradbulger** [comment]
With luck the upload worked this time. [carepackage12nov23.zip](https://github.com/mylar3/mylar3/files/13331239/carepackage12nov23.zip)

**Comment by evilhero** [comment]
There's alot going on in those logs, none of which are good. I'll try and break things down:

- several errors in the logs have been fixed in newer versions of mylar3. You need to upgrade in order to get things working again, or at least be current so that we can isolate the problems.
- you can't update mylar because your config.ini has incorrect values:
   - git_user is set to ``evilhero`` and not ``mylar3``
   - git_branch should be set to ``master``
   - check_github should be set to True
   - check_github_on_startup should be set to True 
- the error above is related to nzbget, not post-processing. Either your nzbget client is not working or its a really old version. Note that nzbget is now dead, so you could be using a really, really old version. You should be using sabnzbd probably. 
- your logs are all in INFO logging level, which does not help much when troubleshooting. Turn on verbose logging, eitherr via the ini or the GUI - you can find info on how to do that in the wiki.

**Comment by bradbulger** [comment]
Changing the mylar config let it update itself, and that resolved many of the problems. I am trying to get sabnzbd working to see if that helps with the rest.
