### ISSUE TITLE
WEB GUI dont work

### ISSUE THREAD

**Issue by mareczek82** [mylar3/mylar3#1451]
**Describe the bug**
I'm using linuxserver docker of Mylar3. 
I was using only DDL but lately i added Newsgroup to search and download. It was working very good, but today i cannot access to Mylar.  

I tryed to recreate docker but it didn't help. 

**CarePackage**
I cannot get carepackage via GUI, below im pasting logs from poitainer

───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Mylar3: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EWQADB5AMVRFU
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1088 : MainThread : [STORYARC LOCATION] Storyarc Base directory location set to: /comics/StoryArcs
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1121 : MainThread : [DOCKER-AWARE] Docker installation detected.
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1187 : MainThread : Ignored Publishers: []
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1210 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1222 : MainThread : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1234 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1248 : MainThread : [COMICTAGGER] Version detected: 1.3.5
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1327 : MainThread : Setting DDL Location set to : /config/mylar/cache
29-Nov-2023 22:31:08 - INFO :: mylar.configure.1341 : MainThread : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
29-Nov-2023 22:31:08 - INFO :: mylar.initialize.257 : MainThread : Checking to see if the database has all tables....
29-Nov-2023 22:31:08 - INFO :: mylar.dbcheck.1555 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
29-Nov-2023 22:31:08 - INFO :: mylar.dbcheck.1565 : MainThread : Correcting Null entries that make the main page break on startup.
29-Nov-2023 22:31:08 - INFO :: mylar.dbcheck.1576 : MainThread : [<class 'int'>]oldconfig_version: 12
log language set to en_US
Initializing startup sequence....
29-Nov-2023 22:31:08 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 496, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 279, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar3/mylar/__init__.py", line 264, in initialize
    cc.provider_sequence()
  File "/app/mylar3/mylar/config.py", line 1711, in provider_sequence
    self.write_out_provider_searches()
  File "/app/mylar3/mylar/config.py", line 1836, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "/app/mylar3/mylar/db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id
Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 496, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 279, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar3/mylar/__init__.py", line 264, in initialize
    cc.provider_sequence()
  File "/app/mylar3/mylar/config.py", line 1711, in provider_sequence
    self.write_out_provider_searches()
  File "/app/mylar3/mylar/config.py", line 1836, in write_out_provider_searches
    writeout = myDB.upsert("provider_searches", vals, ctrls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/db.py", line 178, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "/app/mylar3/mylar/db.py", line 130, in action
    sqlResult = self.connection.execute(query, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: provider_searches.id

**Environment (please complete the following information):**
 -Ubuntu docker
 - last version 0.76

**Additional information**
i'm not sure will it help, but in one of "manage" options i had three positions named NONE which i couldn't delete

**Comment by evilhero** [comment]
The problem occurs usually when you add dog or nzbsu as a newznab entry when you've had the stand-alone option enabled previously at some point (or you have both ways enabled - the standalone and as a newznab). Since it needs to be unique, it throws the error saying it's not.

You'll have to follow the instructions [here](https://github.com/mylar3/mylar3/wiki/Common-Errors---Problems#on-startup-i-get-an-error-about) and edit the config.ini as it shows to get past the error and then remove any problem entries you have setup in your providers within mylar.

**Comment by mareczek82** [comment]
it worked, thank you.
