### ISSUE TITLE
Mylar error 500

### ISSUE THREAD

**Issue by delaho** [mylar3/mylar3#1461]
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 369, in comicDetails
    if os.stat(os.path.join(root, direc))[stat.ST_MTIME] > filesupdated.timestamp():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/149/task/149/fd/7'

**Comment by evilhero** [comment]
Seems like a docker configuration issue, not so much of a mylar one. User running mylar cannot access w/e path you have provided, so it can't get the timestamp of the directory. 

Whether it's cause the directory doesn't exist, or doesn't have perms - I haven't a clue based on the log snippet alone.

We also have an issue template that should be used next time, as attaching the necessary information helps troubleshoot as opposed to pasting a log snippet without any context.

**Comment by delaho** [comment]
I understand youre asking me for more formal reporting, I apologize, I'm fairly new at this. I believe its permission because everything else lined up. Running in Docker though, Mylar3 instructions said to disable folder permission enforecement to let the OS handle the permissions. 
I'm connecting to an SMB. Literally everything I can tell is lined up. Docker has permission to the remote volume. The container has permission to access the volume as well with username and password all checked out and connected. From there, I'm told that Mylar3 cant read the docker compose files so the Mylar3 path needs to be set up relative to the Docker and Container directory location. In other words, if I understand correctly the IPaddress/main/comics set up in Docker and the container the / after /comics/ would be the "root folder" for Mylar3. I therefore have Mylar3 location to save comics to /.
Its a Linux SMB share, if that helps.

**Comment by evilhero** [comment]
That is incorrect. Mylar itself cannot read your compose file, or what it contains, the docker application is wait maps the mount points.

You need to map the full mount points as they appear in your compose. So /comics, /config or w/e else you have is what you should be putting in mylar - not just / as that is not how applications work with regards to docker locations.

Easist would be to paste you compose file in here, and then we can tell you how it should be to get things working proeprly.

**Comment by delaho** [comment]
I wrote "I'm told that Mylar3 _cant_ read the docker compose files" just to clarify. I believe we are on the same page there.
From here, can you assist where to retrieve that compose file? I didnt directly edit it because I used the GUI to set this all up so I assume the GUI edited the compose file on my behalf. I'm not sure where to find it.

**Comment by evilhero** [comment]
Well you setup docker - so wherever you set it up is generally where the compose files are located. Most people tend to install stuff into the /opt directory for Linux. 

Everyone has a different setup for docker, and I have zero idea of how you installed docker, what the GUI is that you're taking about or what your OS is even.

So while I would help, I have zero idea of what your setup is and I'm also probably the least docker-savvy person to help troubleshoot anything outside of basic docker stuff.

You may want to hop onto our discord where there are lots of docker users that can probably assist you better.

**Comment by delaho** [comment]
MacOS, the SMB remote share is Linux. I didnt install via command line. 
The GUI?
![Screenshot 2023-12-10 at 4 26 20 PM](https://github.com/mylar3/mylar3/assets/153228612/e49a29e5-7981-4a09-88f6-9151dfeb0aec)

**Comment by delaho** [comment]
Maybe I should rephrase something, I think I'm closer to solution here: 
within docker I have created an SMB volume mount/share, when adding that SMB share to the container (Mylar3). I need to place the external SMB share to some "path/in/container". What would be the advisable path for Mylar3 to place that path/to/container?

**Comment by delaho** [comment]
@evilhero I figured out the issue, I think:
PermissionError: [Errno 1] Operation not permitted: '/comics/Atom The Cat (1944)/._Atom the Cat 001 (1944).cbz'
Essentially, Mac file transfer to an SMB share adds "._" filesin the transfer and Mylar3 and/or Python is tripping on hidden files. I would like to note that other softwares such as sonarr, radarr, Kapowarr (very alpha piece of software) and others do not get tripped on this as an error.
This error shows up when I click the Atom the Cat comic within Mylar to see the title page and issues. Instead of displaying those details on page http://0.0.0.0:8090/comicDetails?ComicID=123456 I get the operation error. 
This could be a Python thing but again, other apps, other Python apps, dont seem to trip on these .hidden files. Can Mylar be updated to avoid this?
My comics are otherwise now downloading and post processing to the NAS as expected, I got the location part figured out in linking the container to the SMB share and the path/in/container solved as well.

**Comment by evilhero** [comment]
It's an OS error that's being passed back from your OS when mylar is attempting to do some kind of operation on the file - it's not mylar itself. The *arr apps aren't written in Python, different languages. 

You need to fix your permissions and then it won't happen.

**Comment by delaho** [comment]
[carepackage_v0.7.6.zip](https://github.com/mylar3/mylar3/files/13651303/carepackage_v0.7.6.zip)

Carepackage attached

**Comment by DieselTech** [comment]
Seeing some odd things in your logs for supposedly running in docker. 

> mylar.setperms.1933 : CP Server Thread-6 : [ERROR @ path: /] [Errno 1] Operation not permitted: '/opt'. Exiting...

Also you have enforce permissions set. That generally should not be turned on if your using docker. And especially not if your using SMB shares as your comic path. You can't enforce permissions across a network share.

**Comment by delaho** [comment]
The permissions I changed were a result of seeing the 500 error failure because I thought enhanced permissions might be needed. But when the permissions were stock, I still had the issue with ._ files and Mylar/Python not knowing what to do with them. ._ are an artifact of Mac connection to the network share. Theyre just an inevitability. Deleting them, they just come back. If Mylar could ignore .files that error would probably cease as Mylar appears to be trying to figure out what to do with .files.
I'll set stock permissions back when I get around to it, but like I said, Mylar doesnt like .files apparently. And since this is a Mac running Docker and all connected to a network share this isnt likely an isolated problem. Most other users must be manually copying to their network share after processing, if they have a network share. But fixing this would give a fix to a likely broad amount of people.

**Comment by evilhero** [comment]
It's a MAC OS problem with the metadata. Odds are that the files are owned by root so mylar can't access them, but if they are 0 byte files it would ignore them regardless.

I'll have a fix up later tonight to skip the ``. _`` files, but it will be in python3-dev not master so you'll still encounter the error unless you switch to python3-dev (nightly on lsio docker), or wait for us to merge up, which probably isn't going to happen until after the holidays.

**Comment by delaho** [comment]
That would be wonderful and I can wait. Comics come out once a month, y'know? Thank you for your patience. I'll throw a donation soon. Thank you!
