### ISSUE TITLE
Error viewing Superman/Wonder Woman (2013)

### ISSUE THREAD

**Issue by Frankthetankk** [mylar3/mylar3#1463]
**Describe the bug**
Get this error when trying to view [Superman/Wonder Woman (2013)](https://comicvine.gamespot.com/supermanwonder-woman/4050-68150/) in mylar. Am able to search for and add this volume, but get error when trying to view it on Mylar.

**CarePackage**
[carepackage_v0.7.6.zip](https://github.com/mylar3/mylar3/files/13760607/carepackage_v0.7.6.zip)
database file too large

**Environment (please complete the following information):**
 - OS: [Windows10]
 - Branch / commit: [Master/66f8914](https://github.com/mylar3/mylar3/commit/66f891411eb24c8d5b3aa32e2f26619e2b65b993)]

**Additional information**
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

```
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 429, in comicDetails
    comicImage = "data:image/webp;base64,%s" % mylar.getimage.load_image(coverimage, 263)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/getimage.py", line 217, in load_image
    img = Image.open( BytesIO( imagefile) )
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/PIL/Image.py", line 3284, in open
    im = _open_core(fp, filename, prefix, formats)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/PIL/Image.py", line 3270, in _open_core
    im = factory(fp, filename)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 833, in jpeg_factory
    im = JpegImageFile(fp, filename)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/lsiopy/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 390, in _open
    handler(self, i)
  File "/lsiopy/lib/python3.11/site-packages/PIL/JpegImagePlugin.py", line 66, in APP
    s = ImageFile._safe_read(self.fp, n)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/PIL/ImageFile.py", line 571, in _safe_read
    raise OSError(msg)
```
OSError: Truncated File Read

Under 'Manage Comics' it looks like this.
![image](https://github.com/mylar3/mylar3/assets/5327747/dcb3cbe5-582f-4538-a94f-f284802c219d)

**Comment by evilhero** [comment]
It's a problem with the image on CV for that particular series - or was at one point. I'd have to look it into again as it was fixed at one point, but maybe the Alternate image got corrupted or something. It's definitely a problem with that series tho.

**Comment by Frankthetankk** [comment]
> It's a problem with the image on CV for that particular series - or was at one point. I'd have to look it into again as it was fixed at one point, but maybe the Alternate image got corrupted or something. It's definitely a problem with that series tho.

Okay just wanted to let you know. I'm not sure how to fix it myself on comicvine. When I try to upload a new cover image I don't get the option to submit the changes.
