### ISSUE TITLE
Error as soon Mylar snatches an Issue

### ISSUE THREAD

**Issue by Galardin** [mylar3/mylar3#1469]
**Describe the bug**
As soon as Mylar snatches an Comic issue, an error in the cmd window of Windows 11 appears:

> Exception in thread AUTO-COMPLETE-NZB:
> Traceback (most recent call last):
>   File "c:\Mylar\mylar\sabnzbd.py", line 98, in processor
>     if queueresponse['noofslots'] == 1: # 1 means it matched to one instance
> KeyError: 'noofslots'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\Python39\lib\threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "c:\Python39\lib\threading.py", line 892, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\Mylar\mylar\helpers.py", line 3434, in nzb_monitor
>     nzstat = nz.processor()
>   File "c:\Mylar\mylar\sabnzbd.py", line 102, in processor
>     logger.warning('unable to locate item within sabnzbd active queue - it could be finished already?')
> AttributeError: module 'mylar.logger' has no attribute 'warning'
> Exception in thread Thread-20:
> Traceback (most recent call last):
>   File "c:\Python39\lib\threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "c:\Python39\lib\threading.py", line 892, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\Python39\lib\subprocess.py", line 1479, in _readerthread
>     buffer.append(fh.read())
>   File "c:\Python39\lib\encodings\cp1252.py", line 23, in decode
>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 622: character maps to undefined

Mylar snathes the issue sends it to SAB and the issue will be downloaded, but wont be Post Proceesed. This happens since the new Master release of mylar, proir it worked fine.

**CarePackage**
If I click the Buton a new Page opens with red text in it:

> 500 Internal Server Error
> The server encountered an unexpected condition which prevented it from fulfilling the request.
> 
> Traceback (most recent call last):
>   File "c:\Python39\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
>     self._do_respond(path_info)
>   File "c:\Python39\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
>     response.body = self.handler()
>   File "c:\Python39\lib\site-packages\cherrypy\lib\encoding.py", line 223, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "c:\Python39\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
>     return self.callable(*self.args, **self.kwargs)
>   File "c:\Mylar\mylar\webserve.py", line 7320, in carepackage
>     file_to_care = cp.loaders()
>   File "c:\Mylar\mylar\carepackage.py", line 103, in loaders
>     env_status = self.environment(vers_vals)
>   File "c:\Mylar\mylar\carepackage.py", line 131, in environment
>     for hiline in hi.stdout.split('\n'):
> AttributeError: 'NoneType' object has no attribute 'split'

**Environment (please complete the following information):**
 - OS: Windows 11 (German lang,)
 - Chrome 
 - SABNZBD
 - Mylar Version: v0.7.7 (master)

Thank you for any help

**Comment by evilhero** [comment]
What version of SABnzbd are you running ? 

It might be that you're using an outdated version of SABnzbd - that or we need to account for some differing versions where that api value is present.

**Comment by Galardin** [comment]
I updated SAB to 4.2.1, I was using 4.1 before and had the same Error

**Comment by evilhero** [comment]
looks like it's just an incorrect logging reference - not actually a problem with how it's handling SAB itself. 

I'm assuming your downloads are going really fast so it barely has time to register within SAB, and when it goes to check the queue it's already finished and throws that warning.

I will patch it momentarily in python3-dev, but it will be abit before it hits the master branch as we don't push directly to the master branch itself.

You can always switch to the python3-dev branch until such time as it merges up.
