### ISSUE TITLE
Manual search not searching, just queues

### ISSUE THREAD

**Issue by 1-dannyg** [mylar3/mylar3#1471]
**Describe the bug**
Whenever I do a manual search, Mylar just queues it for searching, but never searches.

**CarePackage**
[carepackage_v0.7.7.zip](https://github.com/mylar3/mylar3/files/13851482/carepackage_v0.7.7.zip)

**Environment (please complete the following information):**
 - OS: FreeBSD 13.2
 - Branch / commit: master / f9bd3ba366e2fe200fdc77fabf4a21df85fea006

**Additional information**
Been using Mylar for many years, but it stopped searching. Did a clean install. Only did basic settings, but it still doesn't do a manual search. Attached is a screenshot of the Activity/Jobs tab in the Manage page. It shows there is an entry in the Search Queue, but none of the workers seem to be running and none of the schedulers are there.
![manage-activity-job](https://github.com/mylar3/mylar3/assets/155851739/239db5eb-aad3-4dee-90d8-e4c01df83d96)

I do get the following in the logs when I start Mylar:

> Uncaught exception: Traceback (most recent call last):
> File "/tmp/mylar/Mylar.py", line 496, in
> main()
> File "/tmp/mylar/Mylar.py", line 462, in main
> r.loaders()
> File "/tmp/mylar/mylar/req_test.py", line 52, in loaders
> self.check_the_pip()
> File "/tmp/mylar/mylar/req_test.py", line 148, in check_the_pip
> pip_message = "%s installed %s %s required" % (x['pip_version'], targ, x['req_version'])
> UnboundLocalError: local variable 'targ' referenced before assignment

Let me know if there's anything more you need or if I missed anything (first time ever posting, so not sure I've done everything correctly).

Thanks.

**Comment by evilhero** [comment]
Looking at the carepackage it looks like the error that happens on startup, kills the scheduler from actually starting any of the scheduled job, so nothing runs.

Looking into this now...

**Comment by 1-dannyg** [comment]
I used pip to install cheroot v8.2.1 (instead of FreeBSD's packages where I got v10.0.0) and it looks to be working now,

![manage-activity-job](https://github.com/mylar3/mylar3/assets/155851739/61c820e2-82f7-4cc4-803a-b78b4106ac87)

I was able to download a comic using DDL (will need to test NZB method, but assume it should be fine). Thanks for the help.

Any chance you might upgrade to the newer version? I'd like to keep to using FreeBSD's method of installing things.

Sorry, I don't program with python, so won't be able to properly help with the code side of things.

Thanks.

**Comment by DieselTech** [comment]
If you need different versions of python packages you should setup virtual environments to satisfy multiple versions 

https://docs.python.org/3/library/venv.html

**Comment by 1-dannyg** [comment]
> If you need different versions of python packages you should setup virtual environments to satisfy multiple versions
> 
> https://docs.python.org/3/library/venv.html
Thanks for that.

I'm not a direct python user. Just have it due to certain applications needing it. The FBSD pkg/ports system will install these packages if the app requires it. Again, I also try to avoid using pip so there's no collisions with FBSD's pkg/ports system. It's simpler package management. This is the first time where I've run into a python module version problem with an app.

**Comment by Nebelherr23** [comment]
> so there's no collisions with FBSD's pkg/ports system 

This is exactly the reason why venv is recommended. It maintains a desperate set of packages for that specific venv, so a software installed from source doesn't clash with system packages. It doesn't add much of an overhead in terms of managing things.
