### ISSUE TITLE
The update to the pull list generates an internal 500 error

### ISSUE THREAD

**Issue by jcleitao** [mylar3/mylar3#1475]
Technical specs: Running on a docker-container (provided by linuxservers.io) it is a long running instance, with a collection of several thousands of different titles. Linux server running debian 12.

Issue: It is impossible to see the weekly pull list, when I try to access that page I get the following 500 error:

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
                    ^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/lib/encoding.py", line 223, in __call__
    self.body = self.oldhandler(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2766, in pullist
    repoll = self.pullrecreate(weeknumber=weekinfo['weeknumber'],year=weekinfo['year'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/webserve.py", line 2989, in pullrecreate
    statchk = weeklypull.pullit(forcecheck, weeknumber, year)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/weeklypull.py", line 115, in pullit
    new_pullcheck(chk_locg['weeknumber'],chk_locg['year'])
  File "/app/mylar3/mylar/weeklypull.py", line 934, in new_pullcheck
    if 'Present' in watch['ComicPublished'] or (helpers.now()[:4] in watch['ComicPublished']) or watch['ForceContinuing'] == 1 or len(listit) >0:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
Powered by [CherryPy 18.9.0](http://www.cherrypy.dev/)

The log of mylar reports this (no concrete error):

mylar3            | 15-Jan-2024 20:40:04 - INFO :: mylar.pullist.2765 : CP Server Thread-8 : trying to repopulate to week: 02-2024
mylar3            | 15-Jan-2024 20:40:04 - INFO :: mylar.pullrecreate.2988 : CP Server Thread-8 : [PULL-LIST] Now Recreating the Pull-list for week 02, 2024...
mylar3            | 15-Jan-2024 20:40:04 - INFO :: mylar.pullit.72 : CP Server Thread-8 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website
mylar3            | 15-Jan-2024 20:40:04 - INFO :: mylar.pullit.106 : CP Server Thread-8 : [PULL-LIST] Populating & Loading pull-list data directly from alternate website for specific week of 1, 2024
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.locg.78 : CP Server Thread-8 : [WEEKLY-PULL] There are 88 issues for week 1, 2024
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.locg.109 : CP Server Thread-8 : Re-creating pullist to ensure everything's fresh.
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.locg.144 : CP Server Thread-8 : [PULL-LIST] Successfully populated pull-list into Mylar for week 1 of 2024
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.pullit.114 : CP Server Thread-8 : [PULL-LIST] Weekly Pull List successfully loaded with 88 issues.
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'ワンピース'}, {'AlternateName': 'Wan Piisu'}], 'ComicID': '21397', 'Count': 2}
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'Betty and Veronica Jumbo Comics Digest'}, {'AlternateName': 'Betty and Veronica Comics Annual'}, {'AlternateName': 'Betty and Veronica Jumbo Comics'}, {'AlternateName': 'Betty and Veronica Comics Double Digest'}], 'ComicID': '28073', 'Count': 4}
mylar3            | 15-Jan-2024 20:40:05 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'World of Archie Jumbo Comics Digest'}, {'AlternateName': 'World of Archie Comics Digest'}, {'AlternateName': 'World of Archie Comics Double Digest'}], 'ComicID': '36743', 'Count': 3}
mylar3            | 15-Jan-2024 20:40:06 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'チェンソーマン'}, {'AlternateName': 'Chainsawman'}], 'ComicID': '117318', 'Count': 2}
mylar3            | 15-Jan-2024 20:40:06 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'Nightmare Country - The Glass House'}], 'ComicID': '149389', 'Count': 1}
mylar3            | 15-Jan-2024 20:40:06 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'バットマン ジャスティスバスター'}], 'ComicID': '139351', 'Count': 1}
mylar3            | 15-Jan-2024 20:40:06 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': 'The Bone Orchard Mythos: Tenement'}], 'ComicID': '151620', 'Count': 1}
mylar3            | 15-Jan-2024 20:40:06 - INFO :: mylar.LoadAlternateSearchNames.1425 : CP Server Thread-8 : AlternateNames returned:{'AlternateName': [{'AlternateName': '週刊ヤングジャンプ'}, {'AlternateName': 'ヤングジャンプ'}], 'ComicID': '88805', 'Count': 2}

**Comment by evilhero** [comment]
One of the series on your watchlist, either never finished updating/refreshing, and/or it encountered an error during such activity that it could not finish.

Go the main watchlist page, and sort by published or status to see if any are showing as loading or incomplete. Once you found them, Refesh the series manually and once they're updated correctly you'll be able to access the pullist.

**Comment by xalgorithm** [comment]
I am receiving the same error. What is meant by main watchlist? Is that the Wanted button?

**Comment by evilhero** [comment]
@xalgorithm the main watchlist is the page that mylar loads initially on startup - or whenever you click on the upper left mylar logo. That shows all the series that mylar is watching / monitoring.

**Comment by VulturineHook** [comment]
So I just tried this, refreshing the 3 series that I had 'loading', and I have nothing currently blue or white in my watchlist, and I am getting this error as well. Any ideas?
