### ISSUE TITLE
Switching to Python 3 version causing startup fault

### ISSUE THREAD

**Issue by ErenPhayte** [mylar3/mylar3#148]
Traceback (most recent call last):                                                                                        File "Mylar.py", line 26, in <module>                                                                                     import mylar                                                                                                          File "c:\mylar\mylar\__init__.py", line 33, in <module>                                                                   from apscheduler.schedulers.background import BackgroundScheduler                                                   ImportError: bad magic number in 'apscheduler': b'\x03\xf3\r\n'

**Comment by DrSeussFreak** [comment]
Straight from the readme under requirements

> Python version 3.8+ of Mylar will not work on Windows due to some dependency issues

**Comment by ErenPhayte** [comment]
it does work on Windows. Just needed to clear cached files.

**Comment by AtariBaby** [comment]
I tried clearing cache and that only got slightly further. Uninstalling 3.8 and installing 3.7 then allowed for successful full installation of requirements.txt
