### ISSUE TITLE
Docker unusable due to startup error

### ISSUE THREAD

**Issue by 00Aperture00** [mylar3/mylar3#1502]
**Describe the bug**
As soon as mylar (as docker in unraid) starts up, the error appears and the gui is unreachable. The error repeats indefinitely until docker shutdown.

**CarePackage**
No CarePackage producable, as the gui unreachable.
Contents from mylar.log:
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1122 : MainThread : [DOCKER-AWARE] Docker installation detected.
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1188 : MainThread : Ignored Publishers: []
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1211 : MainThread : [MASS_PUBLISHERS] Auto-add for weekly publishers set to: []
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1223 : MainThread : [IGNORE_SEARCH_WORDS] Words to flag search result as invalid: ['.exe', '.iso', 'pdf-xpost', 'pdf', 'ebook']
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1235 : MainThread : [PROBLEM_DATES] Problem dates loaded: ['2021-07-14 04:00:34']
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1249 : MainThread : [COMICTAGGER] Version detected: 1.3.5
28-Jan-2024 14:37:11 - INFO    :: mylar.configure.1342 : MainThread : [Search Tier Cutoff] Setting Tier-1 cutoff point to 14 days
28-Jan-2024 14:37:11 - ERROR   :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 496, in <module>
    main()
  File "/app/mylar3/Mylar.py", line 279, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/app/mylar3/mylar/__init__.py", line 251, in initialize
    CONFIG = cc.read(startup=True)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/config.py", line 660, in read
    self.configure(startup=startup)
  File "/app/mylar3/mylar/config.py", line 1380, in configure
    if int(re.sub("[^0-9]", '', self.SAB_VERSION).strip()) < int(re.sub("[^0-9]", '', '0.8.0').strip()) and self.SAB_CLIENT_POST_PROCESSING is True:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Environment (please complete the following information):**
 - OS: Unraid 6.12.6
 - Branch / commit: latest, 0.7.8

**Comment by evilhero** [comment]
What version of SAB are your running?

I think if you can edit your config.ini and just blank out the ``sab_version`` value (``sab_version = ``) it should allow it to startup.
