### ISSUE TITLE
TypeError: RotatingLogger.handle_exception() missing 1 required positional argument: 'exc_traceback'

### ISSUE THREAD

**Issue by bulletproof2k** [mylar3/mylar3#1533]
Version: v0.8.0, v0,8.0 (master)
```
Exception in thread Thread-18 (_readerthread):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2865: character maps to <undefined>
Error in sys.excepthook:
TypeError: RotatingLogger.handle_exception() missing 1 required positional argument: 'exc_traceback'

Original exception was:
Traceback (most recent call last):
  File "E:\DEV\Py\mylar3\mylar.py", line 595, in <module>
    main()
  File "E:\DEV\Py\mylar3\mylar.py", line 561, in main
    r.loaders()
  File "E:\DEV\Py\mylar3\mylar\req_test.py", line 53, in loaders
    self.find_the_unrar()
  File "E:\DEV\Py\mylar3\mylar\req_test.py", line 228, in find_the_unrar
    if "not found" in output.stdout or "not recognized as an internal or external command" in output.stdout:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
But Milar is working 🤷🏻‍♂️

**Comment by bulletproof2k** [comment]
@evilhero Will there be any response on my issue?

**Comment by evilhero** [comment]
It's only been 2 days lol - not everything is an instant fix... You also don't need to tag me on everything, I get notified on any updates to any issue regardless.

All that being said, I'm going to say that your system isn't set to use utf-8 by default and it's unable to write to the logs properly. By default, Windows uses cp-1252 encoding. 

You can change it to utf-8 in the Region & Language settings of windows10,  however you need to be aware that it may change usage of some of your other programs as you're changing the system encoding. In which case you'd have to change it back.
