### ISSUE TITLE
CRC Error Behaviour - Reject Comics

### ISSUE THREAD

**Issue by falo2k** [mylar3/mylar3#1541]
**Describe the request**
Can we get an option to reject comics when CT catches a CRC error?  It inevitably means a bad book and I have to either catch it in another application like Komga or when reading.  Would be much better if it just failed the issue so I could see it still sitting in my wanted queue as snatched and look into the problem.

**Environment (please complete the following information):**
 - OS: Docker/Unraid (LSIO)
 - Branch / commit: 9e2833974905d6ec18895fb640e2299eea5f7ec0

> 08-Apr-2024 00:11:48 - INFO    :: mylar.Process.757 : Thread-407 (Process) : Now checking: DCU: Legacies [33175]
> 08-Apr-2024 00:11:48 - INFO    :: mylar.duplicate_filecheck.2231 : Thread-407 (Process) : [DUPECHECK] Duplicate check for /media/downloads/usenet/comics/DC.Universe.-.Legacies.006.2010.Digital.Shadowcat-Empire/DC Universe - Legacies 006 (2010) (Digital) (Shadowcat-Empire).cbz
> 08-Apr-2024 00:11:48 - INFO    :: mylar.duplicate_filecheck.2389 : Thread-407 (Process) : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
> 08-Apr-2024 00:11:48 - INFO    :: mylar.Process_next.2752 : Thread-407 (Process) : [POST-PROCESSING]  [1/1] Starting Post-Processing for DCU: Legacies issue: 6
> 08-Apr-2024 00:11:48 - INFO    :: mylar.run.147 : Thread-407 (Process) : ct_check: b'ComicTagger 1.3.5 [ninjas.walk.alone / SHURIKEN]\nCopyright (c) 2012-2024 ComicTagger Team\nDistributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)\n'
> 08-Apr-2024 00:11:49 - WARNING :: mylar.run.285 : Thread-407 (Process) : [META-TAGGER][COMIC-TAGGER] file is not in a RAR format: DC Universe - Legacies 006 (2010) (Digital) (Shadowcat-Empire).cbz
> 08-Apr-2024 00:11:49 - INFO    :: mylar.run.223 : Thread-407 (Process) : [META-TAGGER] ComicRack tagging meta-tagging processing started.
> 08-Apr-2024 00:11:50 - WARNING :: mylar.run.314 : Thread-407 (Process) : [META-TAGGER][COMIC-TAGGER][UNKNOWN-ERROR-DURING-METATAGGING] bad zipfile [Bad CRC-32 for file 'DC Universe - Legacies 006 (2010) (Digital) (Shadowcat-Empire)/DC Universe - Legacies 006-031.jpg']: /config/mylar/cache/mylar_rakx8k4k/DC Universe - Legacies 006 (2010) (Digital) (Shadowcat-Empire).cbz :: DC Universe - Legacies 006 (2010) (Digital) (Shadowcat-Empire)/DC Universe - Legacies 006-031.jpg
> Error reading in page.  Substituting logo page.
> Traceback (most recent call last):
>   File "/app/mylar3/comictagger.py", line 4, in <module>
>     ctmain()
>   File "/app/mylar3/lib/comictaggerlib/main.py", line 63, in ctmain
>     cli.cli_mode(opts, SETTINGS)
>   File "/app/mylar3/lib/comictaggerlib/cli.py", line 193, in cli_mode
>     process_file_cli(f, opts, settings, match_results)
>   File "/app/mylar3/lib/comictaggerlib/cli.py", line 483, in process_file_cli
>     if not actual_metadata_save(ca, opts, md):
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/mylar3/lib/comictaggerlib/cli.py", line 85, in actual_metadata_save
>     if not ca.writeMetadata(md, opts.data_style):
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/mylar3/lib/comictaggerlib/comicapi/comicarchive.py", line 680, in writeMetadata
>     retcode = self.writeCIX(metadata)
>               ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/app/mylar3/lib/comictaggerlib/comicapi/comicarchive.py", line 909, in writeCIX
>     self.applyArchiveInfoToMetadata(metadata, calc_page_sizes=True)
>   File "/app/mylar3/lib/comictaggerlib/comicapi/comicarchive.py", line 1064, in applyArchiveInfoToMetadata
>     p['ImageSize'] = str(len(data))
>                          ^^^^^^^^^
> TypeError: object of type 'NoneType' has no len()
> 
> 08-Apr-2024 00:11:50 - INFO    :: mylar.validateAndCreateDirectory.1895 : Thread-407 (Process) : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /media/comics/comics/DCU Legacies (2010)
> 08-Apr-2024 00:11:50 - INFO    :: mylar.Process_next.3277 : Thread-407 (Process) : [POST-PROCESSING] move successful to : /media/comics/comics/DCU Legacies (2010)/DCU Legacies 006 (2010).cbz
> 08-Apr-2024 00:11:50 - INFO    :: mylar.foundsearch.1056 : Thread-407 (Process) : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
> 08-Apr-2024 00:11:50 - INFO    :: mylar.foundsearch.1113 : Thread-407 (Process) : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now completed for DCU: Legacies issue: 6
> 08-Apr-2024 00:11:50 - INFO    :: mylar.Process_next.3463 : Thread-407 (Process) : [POST-PROCESSING] Post-Processing completed for: DCU: Legacies #6
> 08-Apr-2024 00:11:50 - INFO    :: mylar.Process.2277 : Thread-407 (Process) : [POST-PROCESSING] post-processing of pack completed for 1 issues [FAILED: 1]

**Comment by falo2k** [comment]
Tacking another log excerpt onto this as it's in the same ballpark.  Another bad archive (abnormal end of archive) but apparently does not throw the same exception.

`07-Mar-2025 16:55:47 - INFO    :: mylar.duplicate_filecheck.2237 : Thread-27 (Process) : [DUPECHECK] Duplicate check for /media/downloads/usenet/comics/Spider-Boy.017.2025.3.covers.Digital.dekabro-Empire/Spider-Boy 017 (2025) (3 covers) (Digital) (dekabro-Empire).cbz
07-Mar-2025 16:55:47 - INFO    :: mylar.duplicate_filecheck.2395 : Thread-27 (Process) : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
07-Mar-2025 16:55:47 - INFO    :: mylar.Process_next.2752 : Thread-27 (Process) : [POST-PROCESSING]  [1/1] Starting Post-Processing for Spider-Boy issue: 17
07-Mar-2025 16:55:48 - INFO    :: mylar.run.147 : Thread-27 (Process) : ct_check: b'ComicTagger 1.3.5 [ninjas.walk.alone / SHURIKEN]\nCopyright (c) 2012-2025 ComicTagger Team\nDistributed under Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)\n'
07-Mar-2025 16:55:48 - WARNING :: mylar.run.297 : Thread-27 (Process) : [META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ]Failed to convert cbr to cbz - check permissions on folder /config/mylar/cache and/or the location where Mylar is trying to tag the files from.
07-Mar-2025 16:55:48 - INFO    :: mylar.validateAndCreateDirectory.1895 : Thread-27 (Process) : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /media/comics/comics/Spider-Boy (2024)
07-Mar-2025 16:55:48 - INFO    :: mylar.Process_next.3280 : Thread-27 (Process) : [POST-PROCESSING] move successful to : /media/comics/comics/Spider-Boy (2024)/Spider-Boy V2024 017 (May 2025).cbz
07-Mar-2025 16:55:48 - INFO    :: mylar.forceRescan.1154 : Thread-27 (Process) : [FILE-RESCAN] Now checking files for Spider-Boy (2024) in /media/comics/comics/Spider-Boy (2024)
07-Mar-2025 16:55:48 - INFO    :: mylar.traverse_directories.1677 : Thread-27 (Process) : there are 17 files.`

I've stashed a copy of this failed issue so I can reproduce if needed.

**Comment by falo2k** [comment]
CRC checks merged into dev.
