### ISSUE TITLE
Error importing comics

### ISSUE THREAD

**Issue by acordmike** [mylar3/mylar3#1555]
Comics cannot be imported. There is a sqlite3 error in the log when I attempt.

**Environment**
- OS Unraid, linux/docker
- Version 0.8.0

Error from log: 
2024-07-19 12:10:11	ERROR	Uncaught exception: Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/webserve.py", line 6228, in preSearchit
results = myDB.select("SELECT * FROM importresults WHERE DynamicName=? AND Volume=? AND Status='Not Imported'", [DynamicName,volume])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/db.py", line 148, in select
sqlResults = self.fetch(query, args).fetchall()
^^^^^^^^^^^^^^^^^^^^^^^
File "/app/mylar3/mylar/db.py", line 93, in fetch
sqlResult = cursor.execute(query, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.ProgrammingError: Error binding parameter 1: type 'list' is not supported
2024-07-19 12:10:11	ERROR	Fatal error executing query: Error binding parameter 1: type 'list' is not supported
2024-07-19 12:10:11	INFO	[IMPORT][*******)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2024-07-19 12:10:11	INFO	[IMPORT][result (s)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2024-07-19 12:10:11	INFO	[IMPORT][impresults_table_lengt (h)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
2024-07-19 12:10:11	INFO	Initiating selected import mode for 26 series.
2024-07-19 12:10:11	INFO	importing selected series.
2024-07-19 12:06:37	INFO	Successfully scanned in directory. Enabling the importResults button now.

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
Log pasting doesn't provide enough information to decipher what's happening, especially when it's not with debug logging. 

Attach a carepackage to the issue and we can look more into it, but without context this is next to impossible to track down the root cause  based on the log snippet alone.

**Comment by acordmike** [comment]
I enabled debug logging, re-tried the import and created the care package.
[carepackage_v0.8.0.zip](https://github.com/user-attachments/files/16316772/carepackage_v0.8.0.zip)
