### ISSUE TITLE
Loading comic information throws error

### ISSUE THREAD

**Issue by danielstorch** [mylar3/mylar3#1557]
Loading information after adding a comic via the ComicVineID throws an error...?

```
24-Jul-2024 22:27:36 - INFO    :: mylar.searchit.1144 : CP Server Thread-7 : Attempting to add directly by ComicVineID: 34860. I sure hope you know what you are doing.
24-Jul-2024 22:27:36 - INFO    :: mylar.addbyid.1390 : CP Server Thread-7 : com_location: None
24-Jul-2024 22:27:36 - INFO    :: mylar.addbyid.1454 : CP Server Thread-7 : Attempting to add directly by ComicVineID: 34860
24-Jul-2024 22:27:36 - INFO    :: mylar.addbyid.1486 : CP Server Thread-7 : [SHIZZLE-WHIZZLE] Now queueing to add 34860
24-Jul-2024 22:27:36 - INFO    :: mylar.importer_thread.1978 : CP Server Thread-7 : [MASS-ADD] MASS_ADD thread not started. Started & submitting.
24-Jul-2024 22:27:36 - INFO    :: mylar.scale_image.76 : CP Server Thread-10 : converted to webp...
24-Jul-2024 22:27:39 - INFO    :: mylar.addvialist.66 : mass-add : [MASS-ADD][1/1] Now adding ComicID: 34860 
24-Jul-2024 22:27:43 - ERROR   :: mylar.excepthook.315 : mass-add : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/importer.py", line 69, in addvialist
    addComictoDB(item['comicid'])
  File "/app/mylar3/mylar/importer.py", line 148, in addComictoDB
    comic = cv.getComic(comicid, 'comic', series=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/cv.py", line 167, in getComic
    return GetComicInfo(comicid, dom, series=series)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/mylar3/mylar/cv.py", line 357, in GetComicInfo
    comic['FirstIssueID'] = dom.getElementsByTagName('id')[0].firstChild.wholeText
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by evilhero** [comment]
It's throwing an unhandled error as it's having a problem retrieving data from CV. This could be due to CV limiting you because of going over their hourly api limit, or hammering their site too quickly. 

It may also be due to having an invalid CV api key, or the client being unable to reach CV for whatever reason (networking, routing, etc).

This is on a case-by-case basis, so there's not one always right answer which is why I provided various possibilities.

**Comment by danielstorch** [comment]
hmm, any idea how i could debug this? It cant be the api limit, i just set up docker and that was my first attempt adding a comic. And it should be a valid key.

**Comment by danielstorch** [comment]
Ok, found the issue after checking the code and testing the api directly. When copying the API key from comicvine, there is a whitespace at the end...
