### ISSUE TITLE
DDL queue crash - "links_exhausted" and "'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by francispeixoto** [mylar3/mylar3#1569]
**Describe the bug**
The DDL queue will go down systematically after downloading two or three issues and can only be recovered by restarting mylar and restarting the last download once mylar comes back up.

**DEBUG error that appears at each DDL queue crash**

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar3/mylar/helpers.py", line 3419, in ddl_downloader
ltf = ddzstat['links_exhausted']
~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'links_exhausted'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/mylar3/mylar/logger.py", line 337, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python3.11/threading.py", line 982, in run
self._target(*self._args, **self._kwargs)
File "/app/mylar3/mylar/helpers.py", line 3428, in ddl_downloader
ggc.parse_downloadresults(item['id'], item['mainlink'], item['comicinfo'], item['packinfo'], link_type_failure[item['id']])
File "/app/mylar3/mylar/getcomics.py", line 1065, in parse_downloadresults
self.issueid = comicinfo[0]['IssueID']
~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Environment (please complete the following information):**
 - OS: Docker/lsio
 - Branch / commit: master

**Additional information**
Add any other information about the problem here.

**Comment by eldridgeh** [comment]
I had the same error. Had to to do similar steps and restart. After a restart, one would process just fine and then the next would be stuck at 100% and get the error until I restarted Mylar and then restarted the download.

This happened multiple times.

What seemed to finally fix everything for me was setting the snatched comics back to wanted, restart Mylar, and then checking for missing for the week. Everything seems to be processing fine since doing this.

**Comment by francispeixoto** [comment]
> I had the same error. Had to to do similar steps and restart. After a restart, one would process just fine and then the next would be stuck at 100% and get the error until I restarted Mylar and then restarted the download.
> 
> This happened multiple times.
> 
> What seemed to finally fix everything for me was setting the snatched comics back to wanted, restart Mylar, and then checking for missing for the week. Everything seems to be processing fine since doing this.

yep that seems to have done it. I'll keep an eye on it, because I have a feeling in the back of my neck it has something to do with the large amount of snatches (288) I had in the DDL queue.

**Comment by francispeixoto** [comment]
Called it. The DLL queue crashed again as soon as mylar added 30 snatched 30 issues into it.

**Comment by Wraithers** [comment]
Thanks @eldridgeh 🙌 I've been breaking my head trying to get around this error 🙈

I expect I'll run into the same issue as you, @francispeixoto, so I'm manually limiting my queue size until I catch up. Here's hoping that works 🤞

**Comment by francispeixoto** [comment]
> Thanks @eldridgeh 🙌 I've been breaking my head trying to get around this error 🙈
> 
> I expect I'll run into the same issue as you, @francispeixoto, so I'm manually limiting my queue size until I catch up. Here's hoping that works 🤞

where do you limit the DDL queue size?
