### ISSUE TITLE
Downloads arent starting

### ISSUE THREAD

**Issue by Fespinoza831** [mylar3/mylar3#1578]
**Describe the bug**
Downloads arent starting, they just remain in queue. Also notice that the DDL-QUEUE down down every now and then. AUTO-SNATCHER has also never started.

**CarePackage**
its attached

**Environment (please complete the following information):**
 - OS: Unraid

**Additional information**
When I manually click start on of the downloads in queue sometimes they will start, other time i get No filename assigned for 
This was probably never started successfully - you should restart the download (use the option in the GUI).

I have also never seen any files in my download directories for nzb or torrents

[carepackage_v0.8.0.zip](https://github.com/user-attachments/files/17969877/carepackage_v0.8.0.zip)

**Comment by francispeixoto** [comment]
I had the same type of symptoms until I moved from a container on a Synology NAS to a container on a much more powerful dedicated linux server. My entire DDL queue seemed to wake from hibernation and the DDL queue job never went down again.

**Comment by Flameingskull** [comment]
> I had the same type of symptoms until I moved from a container on a Synology NAS to a container on a much more powerful dedicated linux server. My entire DDL queue seemed to wake from hibernation and the DDL queue job never went down again.

I've got Mylar3 running on a docker container on a dedicated linux server and I get have the same issue as the OP. The queue did work automatically at first but then then DDL queue dropped. I'm able to restart the function and the queue by restarting mylar but using the restart queue function on the queue management tab only restarts the queue without triggering any downloads.

I'm currently away from my server so I'll have to share logs when I have physical access to it in about a week.

**Comment by barrelltitor** [comment]
The error in the author's carepackage is networking related

```
Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/helpers.py", line 3428, in ddl_downloader
    ggc.parse_downloadresults(item['id'], item['mainlink'], item['comicinfo'], item['packinfo'], link_type_failure[item['id']])
  File "/app/mylar3/mylar/getcomics.py", line 531, in parse_downloadresults
    self.loadsite(id, mainlink)
  File "/app/mylar3/mylar/getcomics.py", line 313, in loadsite
    t = self.session.get(
        ^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='getcomics.org', port=443): Max retries exceeded with url: /marvel/amazing-spider-man-93-2022/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x152dc7915b90>: Failed to establish a new connection: [Errno -3] Try again'))
```

Whatever that session.get is should be wrapped in a try block, but can you try on the dev branch? There's been quite some changes from master as the queue crashing might be fixed already, though you need to investigate the networking issues on your own as those are from your setup not mylar

If anyone does get the queue crashing on the dev branch please send a carepackage so we can see why it's happening and fix it.
