### ISSUE TITLE
Error occurs on torznab searches

### ISSUE THREAD

**Issue by renhardy** [mylar3/mylar3#164]
Every time a search is launched, forced or scheduled a error occurs stopping the search and seems to suspend other processes

05-Mar-2020 15:46:06 - INFO    :: mylar.configure.1009 : MainThread : [COMICTAGGER] Version detected: 1.3.1
05-Mar-2020 15:46:06 - INFO    :: mylar.initialize.186 : MainThread : Checking to see if the database has all tables....
05-Mar-2020 15:46:06 - INFO    :: mylar.dbcheck.1318 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
05-Mar-2020 15:46:06 - INFO    :: mylar.dbcheck.1320 : MainThread : Correcting Null entries that make the main page break on startup.
05-Mar-2020 15:46:06 - INFO    :: mylar.initialize.200 : MainThread : Successfully discovered local IP and locking it in as : 172.17.0.4
05-Mar-2020 15:46:06 - INFO    :: mylar.initialize.262 : MainThread : Remapping the sorting to allow for new additions.
05-Mar-2020 15:46:06 - INFO    :: mylar.ComicSort.761 : MainThread : Sucessfully ordered 3 series in your watchlist.
05-Mar-2020 15:46:06 - INFO    :: mylar.validateAndCreateDirectory.1693 : MainThread : [DIRECTORY-CHECK] Found comic directory: /config/app
05-Mar-2020 15:46:06 - INFO    :: mylar.initialize.72 : MAIN : Starting Mylar on http://0.0.0.0:8090/
05-Mar-2020 15:46:06 - INFO    :: mylar.getVersion.186 : MAIN : [LAST_RELEASE] Branch:  master
05-Mar-2020 15:46:06 - INFO    :: mylar.getVersion.191 : MAIN : [LAST_RELEASE] Version: v0.3.0
05-Mar-2020 15:46:06 - INFO    :: mylar.getVersion.194 : MAIN : [LAST_RELEASE] Commit: 232c56b30153d17f0de63784e317f7d0e4cec5de
05-Mar-2020 15:46:06 - INFO    :: mylar.getVersion.208 : MAIN : Current Release Name: Hulk smash!
05-Mar-2020 15:46:06 - INFO    :: mylar.getVersion.215 : MAIN : Branch detected & set to :  master
05-Mar-2020 15:46:06 - INFO    :: mylar.versionload.359 : MAIN : version_info: {'current_version': '232c56b30153d17f0de63784e317f7d0e4cec5de', 'current_version_name': 'v0.3.0', 'branch': ' master', 'current_release_name': 'Hulk smash!'}
05-Mar-2020 15:46:06 - INFO    :: mylar.versionload.379 : MAIN : Version information:  master [232c56b30153d1435t3ggsdg34gdgst24twc5de]
05-Mar-2020 15:46:06 - INFO    :: mylar.start.356 : MAIN : DB Updater sccheduled to fire every 5 minutes
05-Mar-2020 15:46:06 - INFO    :: mylar.queue_schedule.525 : MAIN : [SEARCH-QUEUE] Attempting to background load the search queue....
05-Mar-2020 15:46:06 - INFO    :: mylar.queue_schedule.528 : MAIN : [SEARCH-QUEUE] Successfully started the Search Queuer...
05-Mar-2020 15:46:06 - INFO    :: mylar.queue_schedule.536 : MAIN : [POST-PROCESS-QUEUE] Post Process queue enabled & monitoring for api requests....
05-Mar-2020 15:46:06 - INFO    :: mylar.queue_schedule.539 : MAIN : [POST-PROCESS-QUEUE] Succesfully started Post-Processing Queuer....
05-Mar-2020 15:46:06 - INFO    :: mylar.start.405 : MAIN : [WEEKLY] Checking for existance of Weekly Comic listing...
05-Mar-2020 15:46:06 - INFO    :: mylar.start.471 : MAIN : Firing up the Background Schedulers now....
05-Mar-2020 15:46:06 - INFO    :: mylar.start.475 : MAIN : Background Schedulers successfully started...
05-Mar-2020 15:46:20 - INFO    :: mylar.toggleVerbose.4015 : CP Server Thread-9 : Verbose (DEBUG) logging is enabled
05-Mar-2020 15:46:20 - DEBUG   :: mylar.toggleVerbose.4016 : CP Server Thread-9 : If you can read this message, debug logging is now working
05-Mar-2020 15:46:20 - INFO    :: mylar.toggleVerbose.4019 : CP Server Thread-9 : config file has been loaded from: /config/app/config.ini
05-Mar-2020 15:46:23 - INFO    :: mylar.schedulerForceCheck.2642 : CP Server Thread-3 : [Auto-Search (trigger: interval[6:00:00], next run at: 2020-03-06 02:45:19 UTC)] Now force submitting job for jobid search
05-Mar-2020 15:46:23 - INFO    :: mylar.run.28 : ThreadPoolExecutor-0_0 : [SEARCH] Running Search for Wanted.
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1614 : ThreadPoolExecutor-0_0 : Initiating check to add Wanted items to Search Queue....
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:118500  IssueiD: 714255
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:118500  IssueiD: 712334
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:118500  IssueiD: 710006
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:118500  IssueiD: 706858
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 636411
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 612006
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 599898
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 592634
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 587440
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 534311
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 527174
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 520230
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 514490
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 510990
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 499885
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 497433
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 494597
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 493840
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 491620
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 490940
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:81986  IssueiD: 488743
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 487873
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 482739
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 477905
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 473600
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 470384
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 468423
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 462214
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 460275
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 453372
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 451051
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 447962
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 442887
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 437436
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 433797
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 428890
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1767 : ThreadPoolExecutor-0_0 : adding: ComicID:67426  IssueiD: 425853
05-Mar-2020 15:46:23 - INFO    :: mylar.searchforissue.1781 : ThreadPoolExecutor-0_0 : Completed Queueing API Search scan
05-Mar-2020 15:46:23 - DEBUG   :: mylar.job_management.3567 : ThreadPoolExecutor-0_0 : ReScheduled job: Auto-Search to 2020-03-06 02:46:23
05-Mar-2020 15:46:26 - INFO    :: mylar.search_queue.3112 : SEARCH-QUEUE : [SEARCH-QUEUE] Now loading item from search queue: {'comicname': 'Ascender', 'seriesyear': '2019', 'issuenumber': '4', 'issueid': '714255', 'comicid': '118500', 'booktype': 'Print'}
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.63 : SEARCH-QUEUE : Publisher is : Image
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.71 : SEARCH-QUEUE : Issue Title given as : b'the haunted galaxy, part four'
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.102 : SEARCH-QUEUE : Checking for torrent enabled.
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.153 : SEARCH-QUEUE : nzbprovider(s): []
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.156 : SEARCH-QUEUE : There are 4 torrent providers you have selected.
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.161 : SEARCH-QUEUE : There are : 0 nzb providers you have selected
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.180 : SEARCH-QUEUE : search provider order is ['torznab: 1337x', 'torznab: thepiratebay', 'torznab: TorrentProjet2', 'torznab: Limetorrents']
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.247 : SEARCH-QUEUE : calpha/cnumber: None / None
05-Mar-2020 15:46:26 - DEBUG   :: mylar.search_init.283 : SEARCH-QUEUE : Initiating Search via : api
05-Mar-2020 15:46:26 - DEBUG   :: mylar.NZB_SEARCH.468 : SEARCH-QUEUE : Using Torznab host of : 1337x
05-Mar-2020 15:46:26 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Ascender issue: 4 (2019) using 1337x (torznab).
05-Mar-2020 15:46:26 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
05-Mar-2020 15:46:26 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
05-Mar-2020 15:46:26 - DEBUG   :: mylar.NZB_SEARCH.758 : SEARCH-QUEUE : [SSL: False] Search URL: http://192.168.1.134:9117/api/v2.0/indexers/1337x/results/torznab?t=search&q=ascender%20004&cat=&apikey=ypo4pi1od7jct29m75gowndrofhrq5jk
05-Mar-2020 15:46:27 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
05-Mar-2020 15:46:27 - INFO    :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 4 of Ascender (2019) using 1337x [api]
05-Mar-2020 15:46:27 - DEBUG   :: mylar.NZB_SEARCH.468 : SEARCH-QUEUE : Using Torznab host of : thepiratebay
05-Mar-2020 15:46:27 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Ascender issue: 4 (2019) using thepiratebay (torznab).
05-Mar-2020 15:46:27 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
05-Mar-2020 15:46:27 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
05-Mar-2020 15:46:27 - DEBUG   :: mylar.NZB_SEARCH.758 : SEARCH-QUEUE : [SSL: False] Search URL: http://192.168.1.134:9117/api/v2.0/indexers/thepiratebay/results/torznab?t=search&q=ascender%20004&cat=&apikey=ypo4pi1od7jct29m75gowndrofhrq5jk
05-Mar-2020 15:46:28 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
05-Mar-2020 15:46:28 - INFO    :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 4 of Ascender (2019) using thepiratebay [api]
05-Mar-2020 15:46:28 - DEBUG   :: mylar.NZB_SEARCH.468 : SEARCH-QUEUE : Using Torznab host of : TorrentProjet2
05-Mar-2020 15:46:28 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Ascender issue: 4 (2019) using TorrentProjet2 (torznab).
05-Mar-2020 15:46:28 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
05-Mar-2020 15:46:28 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
05-Mar-2020 15:46:28 - DEBUG   :: mylar.NZB_SEARCH.758 : SEARCH-QUEUE : [SSL: False] Search URL: http://192.168.1.134:9117/api/v2.0/indexers/torrentproject2/results/torznab?t=search&q=ascender%20004&cat=&apikey=ypo4pi1od7jct29m75gowndrofhrq5jk
05-Mar-2020 15:46:29 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
05-Mar-2020 15:46:29 - INFO    :: mylar.search_init.396 : SEARCH-QUEUE : Could not find Issue 4 of Ascender (2019) using TorrentProjet2 [api]
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.468 : SEARCH-QUEUE : Using Torznab host of : Limetorrents
05-Mar-2020 15:46:29 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Ascender issue: 4 (2019) using Limetorrents (torznab).
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.578 : SEARCH-QUEUE : findloop: 0 / findcount: 1
05-Mar-2020 15:46:29 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.758 : SEARCH-QUEUE : [SSL: False] Search URL: http://192.168.1.134:9117/api/v2.0/indexers/limetorrents/results/torznab?t=search&q=ascender%20004&cat=&apikey=ypo4pi1od7jct29m75gowndrofhrq5jk
05-Mar-2020 15:46:29 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.857 : SEARCH-QUEUE : checking search result: Ascender 004 (2019) (Digital) (Zone-Empire)
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : sub: Ascender 004 (2019) (Digital) (Zone-Empire)
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.916 : SEARCH-QUEUE : comsize_b: 65630372
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.953 : SEARCH-QUEUE : size given as: 62.6 MB
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.999 : SEARCH-QUEUE : store date used is : 2019-07-24
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1000 : SEARCH-QUEUE : date used is : 2019-07-24
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1043 : SEARCH-QUEUE : usedate: 2019-07-24
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1089 : SEARCH-QUEUE : [CONV] Thu, 08 Aug 2019 20:46:29 +0000 is after store date of 2019-07-24
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1109 : SEARCH-QUEUE : Entry: Ascender 004 (2019) (Digital) (Zone-Empire)
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.325 : SEARCH-QUEUE : Scanner group tag discovered: Zone-Empire
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.436 : SEARCH-QUEUE : NEWLY SPLIT REORGD: ['Ascender', '004', '(2019)', '(Digital)']
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.471 : SEARCH-QUEUE : checking date : 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.474 : SEARCH-QUEUE : date: 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.802 : SEARCH-QUEUE : datecheck: [{'date': '2019', 'position': 2, 'mod_position': 14}]
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.808 : SEARCH-QUEUE : sctd: 2020
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.817 : SEARCH-QUEUE : year verified as : 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.823 : SEARCH-QUEUE : year verified as: 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.855 : SEARCH-QUEUE : highest_series_position: 2
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.875 : SEARCH-QUEUE : possible_issuenumbers: [{'number': '004', 'position': 1, 'mod_position': 9, 'validcountchk': False}]
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.924 : SEARCH-QUEUE : issue number :004
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.953 : SEARCH-QUEUE : issue_position: 1
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.970 : SEARCH-QUEUE : issue verified as : 004
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.1104 : SEARCH-QUEUE : sf_highest_series_pos: ['Ascender']
05-Mar-2020 15:46:29 - DEBUG   :: mylar.parseit.1152 : SEARCH-QUEUE : series title possibly: Ascender
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1126 : SEARCH-QUEUE : parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': 'Ascender 004 (2019) (Digital) (Zone-Empire)', 'comiclocation': None, 'series_name': 'Ascender', 'series_name_decoded': 'Ascender', 'issueid': None, 'dynamic_name': 'Ascender', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2019', 'issue_number': '004', 'scangroup': 'Zone-Empire', 'reading_order': None, 'booktype': 'issue'}
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1135 : SEARCH-QUEUE : match_check: {'process_status': 'match', 'sub': None, 'volume': None, 'match_type': None, 'comicfilename': 'Ascender 004 (2019) (Digital) (Zone-Empire)', 'comiclocation': None, 'series_name': 'Ascender', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2019', 'issueid': None, 'justthedigits': '004', 'annual_comicid': None, 'scangroup': 'Zone-Empire', 'booktype': 'issue'}
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1201 : SEARCH-QUEUE : year detected: 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1203 : SEARCH-QUEUE : year looking for: 2019
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1205 : SEARCH-QUEUE : 2019 - right years match baby!
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1383 : SEARCH-QUEUE : issue we are looking for is : 4
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1384 : SEARCH-QUEUE : integer value of issue we are looking for : 4000
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1391 : SEARCH-QUEUE : issue we found for is : 004
05-Mar-2020 15:46:29 - DEBUG   :: mylar.NZB_SEARCH.1393 : SEARCH-QUEUE : integer value of issue we have found : 4000
05-Mar-2020 15:46:29 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/helpers.py", line 3114, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/app/mylar/search.py", line 1873, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/app/mylar/search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/app/mylar/search.py", line 1489, in NZB_SEARCH
    nzbname = nzbname_create(nzbprov, info=mylar.COMICINFO, title=ComicTitle) #entry['title'])
  File "/app/mylar/search.py", line 2004, in nzbname_create
    if os.path.exists(mylar.CONFIG.BLACKHOLE_DIR):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

Environnement:

Mylar Version: master [v0.3.0 - Hulk smash!] 
-- source (build 232c56b30153d17f0de63784e317f7d0e4cec5de)
Python Version : 3.7.5
Language : en_US.UTF-8

Running in a container (hotio) on a Debian 10 system

I have tried removing some of the Torznab to see if the error was coming from a specific provider, but it seems it happens with all providers.

Thanks

**Comment by evilhero** [comment]
Do you have the blackhole option specified for torrents? It's trying to send the torrent to your blackhole directory, only you don't have anything set for it.

Is there a particular reason you're not using one of the clients available within mylar, instead of a blackhole?

**Comment by renhardy** [comment]
I did have the blackhole option enable for NZBs since I am not using usenet. I was not aware it would look for torrents there.

I have made the changes and it solved the error I was seeing. I still get a error when mylar pushes a magnet link to deluge, but the torrents get added anyway

thanks

**Comment by evilhero** [comment]
Yeah there's some glitching with the blackhole aspect that we need to look into - it doesn't come up very often as not many use it.

I believe there was someone looking at the deluge error after something gets pushed, but we should address that. Is it just a popup in the GUI saying there was an error, or something in the logs to indicate?

**Comment by renhardy** [comment]
All right thanks for your help.

as for the deluge error, here is the log from the GUI:


2020-03-05 16:44:39 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
-- | -- | --
2020-03-05 16:44:39 | INFO | Checking if Torrent Exists!
2020-03-05 16:44:39 | INFO | filepath to torrent file set to : magnet:?xt=urn:btih:978062719C5F99CDE8D0C08F3E261C6FCF02AAB5&dn=&tr=udp://tracker.torrent.eu.org:451/announce&tr=http://tracker.ipv6tracker.ru:80/announce&tr=udp://retracker.hotplug.ru:2710/announce&tr=https://tracker.fastdownload.xyz:443/announce&tr=https://opentracker.xyz:443/announce&tr=http://open.trackerlist.xyz:80/announce&tr=udp://tracker.birkenwald.de:6969/announce&tr=https://t.quic.ws:443/announce&tr=https://tracker.parrotsec.org:443/announce&tr=udp://tracker.supertracker.net:1337/announce&tr=http://gwp2-v19.rinet.ru:80/announce&tr=udp://bigfoot1942.sektori.org:6969/announce&tr=udp://carapax.net:6969/announce&tr=udp://retracker.akado-ural.ru:80/announce&tr=udp://retracker.maxnet.ua:80/announce&tr=udp://bt.dy20188.com:80/announce&tr=http://0d.kebhana.mx:443/announce&tr=http://tracker.files.fm:6969/announce&tr=http://retracker.joxnet.ru:80/announce&tr=http://tracker.moxing.party:6969/announce
2020-03-05 16:44:39 | INFO | Connected to Deluge! Will try to add torrent now!
2020-03-05 16:44:39 | INFO | Got a magnet url from redirect.

**Comment by renhardy** [comment]
Hi,

Still getting a error on torznab searches. Different one than last time though. I cant figure out if it is still related to my config. Thanks:

06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Zero issue: 18 (2015) using Limetorrents (torznab).
06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
06-Mar-2020 12:02:14 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/helpers.py", line 3114, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/app/mylar/search.py", line 1873, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/app/mylar/search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/app/mylar/search.py", line 1124, in NZB_SEARCH
    parsed_comic = p_comic.listFiles()
  File "/app/mylar/filechecker.py", line 116, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar/filechecker.py", line 355, in parseit
    tmpfilename = re.sub(i, 'XCV', tmpfilename)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 526, in _parse
    source.tell() - here)
re.error: unterminated character set at position 5

06-Mar-2020 12:03:07 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_1 : Update complete
06-Mar-2020 12:08:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_2 : Update complete
06-Mar-2020 12:13:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_4 : Update complete
06-Mar-2020 12:18:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_0 : Update complete
06-Mar-2020 12:23:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_2 : Update complete
06-Mar-2020 12:28:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_7 : Update complete

**Comment by barbequesauce** [comment]
@renhardy I'm moving that second error to #168 as it's a very different error and related to searching, not about torznab...

**Comment by barbequesauce** [comment]
Any chance we can see a debug log?

**Comment by barbequesauce** [comment]
Closing this due to inactivity. Feel free to reopen when you have an update.
