### ISSUE TITLE
Error on torznab searches (XCV vs "Zero (2015)")

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#168]
Hi,

Still getting a error on torznab searches. Different one than last time though. I cant figure out if it is still related to my config. Thanks:

06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.514 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Zero issue: 18 (2015) using Limetorrents (torznab).
06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.740 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering
06-Mar-2020 12:02:14 - INFO    :: mylar.NZB_SEARCH.816 : SEARCH-QUEUE : no errors on data retrieval...proceeding
06-Mar-2020 12:02:14 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/helpers.py", line 3114, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/app/mylar/search.py", line 1873, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/app/mylar/search.py", line 360, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/app/mylar/search.py", line 1124, in NZB_SEARCH
    parsed_comic = p_comic.listFiles()
  File "/app/mylar/filechecker.py", line 116, in listFiles
    runresults = self.parseit(self.dir, self.file)
  File "/app/mylar/filechecker.py", line 355, in parseit
    tmpfilename = re.sub(i, 'XCV', tmpfilename)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 526, in _parse
    source.tell() - here)
re.error: unterminated character set at position 5

06-Mar-2020 12:03:07 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_1 : Update complete
06-Mar-2020 12:08:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_2 : Update complete
06-Mar-2020 12:13:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_4 : Update complete
06-Mar-2020 12:18:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_0 : Update complete
06-Mar-2020 12:23:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_2 : Update complete
06-Mar-2020 12:28:08 - INFO    :: mylar.dbUpdate.352 : ThreadPoolExecutor-0_7 : Update complete

_Originally posted by @renhardy in https://github.com/mylar3/mylar3/issues/164#issuecomment-595907929_

**Comment by evilhero** [comment]
Did you define any categories within mylar for that torznab? That would limit the search results to just comics instead of returning everything. 

 Also if you could do a searfh with debug logging enabled we can see what the search result is that it's trying to parse and erroring on.

**Comment by barbequesauce** [comment]
@renhardy ^^^ :)

**Comment by renhardy** [comment]
I did not add categories to the torznab, I did not want to exclude results. I managed to reproduce the error after adding a few more wanted issues. Here is the debug log from the GUI. I copied more than less to make sure you had the info you need:


2020-03-09 15:52:05 | ERROR | Uncaught exception: Traceback (most recent call last):File "/app/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/usr/lib/python3.7/threading.py", line 870, in runself._target(*self._args, **self._kwargs)File "/app/mylar/helpers.py", line 3114, in search_queuess_queue = mylar.search.searchforissue(item['issueid'])File "/app/mylar/search.py", line 1873, in searchforissuefoundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)File "/app/mylar/search.py", line 360, in search_initfindit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)File "/app/mylar/search.py", line 1124, in NZB_SEARCHparsed_comic = p_comic.listFiles()File "/app/mylar/filechecker.py", line 116, in listFilesrunresults = self.parseit(self.dir, self.file)File "/app/mylar/filechecker.py", line 355, in parseittmpfilename = re.sub(i, 'XCV', tmpfilename)File "/usr/lib/python3.7/re.py", line 192, in subreturn _compile(pattern, flags).sub(repl, string, count)File "/usr/lib/python3.7/re.py", line 286, in _compilep = sre_compile.compile(pattern, flags)File "/usr/lib/python3.7/sre_compile.py", line 764, in compilep = sre_parse.parse(p, flags)File "/usr/lib/python3.7/sre_parse.py", line 938, in parseraise source.error("unbalanced parenthesis")re.error: unbalanced parenthesis at position 9
-- | -- | --
2020-03-09 15:52:05 | DEBUG | Entry: 2017 Лахти (Финляндия) Женщины Скиатлон 15 км ..
2020-03-09 15:52:05 | DEBUG | [CONV] Sun, 14 Apr 2019 19:52:05 +0000 is after store date of 2017-02-15
2020-03-09 15:52:05 | DEBUG | usedate: 2017-02-15
2020-03-09 15:52:05 | DEBUG | date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | store date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | size given as: 1.21 GB
2020-03-09 15:52:05 | DEBUG | comsize_b: 1299227648
2020-03-09 15:52:05 | DEBUG | sub: 2017 Лахти (Финляндия) Женщины Скиатлон 15 км ..
2020-03-09 15:52:05 | DEBUG | checking search result: 2017 Лахти (Финляндия) Женщины Скиатлон 15 км ..
2020-03-09 15:52:05 | DEBUG | 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT.. was not a match to My Favorite Thing Is Monsters (2017)
2020-03-09 15:52:05 | DEBUG | match_check: {'process_status': 'fail', 'comicfilename': '2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..', 'sub': None, 'comiclocation': None, 'series_name': '2017 -18 1', 'alt_series': None, 'alt_issue': None, 'issue_number': '-16финала Первые матчи Обзор', 'series_volume': None, 'issue_year': '2017', 'issueid': None, 'scangroup': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': '2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..', 'comiclocation': None, 'series_name': '2017 -18 1', 'series_name_decoded': '2017 -18 1', 'issueid': None, 'dynamic_name': '2017\|181', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2017', 'issue_number': '-16финала Первые матчи Обзор', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | series title possibly: 2017 -18 1
2020-03-09 15:52:05 | DEBUG | sf_highest_series_pos: ['2017', '-18', '1']
2020-03-09 15:52:05 | DEBUG | issue verified as : -16XCV
2020-03-09 15:52:05 | DEBUG | issue_position: 3
2020-03-09 15:52:05 | DEBUG | issue number :-16XCV
2020-03-09 15:52:05 | DEBUG | hyphen located at position: 4
2020-03-09 15:52:05 | DEBUG | possible_issuenumbers: [{'number': '-18', 'position': 1, 'mod_position': 4, 'validcountchk': False}, {'number': '1', 'position': 2, 'mod_position': 5, 'validcountchk': False}, {'number': '-16XCV', 'position': 3, 'mod_position': 9, 'validcountchk': False}]
2020-03-09 15:52:05 | DEBUG | highest_series_position: 0
2020-03-09 15:52:05 | DEBUG | year verified as: 2017
2020-03-09 15:52:05 | DEBUG | year verified as : 2017
2020-03-09 15:52:05 | DEBUG | sctd: 2020
2020-03-09 15:52:05 | DEBUG | datecheck: [{'date': '2017', 'position': 0, 'mod_position': 0}]
2020-03-09 15:52:05 | DEBUG | checking date : 15 02 2018
2020-03-09 15:52:05 | DEBUG | this should be: -16XCV
2020-03-09 15:52:05 | DEBUG | [SPECIAL-CHARACTER ISSUE] Possible issue # : финала Первые матчи Обзор
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -16
2020-03-09 15:52:05 | DEBUG | 2 seperate numbers detected. Assuming 2nd number is the actual issue
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -18
2020-03-09 15:52:05 | DEBUG | date: 2017
2020-03-09 15:52:05 | DEBUG | checking date : 2017
2020-03-09 15:52:05 | DEBUG | NEWLY SPLIT REORGD: ['2017', '-18', '1', '-16', 'XCV', '(15 02 2018)', 'IPT']
2020-03-09 15:52:05 | DEBUG | Entry: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | [CONV] Tue, 14 May 2019 19:52:05 +0000 is after store date of 2017-02-15
2020-03-09 15:52:05 | DEBUG | usedate: 2017-02-15
2020-03-09 15:52:05 | DEBUG | date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | store date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | size given as: 666.8 MB
2020-03-09 15:52:05 | DEBUG | comsize_b: 699159040
2020-03-09 15:52:05 | DEBUG | sub: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | checking search result: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT.. was not a match to My Favorite Thing Is Monsters (2017)
2020-03-09 15:52:05 | DEBUG | match_check: {'process_status': 'fail', 'comicfilename': '2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..', 'sub': None, 'comiclocation': None, 'series_name': '2017 -18 1', 'alt_series': None, 'alt_issue': None, 'issue_number': '-16финала Первые матчи Обзор', 'series_volume': None, 'issue_year': '2017', 'issueid': None, 'scangroup': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': '2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..', 'comiclocation': None, 'series_name': '2017 -18 1', 'series_name_decoded': '2017 -18 1', 'issueid': None, 'dynamic_name': '2017\|181', 'series_volume': None, 'alt_series': None, 'alt_issue': None, 'issue_year': '2017', 'issue_number': '-16финала Первые матчи Обзор', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | series title possibly: 2017 -18 1
2020-03-09 15:52:05 | DEBUG | sf_highest_series_pos: ['2017', '-18', '1']
2020-03-09 15:52:05 | DEBUG | issue verified as : -16XCV
2020-03-09 15:52:05 | DEBUG | issue_position: 3
2020-03-09 15:52:05 | DEBUG | issue number :-16XCV
2020-03-09 15:52:05 | DEBUG | hyphen located at position: 4
2020-03-09 15:52:05 | DEBUG | possible_issuenumbers: [{'number': '-18', 'position': 1, 'mod_position': 4, 'validcountchk': False}, {'number': '1', 'position': 2, 'mod_position': 5, 'validcountchk': False}, {'number': '-16XCV', 'position': 3, 'mod_position': 9, 'validcountchk': False}]
2020-03-09 15:52:05 | DEBUG | highest_series_position: 0
2020-03-09 15:52:05 | DEBUG | year verified as: 2017
2020-03-09 15:52:05 | DEBUG | year verified as : 2017
2020-03-09 15:52:05 | DEBUG | sctd: 2020
2020-03-09 15:52:05 | DEBUG | datecheck: [{'date': '2017', 'position': 0, 'mod_position': 0}]
2020-03-09 15:52:05 | DEBUG | checking date : 15 02 2018
2020-03-09 15:52:05 | DEBUG | this should be: -16XCV
2020-03-09 15:52:05 | DEBUG | [SPECIAL-CHARACTER ISSUE] Possible issue # : финала Первые матчи Обзор
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -16
2020-03-09 15:52:05 | DEBUG | 2 seperate numbers detected. Assuming 2nd number is the actual issue
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -18
2020-03-09 15:52:05 | DEBUG | date: 2017
2020-03-09 15:52:05 | DEBUG | checking date : 2017
2020-03-09 15:52:05 | DEBUG | NEWLY SPLIT REORGD: ['2017', '-18', '1', '-16', 'XCV', '(15 02 2018)', 'IPT']
2020-03-09 15:52:05 | DEBUG | Entry: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | [CONV] Tue, 14 May 2019 19:52:05 +0000 is after store date of 2017-02-15
2020-03-09 15:52:05 | DEBUG | usedate: 2017-02-15
2020-03-09 15:52:05 | DEBUG | date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | store date used is : 2017-02-15
2020-03-09 15:52:05 | DEBUG | size given as: 1.5 GB
2020-03-09 15:52:05 | DEBUG | comsize_b: 1610612736
2020-03-09 15:52:05 | DEBUG | sub: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | checking search result: 2017-18 1-16 финала Первые матчи Обзор (15 02 2018) IPT..
2020-03-09 15:52:05 | DEBUG | (2018 02 15) Ницца - Локомотив Лига Европы 2017-18 1-1.. was not a match to My Favorite Thing Is Monsters (2017)
2020-03-09 15:52:05 | DEBUG | match_check: {'process_status': 'fail', 'comicfilename': '(2018 02 15) Ницца - Локомотив Лига Европы 2017-18 1-1..', 'sub': None, 'comiclocation': None, 'series_name': '(2018 02 15) Ницца - Локомотив Лига Европы 2017 -18 1', 'alt_series': '(2018 02 15) Ницца', 'alt_issue': 'Ницца 2017 -18 1', 'issue_number': '-1', 'series_volume': None, 'issue_year': '2017', 'issueid': None, 'scangroup': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | parsed_info: {'parse_status': 'success', 'sub': None, 'comicfilename': '(2018 02 15) Ницца - Локомотив Лига Европы 2017-18 1-1..', 'comiclocation': None, 'series_name': '(2018 02 15) Ницца - Локомотив Лига Европы 2017 -18 1', 'series_name_decoded': '(2018 02 15) Ницца - Локомотив Лига Европы 2017 -18 1', 'issueid': None, 'dynamic_name': '\|20180215\|Ницца\|ЛокомотивЛигаЕвропы2017\|181', 'series_volume': None, 'alt_series': '(2018 02 15) Ницца', 'alt_issue': 'Ницца 2017 -18 1', 'issue_year': '2017', 'issue_number': '-1', 'scangroup': None, 'reading_order': None, 'booktype': 'issue'}
2020-03-09 15:52:05 | DEBUG | Alternate series / issue title: (2018 02 15) Ницца [Ницца 2017 -18 1]
2020-03-09 15:52:05 | DEBUG | series title possibly: (2018 02 15) Ницца - Локомотив Лига Европы 2017 -18 1
2020-03-09 15:52:05 | DEBUG | sf_highest_series_pos: ['(2018 02 15)', 'XCV', '-', 'XCV', '2017', '-18', '1']
2020-03-09 15:52:05 | DEBUG | ALT-SERIES NAME [ISSUE TITLE]: (2018 02 15) XCV [XCV 2017 -18 1]
2020-03-09 15:52:05 | DEBUG | issue verified as : -1
2020-03-09 15:52:05 | DEBUG | issue_position: 7
2020-03-09 15:52:05 | DEBUG | Already validated year, ignoring as possible issue number: 2017
2020-03-09 15:52:05 | DEBUG | issue number :-1
2020-03-09 15:52:05 | DEBUG | yearposition: 4
2020-03-09 15:52:05 | DEBUG | hyphen located at position: 17
2020-03-09 15:52:05 | DEBUG | possible_issuenumbers: [{'number': 'XCV', 'position': 1, 'mod_position': 13, 'validcountchk': False}, {'number': 'XCV', 'position': 1, 'mod_position': 19, 'validcountchk': False}, {'number': '2017', 'position': 4, 'mod_position': 23, 'validcountchk': False}, {'number': '-18', 'position': 5, 'mod_position': 27, 'validcountchk': False}, {'number': '1', 'position': 6, 'mod_position': 28, 'validcountchk': False}, {'number': '-1', 'position': 7, 'mod_position': 32, 'validcountchk': False}]
2020-03-09 15:52:05 | DEBUG | highest_series_position: 4
2020-03-09 15:52:05 | DEBUG | year verified as: 2017
2020-03-09 15:52:05 | DEBUG | year verified as : 2017
2020-03-09 15:52:05 | DEBUG | sctd: 2020
2020-03-09 15:52:05 | DEBUG | datecheck: [{'date': '2017', 'position': 4, 'mod_position': 23}]
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -1
2020-03-09 15:52:05 | DEBUG | 2 seperate numbers detected. Assuming 2nd number is the actual issue
2020-03-09 15:52:05 | DEBUG | I have encountered a negative issue #: -18
2020-03-09 15:52:05 | DEBUG | date: 2017
2020-03-09 15:52:05 | DEBUG | checking date : 2017

**Comment by evilhero** [comment]
You kinda ```have``` to add a category for your torznab instance - or else it will poll against movies, music, tv shows, porn, etc.  Setting the category to ```7030``` which is what it typically is doesn't impact the torznab itself, it just sets the query to hit against that specific category which all the torznab indexers support regardless.

The only other thing to do is completely reject anything that throws that traceback which is probably what we'll end up doing - cause anything that throws back that type of error is going to be unparsable regardless.

**Comment by renhardy** [comment]
Thanks for the quick reply. I added the categories to the providers.

**Comment by barbequesauce** [comment]
Did that clean up the problem?

**Comment by renhardy** [comment]
Not really, most of the trackers I use do not seem to support that category:

09-Mar-2020 16:12:12 - ERROR   :: mylar.NZB_SEARCH.804 : SEARCH-QUEUE : [ERROR CODE: 201] 1337x does not support the requested query. Please check the capabilities (t=caps) and make sure the search mode and categories are supported.

I get that for most of the providers I have.

**Comment by evilhero** [comment]
The ```7030``` might be different depending on the provider - ```7030``` is the typical one as that's based off of newznab. You'd have to reference the jackett category properties for that indexer and use whatever it is for Comics within Mylar. For example, IPT is 8020 according to google.

**Comment by renhardy** [comment]
All right, thanks.

I'll make the changes and tell you if it improves.

**Comment by barbequesauce** [comment]
Any updates?

**Comment by barbequesauce** [comment]
Closing this due to inactivity. Feel free to reopen when you have an update.
