### ISSUE TITLE
failure writing nzb to cache

### ISSUE THREAD

**Issue by mylar3** [mylar3/mylar3#2]
```13-Jan-2020 16:41:06 - DEBUG :: mylar.searcher.2293 : SEARCH-QUEUE : [FILENAME] end nzbname: Dr.Strange-Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
13-Jan-2020 16:41:06 - DEBUG :: mylar.searcher.2308 : SEARCH-QUEUE : Cache Directory successfully found at : /opt/mylar.py3/cache
13-Jan-2020 16:41:06 - ERROR :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar.py3/mylar/helpers.py", line 3177, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/opt/mylar.py3/mylar/search.py", line 1862, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 371, in search_init
    findit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 1489, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/opt/mylar.py3/mylar/search.py", line 2494, in searcher
    send_to_nzbget = ss.sender(nzbpath)
  File "/opt/mylar.py3/mylar/nzbget.py", line 72, in sender
    if not chunk:
NameError: name 'chunk' is not defined

Traceback (most recent call last):
  File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/opt/pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/mylar.py3/mylar/helpers.py", line 3177, in search_queue
    ss_queue = mylar.search.searchforissue(item['issueid'])
  File "/opt/mylar.py3/mylar/search.py", line 1862, in searchforissue
    foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 371, in search_init
    findit = NZB_SEARCH(AS_Alternate, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 1489, in NZB_SEARCH
    searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  File "/opt/mylar.py3/mylar/search.py", line 2494, in searcher
    send_to_nzbget = ss.sender(nzbpath)
  File "/opt/mylar.py3/mylar/nzbget.py", line 72, in sender
    if not chunk:
NameError: name 'chunk' is not defined```

**Comment by evilhero** [comment]
This should be fixed as of 05652beef1172b58f98624c8ea34d52d4f881c12
