### ISSUE TITLE
systemd startup not working

### ISSUE THREAD

**Issue by Serneum** [mylar3/mylar3#200]
**Describe the bug**
Conversation in https://github.com/evilhero/mylar/issues/2432 led me to try installing Mylar3 alongside my old Mylar instance. All of the init.d scripts seem to be the same, but just to be safe I followed the `read.me` file and copied them all into place. I also set up a `PYTHON_BIN` in my `defaults` file since my server has `python` and `python3`. After running the `systemctl` reload and enable commands, I ran `systemctl start mylar` with no luck.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4
- Python: 3.6.9
 - Branch / commit: a5e12b5

**Additional information**
Per the conversation in my issue on the old Mylar repo, I copied my `cache`, `config.ini`, and `mylar.db` files. I updated the `logs` and `cache` lines in the config file to point to the new Mylar3 directory.

`pip3` didn't want to work for me, even after installing `python3-pip`, so I ran `python3 -m pip install -r requirements.txt`, though it doesn't even seem to be getting to the point of trying to start the app

Starting the service seems to get hung up. Here is the output from `journalctl -xe`:
```
Mar 19 17:37:12 <server> systemd[1]: Starting starts instance of Mylar...
-- Subject: Unit mylar.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit mylar.service has begun starting up.
```

Service file:
```
# Mylar.service to run as $USER with config in $DATA_DIR

[Unit]
SourcePath=/etc/init.d/mylar
Description=starts instance of Mylar
After=all.target

[Service]
Type=forking
Restart=no
TimeoutSec=5min
IgnoreSIGPIPE=no
KillMode=process
GuessMainPID=no
RemainAfterExit=yes
ExecStart=/etc/init.d/mylar start
ExecStop=/etc/init.d/mylar stop

[Install]
WantedBy=multi-user.target
```

Defaults:
```
MYLAR_USER=<redacted>
MYLAR_HOME=/<some_dir>/mylar3
MYLAR_DATA=/<some_dir>/mylar3
PYTHON_BIN=/usr/bin/python3
```

If I run `python3 Mylar.py`, I get the following:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/jaraco/text/__init__.py", line 11, in <module>
    from importlib import resources
ImportError: cannot import name 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/importlib_resources/_compat.py", line 39, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar3/mylar/__init__.py", line 36, in <module>
    import cherrypy
  File "~/.local/lib/python3.6/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "~/.local/lib/python3.6/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "~/.local/lib/python3.6/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "~/.local/lib/python3.6/site-packages/jaraco/collections.py", line 9, in <module>
    import jaraco.text
  File "~/.local/lib/python3.6/site-packages/jaraco/text/__init__.py", line 13, in <module>
    import importlib_resources as resources
  File "~/.local/lib/python3.6/site-packages/importlib_resources/__init__.py", line 5, in <module>
    from ._compat import metadata
  File "~/.local/lib/python3.6/site-packages/importlib_resources/_compat.py", line 41, in <module>
    import importlib_metadata as metadata  # type: ignore
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 591, in <module>
    __version__ = version(__name__)
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 553, in version
    return distribution(distribution_name).version
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 253, in version
    return self.metadata['Version']
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 241, in metadata
    self.read_text('METADATA')
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 513, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Comment by evilhero** [comment]
Try removing the use of the default stuff (systemd doesn't need to call init.d for anything, it's a holdover from previous OS versions).

Remove the ExexStop line and change your ExecStart so that it executes mylar directly with the necessary switches needed. This is an example:
```
[Service]
Type=forking
User=username
Group=username
ExecStart=/usr/bin/python3 /opt/mylar/Mylar.py --daemon --datadir=/opt/mylar --config=/opt/mylar/config.ini --nolaunch
GuessMainPID=no
```

The datadir and config switches are optional, just make sure you point them to the correct locations if you do use them.

**Comment by Serneum** [comment]
That didn't seem to solve the issue. Nothing is showing up in the `journalctl` log that stands out to me now. Is it due to the errors I'm seeing when trying to run Mylar manually?

```
Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/jaraco/text/__init__.py", line 11, in <module>
    from importlib import resources
ImportError: cannot import name 'resources'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.6/site-packages/importlib_resources/_compat.py", line 39, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar3/mylar/__init__.py", line 36, in <module>
    import cherrypy
  File "~/.local/lib/python3.6/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "~/.local/lib/python3.6/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "~/.local/lib/python3.6/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "~/.local/lib/python3.6/site-packages/jaraco/collections.py", line 9, in <module>
    import jaraco.text
  File "~/.local/lib/python3.6/site-packages/jaraco/text/__init__.py", line 13, in <module>
    import importlib_resources as resources
  File "~/.local/lib/python3.6/site-packages/importlib_resources/__init__.py", line 5, in <module>
    from ._compat import metadata
  File "~/.local/lib/python3.6/site-packages/importlib_resources/_compat.py", line 41, in <module>
    import importlib_metadata as metadata  # type: ignore
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 591, in <module>
    __version__ = version(__name__)
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 553, in version
    return distribution(distribution_name).version
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 253, in version
    return self.metadata['Version']
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 241, in metadata
    self.read_text('METADATA')
  File "~/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 513, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Comment by evilhero** [comment]
Python3.6 isn't supported. You should be running at a minimum 3.7.5 or the most recent 3.8 version (3.7 'might' work, but hasn't been tested). You'll have to reinstall the pip too once you've upgraded python.

Pyenv is a great tool for being able to install various versions of python at the same time.

**Comment by Serneum** [comment]
No worries. I got 3.7 installed through `apt-get` on Ubuntu to verify that everything works. It's not pretty, but it works. I'll look into Pyenv shortly, thanks!
