### ISSUE TITLE
Impossible to start after migration

### ISSUE THREAD

**Issue by judzk** [mylar3/mylar3#239]
**Describe the bug**
Hi, i just migrate from mylar2 and it's impossible to start mylar3

**CarePackage**

`01-avril-2020 18:28:21 - INFO :: MainThread : filechecker.py:validateAndCreateDirectory:1710 : [DIRECTORY-CHECK] Found comic directory: /mnt/comics
Error in sys.excepthook:
TypeError: handle_exception() missing 1 required positional argument: 'exc_traceback'

Original exception was:
Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/opt/mylar3/mylar/__init__.py", line 260, in initialize
    helpers.updateComicLocation()
  File "/opt/mylar3/mylar/helpers.py", line 889, in updateComicLocation
    com_done = re.sub('%&', os.sep.encode('unicode-escape'), comlocation).strip()
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: sequence item 0: expected str instance, bytes found
`

**Environment (please complete the following information):**
 - OS: Debian 10
 - Branch / commit: the last one

**Additional information**
Add any other information about the problem here.

**Comment by evilhero** [comment]
We need full debug logs, do not paste in just the error message.

Also:
- specify specific version of python
- the commit of mylar you are running and the branch (not just last one)
- source or git install

**Comment by barbequesauce** [comment]
In this case I'd also ask what locale you're running under, in addition to OS/branch/commit/python version/git vs src

**Comment by barbequesauce** [comment]
Closing due to inactivity - please feel free to reopen if this is still a problem.
