### ISSUE TITLE
Can't start Mylar3 after changing webui port

### ISSUE THREAD

**Issue by seannymurrs** [mylar3/mylar3#252]
I had to change the webui port for Mylar. Afterwards, when I went to start it back up again, it wouldn't start. Attached is the full output from when I attempt to start it. I attempted to paste the output into this post, but I couldn't get the formatting correct.
[mylar-verbose.txt](https://github.com/mylar3/mylar3/files/4467377/mylar-verbose.txt)

**Comment by barbequesauce** [comment]
That’s .... odd.

What OS? What version of python? What does `pip freeze` output?

**Comment by seannymurrs** [comment]
The os is Gentoo. It's actually running on my seedbox from Whatbox.ca. Python is version 3.7.7. When I run `pip freeze` I get the following:

`adba==1.1.0
altgraph==0.17
appdirs==1.4.3
APScheduler==3.6.3
attrs==18.2.0
babelfish==0.5.6.dev0
beautifulsoup4==4.8.2
bencode.py==2.1.0
boto==2.48.0
CacheControl==0.12.6
certifi==2019.11.28
cffi==1.14.0
cfscrape==2.1.1
chardet==3.0.4
cheroot==8.2.1
CherryPy==18.5.0
click==7.1.1
cloudscraper==1.2.30
configobj==5.0.6
configparser==5.0.0
contextlib2==0.6.0.post1
decorator==4.4.2
deluge-client==1.8.0
Deprecated==1.2.9
dirtyjson==1.0.7
diskcache==2.9.0
dogpile.cache==0.9.0
enzyme==0.4.2.dev0
feedparser==5.2.1
future==0.18.2
gntp==1.0.3
guessit==3.1.0
html5lib==1.0.1
idna==2.9
imdbpie==5.6.4
jaraco.classes==3.1.0
jaraco.collections==3.0.0
jaraco.functools==3.0.0
jaraco.text==3.2.0
jsonrpclib-pelix==0.4.0
knowit==0.3.0.dev0
Mako==1.1.2
markdown2==2.3.8
MarkupSafe==1.1.1
more-itertools==8.2.0
msgpack==1.0.0
natsort==7.0.1
oauthlib==3.1.0
pbr==5.4.5
Pillow==6.2.2
Pint==0.11
portend==2.6
profilehooks==1.11.2
pycparser==2.20
PyGithub==1.45
PyInstaller==3.6
PyJWT==1.7.1
pymediainfo==4.1
pysrt==1.1.2
python-dateutil==2.8.1
python-twitter==3.5
pytz==2019.3
PyYAML==5.3.1
rarfile==3.1
rebulk==2.0.0
requests==2.23.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
sgmllib3k==1.0.0
simplejson==3.17.0
six==1.14.0
soupsieve==2.0
stevedore==1.32.0
subliminal==2.1.0.dev0
tempora==3.0.0
tornado==5.1.1
tornroutes==0.5.1
trans==2.1.0
tvdbapiv2==1.0.1
tzlocal==2.0.0
unrar==0.4
unrar-cffi==0.1.0a5
urllib3==1.25.8
validators==0.14.2
webencodings==0.5.1
wrapt==1.12.1
zc.lockfile==2.0`

**Comment by evilhero** [comment]
When you start mylar, you have the ```-v``` switch in the wrong place. It's supposed to come after mylar.py, not after the python command (ie. ```python Mylar.py -v``` and not ```python -v Mylar.py```

**Comment by seannymurrs** [comment]
When I run `python3.7 Mylar.py -v` I only get the following output:

`Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/mnt/mpathd/seannymurrs/mylar3/mylar/__init__.py", line 38, in <module>
    from mylar import logger, versioncheckit, rsscheckit, searchit, weeklypullit, PostProcessor, updater, helpers
  File "/mnt/mpathd/seannymurrs/mylar3/mylar/rsscheckit.py", line 21, in <module>
    from mylar import logger, rsscheck, helpers, auth32p
  File "/mnt/mpathd/seannymurrs/mylar3/mylar/rsscheck.py", line 52, in <module>
    feedparser._FeedParserMixin._start_newznab_attr = _start_newznab_attr
AttributeError: module 'feedparser' has no attribute '_FeedParserMixin'`

**Comment by evilhero** [comment]
You ran pip against the wrong  version of python most likely. In order to get the requirements.txt to pull against 3.7.7 you need to initiate pip with pip3.7, and not just pip (as that's probably tied to a different version of python)

**Comment by seannymurrs** [comment]
> You ran pip against the wrong version of python most likely. In order to get the requirements.txt to pull against 3.7.7 you need to initiate pip with pip3.7, and not just pip (as that's probably tied to a different version of python)

I know that's not the case because that was the issue when I originally installed Mylar. I got that sorted out earlier. Literally, the only thing I changed was the webui port and then I tried to launch it again using the exact same command I did last time.

**Comment by evilhero** [comment]
Don't know what else to say. That's pretty much what that error is implying (right up to the -v in the wrong spot). That or you didn't run it previously with the python3.7 command and instead used just python. Changing the web port wouldn't spit back a feed parser error requirement unless something else got changed outside of mylar (ie. installing something else that hammered our requirements) . 

If you run ```pip3.7 freeze``` does it give a different listing back than previous?

**Comment by seannymurrs** [comment]
`pip3.7 freeze` produces this output:

`adba==1.1.0
altgraph==0.17
appdirs==1.4.3
APScheduler==3.6.3
attrs==18.2.0
babelfish==0.5.6.dev0
beautifulsoup4==4.8.2
bencode.py==2.1.0
boto==2.48.0
CacheControl==0.12.6
certifi==2019.11.28
cffi==1.14.0
cfscrape==2.1.1
chardet==3.0.4
cheroot==8.2.1
CherryPy==18.5.0
click==7.1.1
cloudscraper==1.2.30
configobj==5.0.6
configparser==5.0.0
contextlib2==0.6.0.post1
decorator==4.4.2
deluge-client==1.8.0
Deprecated==1.2.9
dirtyjson==1.0.7
diskcache==2.9.0
dogpile.cache==0.9.0
enzyme==0.4.2.dev0
feedparser==5.2.1
future==0.18.2
gntp==1.0.3
guessit==3.1.0
html5lib==1.0.1
idna==2.9
imdbpie==5.6.4
jaraco.classes==3.1.0
jaraco.collections==3.0.0
jaraco.functools==3.0.0
jaraco.text==3.2.0
jsonrpclib-pelix==0.4.0
knowit==0.3.0.dev0
Mako==1.1.2
markdown2==2.3.8
MarkupSafe==1.1.1
more-itertools==8.2.0
msgpack==1.0.0
natsort==7.0.1
oauthlib==3.1.0
pbr==5.4.5
Pillow==6.2.2
Pint==0.11
portend==2.6
profilehooks==1.11.2
pycparser==2.20
PyGithub==1.45
PyInstaller==3.6
PyJWT==1.7.1
pymediainfo==4.1
pysrt==1.1.2
python-dateutil==2.8.1
python-twitter==3.5
pytz==2019.3
PyYAML==5.3.1
rarfile==3.1
rebulk==2.0.0
requests==2.23.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
sgmllib3k==1.0.0
simplejson==3.17.0
six==1.14.0
soupsieve==2.0
stevedore==1.32.0
subliminal==2.1.0.dev0
tempora==3.0.0
tornado==5.1.1
tornroutes==0.5.1
trans==2.1.0
tvdbapiv2==1.0.1
tzlocal==2.0.0
unrar==0.4
unrar-cffi==0.1.0a5
urllib3==1.25.8
validators==0.14.2
webencodings==0.5.1
wrapt==1.12.1
zc.lockfile==2.0
seannymurrs@discove `

**Comment by evilhero** [comment]
Did you install feedparser outside of pip by chance when you encountered that error previously? That error has been documented in other github repos as having conflicting feedparser versions - basically it's loading the other version and not the version that it's installed via pip. Or do you have a feedparser.py file in either the root of the mylar directory or the mylar/lib folder ?

**Comment by barbequesauce** [comment]
@seannymurrs wondering if you had feedback on evilhero's question above?

**Comment by barbequesauce** [comment]
Closing due to inactivity - please feel free to open a fresh issue and reference this if you're still having the issue.
