### ISSUE TITLE
RSS feeds TypeError

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#28]
```
Job "RSS Feeds (trigger: interval[0:30:00], next run at: 2020-01-15 20:45:07 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/mylar.py3/mylar/rsscheckit.py", line 99, in run
    mylar.search.searchforissue(rsscheck='yes')
  File "/opt/mylar.py3/mylar/search.py", line 1761, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), SeriesYear, Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=result['SARC'], IssueArcID=result['IssueArcID'], mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=Comicname_filesafe, allow_packs=AllowPacks, oneoff=OneOff, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 339, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="yes", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, digitaldate=digitaldate, booktype=booktype)
  File "/opt/mylar.py3/mylar/search.py", line 1392, in NZB_SEARCH
    if int(intIss) == int(comintIss) or all([cmloopit == 4, findcomiciss is None, pc_in is None]) or all([cmloopit == 4, findcomiciss is None, pc_in == 1]):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Full log attached - weirdly the traceback only appears when running from command line, not in the debug (but occurred immediately after the last line in the log)
[mylar.log](https://github.com/mylar3/mylar3/files/4067345/mylar.log)

**Comment by barbequesauce** [comment]
Bah duplicate of #7

**Comment by barbequesauce** [comment]
not a dupe per the boss

**Comment by barbequesauce** [comment]
Cant reproduce.
