### ISSUE TITLE
Library import: NameError: name 'ckh' is not defined

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#29]
```
15-Jan-2020 16:51:09 - INFO :: mylar.libraryScan.47 : LibraryScan : Scanning comic directory: /mnt/whitecliff/comics/The Wild Storm (2017)
15-Jan-2020 16:51:09 - ERROR :: mylar.scanLibrary.629 : LibraryScan : [IMPORT] Unable to complete the scan: endswith first arg must be bytes or a tuple of bytes, not str
[15/Jan/2020:16:51:09] HTTP 
Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 250, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 163, in find_acceptable_charset
    if encoder(encoding):
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 112, in encode_string
    for chunk in self.body:
  File "/opt/mylar.py3/mylar/webserve.py", line 4278, in ThreadcomicScan
    yield ckh[0]['result']
NameError: name 'ckh' is not defined
```

**Comment by barbequesauce** [comment]
Doesn't seem to save the scan config either, FWIW

**Comment by barbequesauce** [comment]
librarysync.py, line 6 - added b before quotes... then got this

```
an : Scanning comic directory: /mnt/whitecliff/comics/The Wild Storm (2017)
15-Jan-2020 18:53:56 - ERROR :: mylar.scanLibrary.629 : LibraryScan : [IMPORT] Unable to complete the scan: can't concat str to bytes
[15/Jan/2020:18:53:56] HTTP 
Traceback (most recent call last):
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 250, in __call__
    ct.params['charset'] = self.find_acceptable_charset()
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 163, in find_acceptable_charset
    if encoder(encoding):
  File "/home/mylar3/.local/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 112, in encode_string
    for chunk in self.body:
  File "/opt/mylar.py3/mylar/webserve.py", line 4280, in ThreadcomicScan
    yield ckh[0]['result']
NameError: name 'ckh' is not defined
```
