### ISSUE TITLE
Traceback on many issues when doing Import

### ISSUE THREAD

**Issue by bguidotti** [mylar3/mylar3#337]
Hi. I'm on the development branch of Mylar3, running on Win10 with Python 3.7.7.
I'm trying to do a mass import of a bunch of files that a duplicate removal program left hanging out in a miscellaneous directory. In other words, they used to be in the correct series folders, but now are in a single folder.
The importer works on some files, but pukes out pretty quickly for me if I try to set it and walk away.
I'm hoping some of my filenames will help improve it.

I turned on debug logging and did a carepackage after I tried an import again.
I can get that file to you through Google Drive.

**Here is a sample:**
06-Jun-2020 22:29:09 - DEBUG :: mylar.preSearchit.4806 : Thread-24 : search_values: [{'SRID': '347271', 'comicid': '94624'}]/{'Series': 'Enchanted Tiki Room', 'results': 2, 'publisher': 'Marvel', 'haveit': {'comicid': '94624', 'status': 'Active'}, 'name': 'Enchanted Tiki Room', 'deck': 'None', 'url': 'https://comicvine.gamespot.com/enchanted-tiki-room/4050-94624/', 'description': '<p>Five issue mini-series.</p><p>Collected in <a href="https://comicvine.gamespot.com/enchanted-tiki-room/4050-100693/" data-ref-id="4050-100693">Enchanted Tiki Room</a>.</p>', 'comicimage': 'https://comicvine1.cbsistatic.com/uploads/scale_large/6/67663/5467806-01.jpg', 'issues': '5', 'ogcname': 'Enchanted Tiki Room', 'comicyear': '2016'}
06-Jun-2020 22:29:09 - ERROR :: mylar.excepthook.315 : Thread-24 : Uncaught exception: Traceback (most recent call last):
  File "C:\mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\Bruce\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mylar3\mylar\webserve.py", line 4807, in preSearchit
    myDB.upsert("searchresults", nVal, cVal)
  File "C:\mylar3\mylar\db.py", line 169, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "C:\mylar3\mylar\db.py", line 128, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.

Traceback (most recent call last):
  File "C:\mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\Bruce\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\mylar3\mylar\webserve.py", line 4807, in preSearchit
    myDB.upsert("searchresults", nVal, cVal)
  File "C:\mylar3\mylar\db.py", line 169, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "C:\mylar3\mylar\db.py", line 128, in action
    sqlResult = self.connection.execute(query, args)
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.

**Comment by bguidotti** [comment]
https://drive.google.com/file/d/1nXAs6VzkHbb2Yt0xtQLOg9gajUk0c9AK/view?usp=sharing

**Comment by barbequesauce** [comment]
Related to #149

**Comment by barbequesauce** [comment]
Closing due to staleness, we welcome contributions for new features. If this is an issue and you are still experiencing it, please open a new ticket with a care package attached.

**Comment by barbequesauce** [comment]
Closing due to staleness, we welcome contributions for new features. If this is an issue and you are still experiencing it, please open a new ticket with a care package attached.
