### ISSUE TITLE
Unable to grab torrents

### ISSUE THREAD

**Issue by ahoytoy** [mylar3/mylar3#390]
So I set up all the API, torrent client, and tracker for my mylar, but when making requests for comics, it doesn't pull anything from my tracker.  Is there something I can do to fix this?

**Comment by barbequesauce** [comment]
On  the config page, please click the "care package" button; it will zip up logs, config file, and the database so we can help diagnose...

**Comment by ahoytoy** [comment]
Hello,

So I Clicked on care package and got the following

> Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 916, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.7/collections/__init__.py", line 908, in __missing__
    raise KeyError(key)
KeyError: 'torznab_host'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/user1/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/user1/.local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/user1/.local/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 5780, in carepackage
    cp = carePackage()
  File "/opt/mylar/mylar/carepackage.py", line 86, in __init__
    self.cleaned_config()
  File "/opt/mylar/mylar/carepackage.py", line 169, in cleaned_config
    hkey = tmpconfig.get(h[0], h[1])
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'torznab_host' in section: 'Torznab'

**Comment by barbequesauce** [comment]
yep, something serious wrong in that config. Can you manually redact API keys and post it to a pastebin please? Also debug logs from a startup (`python3 Mylar.py -v`)

**Comment by ahoytoy** [comment]
I'll log onto irc to see if I can discuss

**Comment by ahoytoy** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4893726/carepackage.zip)
ok did a reinstall.  

I've set up the api, etc.  However, now the added comics are listed as none on all fields. This time though, was able to pull package

**Comment by ahoytoy** [comment]
[carepackage (1).zip](https://github.com/mylar3/mylar3/files/4894007/carepackage.1.zip)

**Comment by ahoytoy** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4894011/carepackage.zip)

**Comment by ahoytoy** [comment]
gonna close the issue,  basically mylar won't work with manga since naming conventions are weird. props to evilhero for taking time to help out in any case!
