### ISSUE TITLE
Post Processing fails after completion of 1st queue item

### ISSUE THREAD

**Issue by kmccormi** [mylar3/mylar3#395]
I migrated from Mylar to Mylar3 and copied the config/db/cache files across, but launch failed until I started with a clean config.ini. Then I rebuilt the previous settings and all is working except after a file is grabbed and downloaded it will post-process as expected but then throw an error that halts further post-processing, regardless of file provider and cache/destination folder. 

I am running Python 3.7.8 and Python 2.7 concurrently on my Win 10 machine and am on the python3-dev branch with latest commit: d6c3cdabe

[carepackage (1).zip](https://github.com/mylar3/mylar3/files/4922740/carepackage.1.zip)

**Comment by barbequesauce** [comment]
Check your path definitions. If it's Windows, you should have backslashes not forward slashes like on Linux...

`INFO    :: mylar.validateAndCreateDirectory.1717 : Thread-18 : [WEEKLY-PULL COPY][DIRECTORY-CHECK] Found comic directory: H:/Comics/Downloads\`

**Comment by kmccormi** [comment]
Not sure why the paths were like that - but I used the locmove method in the config file to update all paths for all comics directories, which was successful. I then restarted and grabbed the previously snatched downloads again and the result is the same, first one works and then it throws the same error. My updated care package is attached.
[carepackage (2).zip](https://github.com/mylar3/mylar3/files/4936959/carepackage.2.zip)

**Comment by evilhero** [comment]
You still need to update any windows paths in your config.ini to point to the new location. Your ini has a few still set to windows paths, so it won't resolve properly. Most important one is the destination_dir in the ini - having that set incorrectly will cause problems, as that's telling Mylar what your base path is. 

The locmove option will not convert your ini paths, it just updates the paths within the db for your series.

**Comment by kmccormi** [comment]
Not sure what else I can update - I checked the ini again a few times, including searching for the '/' character and I can only find correct paths, e.g. the destination_dir value is "H:\Comics\Downloads". I checked the logs and it lists the paths for all series folders as "H:/Comics/Downloads\Comic Name". I've tried refreshing all series. I checked manually in the series config pages (Edit Settings) and it list the path as "H:\Comics\Downloads\Comic Name" as expected.

**Comment by barbequesauce** [comment]
Good news, it looks like your pathing is correct now. That said, there's something else broken - I think I have what i need to dig deeper, more to come.

```
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - INFO    :: mylar.Process_next.2645 : Thread-19 : [POST-PROCESSING] move successful to : H:\Comics\Downloads\Strange Adventures (2-REDACTED-2-REDACTED-)\Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbz
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.243 : Thread-19 : File Option: move [META-ENABLED: True]
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.244 : Thread-19 : odir: C:\Mylar\cache\mylar_xcbvkubx [filename: Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbr][self.nzb_folder: C:\Mylar\cache\Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbr]
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.245 : Thread-19 : sub_path: C:\Mylar\cache [cacheonly: False][del_nzbdir: True]
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.252 : Thread-19 : Direct post-processing was performed against specific issueid. Using supplied filepath for deletion.
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.264 : Thread-19 : [POST-PROCESSING] item to be deleted is file, not folder due to direct submission: C:\Mylar\cache\Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbr
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.316 : Thread-19 : [POST-PROCESSING] Attempting to remove file: C:\Mylar\cache\Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbr
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - ERROR   :: mylar.tidyup.333 : Thread-19 : [POST-PROCESSING] C:\Mylar\cache not empty. Skipping removal of directory - this will either be caught in further post-processing or it will have to be manually deleted.
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.tidyup.348 : Thread-19 : [POST-PROCESSING] Tidying up. Deleting temporary cache directory : C:\Mylar\cache\mylar_xcbvkubx
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.totals.1626 : Thread-19 : totalfiles: 3
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.totals.1627 : Thread-19 : status: Snatched
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.totals.164-REDACTED- : Thread-19 : incremented havefiles: 3
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.foundsearch.717 : Thread-19 : [POST-PROCESSING][UPDATER] comicid: 125426
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - DEBUG   :: mylar.foundsearch.718 : Thread-19 : [POST-PROCESSING][UPDATER] issueid: 778249
17-Jul-2-REDACTED-2-REDACTED- 17:39:26 - INFO    :: mylar.foundsearch.856 : Thread-19 : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
17-Jul-2-REDACTED-2-REDACTED- 17:39:27 - INFO    :: mylar.foundsearch.913 : Thread-19 : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now completed for Strange Adventures issue: 3
17-Jul-2-REDACTED-2-REDACTED- 17:39:27 - DEBUG   :: mylar.Process_next.2688 : Thread-19 : [annchk:no] issue to update: #3
17-Jul-2-REDACTED-2-REDACTED- 17:39:27 - DEBUG   :: mylar.Process_next.2695 : Thread-19 : writing: {'Status': 'Downloaded', 'Location': 'Strange Adventures -REDACTED-3 (of 12) (2-REDACTED-2-REDACTED-) (digital) (Son of Ultron-Empire).cbz'} -- {'IssueID': '778249'}
17-Jul-2-REDACTED-2-REDACTED- 17:39:27 - INFO    :: mylar.weekly_check.1314 : Thread-19 : [POST-PROCESSING][WEEKLY-PULL] Issue found on weekly pull-list.
17-Jul-2-REDACTED-2-REDACTED- 17:39:27 - INFO    :: mylar.validateAndCreateDirectory.1717 : Thread-19 : [WEEKLY-PULL COPY][DIRECTORY-CHECK] Found comic directory: H:\Comics\Downloads\2-REDACTED-2-REDACTED---REDACTED-7-15
17-Jul-2-REDACTED-2-REDACTED- 17:39:29 - ERROR   :: mylar.excepthook.315 : Thread-19 : Uncaught exception: Traceback (most recent call last):
  File "C:\Mylar\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Python\Python37\lib\threading.py", line 87-REDACTED-, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Mylar\mylar\PostProcessor.py", line 1688, in Process
    self.Process_next(comicid, issueid, issuenumOG, ml, stat)
  File "C:\Mylar\mylar\PostProcessor.py", line 2769, in Process_next
    weeklypull.weekly_check(comicid, issuenum, file=(nfilename +ext), path=dst, module=module, issueid=issueid)
  File "C:\Mylar\mylar\weeklypull.py", line 1319, in weekly_check
    weekly_singlecopy(comicid, issuenum, file, path, weekinfo)
  File "C:\Mylar\mylar\weeklypull.py", line 1347, in weekly_singlecopy
    logger.info(module + ' Sucessfully copied to ' + desfile.encode('utf-8').strip())
TypeError: can only concatenate str (not "bytes") to str
```

While I was poking around the care package, I'd noted this concerning bit - you might need to reinstall...

```
Mylar git status:
git version 2.17.1.windows.2

On branch python3-dev
Your branch is up to date with 'origin/python3-dev'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    Mylar.py
```

**Comment by kmccormi** [comment]
Thanks for checking the paths. That git status 'deleted' item is just me changing the mylar.py to mylar.pyw to run without console. I've always run it that way in the past, though perhaps mylar3 (or python 3) has issues with that.

**Comment by kmccormi** [comment]
I tested your fix by editing the weeklypull.py file and it worked! Thank you🙂
