### ISSUE TITLE
Mass Import fails with DataTables popup

### ISSUE THREAD

**Issue by JPNYC81** [mylar3/mylar3#403]
Attempting to import, all actions are met with this popup error.

Error:
DataTables warning: table id=impresults_table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

Goes bad here in log:
26-Jul-2020 22:22:52 - DEBUG   :: mylar.preSearchit.4571 : Thread-12 : [IMPORT] [!none] dynamicname: astrocity
26-Jul-2020 22:22:52 - DEBUG   :: mylar.preSearchit.4572 : Thread-12 : [IMPORT] [!none] volume: v01
26-Jul-2020 22:22:52 - ERROR   :: mylar.excepthook.315 : Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar/webserve.py", line 4622, in preSearchit
    if 'annual' in getiss.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by barbequesauce** [comment]
Whats the full filename it's dying on?

**Comment by JPNYC81** [comment]
Happens with any files.
/import/Analog (2018)/Analog 001 (2018) (Digital) (Zone-Empire).cbr
/import/Chew (2009)/Chew 001 (2009) (digital) (Minutemen-Spaztastic).cbr
/import/Lazarus (2013)/Lazarus 001 (2013) (Digital) (Vee-Empire).cbr 

Flushing and attempting again results in this error:
DataTables warning: table id=impresults_table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

**Comment by evilhero** [comment]
Odds are it's not those filenames you just pasted, as those would import just fine under normal circumstances.
The problem is that with the traceback, it's indicating that there is no issue number found in the filename, and unfortunately it dies at that point. The importer, in its current iteration, will jot be able to import GNs, TPB's, or Compendiums - so basically anything that does not have an issue number present in the filename. Performing a mass import on such titles will result in the above error.

The importer has been going thru an update process for the last little while, albeit not publicly. TPB's, GNs, et all will be able to be scanned in properly (hopefully) in the update, as then it will have caught up to the other modules which can handle those items (searching, post-processing, file-checking, etc). 

Until the new code gets into the existing base, your best bet is to either remove those files with no issue # from your import scan location, or do a selection of items from the import results management page and manually import them via the dropdown (or via the individual option). 

Yeah, it sucks - but the mass importer is flaky at best in its current state and you'll probably run into more of these types of problems with it vs doing it in small batches.

**Comment by Dude77777** [comment]
Hi @evilhero, @ahknight and team, I was searching the issues for an error I am also getting doing mass import, it looks very similar to the above. I understand that you are currently redeveloping the mass importer to be more robust.

10-Nov-2022 07:51:54 - INFO    :: mylar.preSearchit.5934 : Thread-23 (preSearchit) : [IMPORT][01 - Metamorphosis Odyssey (v1)] Now preparing to import. First I need to determine the highest issue, and possible year(s) of the series.
10-Nov-2022 07:51:54 - ERROR   :: mylar.excepthook.315 : Thread-23 (preSearchit) : Uncaught exception: Traceback (most recent call last):
  File "A:\DL\Z mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "C:\Users\micha\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "A:\DL\Z mylar3\mylar\webserve.py", line 5992, in preSearchit
    if 'annual' in getiss.lower():
AttributeError: 'NoneType' object has no attribute 'lower'

10-Nov-2022 07:56:50 - INFO    :: mylar.run.3503 : ThreadPoolExecutor-0_0 : [FOLDER-CHECK] Checking folder A:\COMICS TBS\- Mylar folder based monitor for newly snatched downloads

Equally the mass import crashes likewise. Am I right in saying I have to remove the file it's trying to access? I had checked and made sure all mass import files are CR tagged, so just wondering why it fails on the filename? How would I filter these types of files out via search?

**Comment by barbequesauce** [comment]
Closing due to staleness, we welcome contributions for new features. If this is an issue and you are still experiencing it, please open a new ticket with a care package attached.
