### ISSUE TITLE
problem with unrar on windows

### ISSUE THREAD

**Issue by HypKin** [mylar3/mylar3#404]
**Describe the bug**
when i try to open a cbr (.rar) file in the reader or view the issue details I'm getting a 500 internal server error. no issue with cbz (zip) files, also it seems i do have a corrosponding problem with the opds stream. 

seems to be a problem with unrar on windows. 

**CarePackage**
not possible, getting a 500 internal server error ;)

**Environment (please complete the following information):**
 - OS: Win 10
 - Dev
- installed unrar

**Additional information**
trying to open a cbr in the reader i get the following error:

`Traceback (most recent call last):
  File "D:\mylar3\lib\rarfile\rarfile.py", line 2870, in custom_popen
    creationflags=creationflags)
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\mylar3\mylar\webserve.py", line 6779, in read_comic
    data = wv.read_comic(ish_id, page_num, size)
  File "D:\mylar3\mylar\webviewer.py", line 74, in read_comic
    scanner.user_unpack_comic(ish_id, comic_path)
  File "D:\mylar3\mylar\webviewer.py", line 142, in user_unpack_comic
    opened_rar.extractall(os.path.join(mylar.CONFIG.CACHE_DIR, "webviewer", ish_id))
  File "D:\mylar3\lib\rarfile\rarfile.py", line 829, in extractall
    self._extract(fnlist, path, pwd)
  File "D:\mylar3\lib\rarfile\rarfile.py", line 894, in _extract
    p = custom_popen(cmd)
  File "D:\mylar3\lib\rarfile\rarfile.py", line 2873, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
lib.rarfile.rarfile.RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
Powered by CherryPy 18.6.0`

***************************

i installed the windows version of unrar and pointed the .comictagger/settings file to the exe path

"C:\Program Files (x86)\UNRAR\UNRAR.exe"

but it seems that this isn't enough, do i need to do something else to get it to work?

**Comment by evilhero** [comment]
In your ```config.ini``` - check to see that the field under [Metatagging] called ```ct_settingspath``` is pointing to the correct location to your settings file (ie. it should be something along the lines of ```D:\mylar3\.ComicTagger``` - note that you don't actually put in the filename of settings as that can't be changed).

If you have more than one ```ct_settingspath``` variable in your config.ini, that will cause a problem too. The correct one should be under [Metatagging], if you have one under [General] delete that entire reference from the file.

**Comment by HypKin** [comment]
I've tried a few things in the last days but nothing worked, i'll try a few more things, and will hopefully be able to resolve this ;)

**Comment by barbequesauce** [comment]
Any news here?
