### ISSUE TITLE
Unknown version - can't update

### ISSUE THREAD

**Issue by dma9** [mylar3/mylar3#405]
**Describe the bug**
I've just updated from mylar to mylar3 using the instructions on the project homepage. Everything seemed to go fine but when I went into the WebGUI it says I'm running an unknown version. When I try to update it goes to the update page, but then nothing changes and I still get the same message.

**CarePackage**
Unfortunately when I try generating a care package I get the following error:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar3/mylar/webserve.py", line 5780, in carepackage
    NZBGet_test.exposed = True
  File "/opt/mylar3/mylar/carepackage.py", line 85, in __init__
    self.environment()
  File "/opt/mylar3/mylar/carepackage.py", line 101, in environment
    text=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
There seem to be some errors in the log:

```
30-Jul-2020 17:58:15 - INFO    :: mylar.configure.1015 : MainThread : [COMICTAGGER] Version detected: 1.3.3
30-Jul-2020 17:58:15 - INFO    :: mylar.configure.1080 : MainThread : Setting DDL Location set to : /opt/mylar3/cache
30-Jul-2020 17:58:15 - INFO    :: mylar.initialize.188 : MainThread : Checking to see if the database has all tables....
30-Jul-2020 17:58:15 - INFO    :: mylar.dbcheck.1325 : MainThread : Ensuring DB integrity - Removing all Erroneous Comics (ie. named None)
30-Jul-2020 17:58:15 - INFO    :: mylar.dbcheck.1327 : MainThread : Correcting Null entries that make the main page break on startup.
30-Jul-2020 17:58:15 - INFO    :: mylar.initialize.202 : MainThread : Successfully discovered local IP and locking it in as : 10.0.20.33
30-Jul-2020 17:58:15 - INFO    :: mylar.initialize.264 : MainThread : Remapping the sorting to allow for new additions.
30-Jul-2020 17:58:15 - INFO    :: mylar.ComicSort.761 : MainThread : Sucessfully ordered 3826 series in your watchlist.
30-Jul-2020 17:58:15 - INFO    :: mylar.validateAndCreateDirectory.1717 : MainThread : [DIRECTORY-CHECK] Found comic directory: /opt/mylar3
30-Jul-2020 17:58:15 - INFO    :: mylar.initialize.73 : MAIN : Starting Mylar on http://0.0.0.0:8090/
30-Jul-2020 17:58:15 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 17:58:15 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:05:40 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:05:40 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:06:12 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-8 : Error not an encryption that I recognize.
30-Jul-2020 18:07:21 - WARNING :: mylar.checkGithub.253 : CP Server Thread-11 : [ERROR] Could not get the latest commit from github: 'sha'
30-Jul-2020 18:11:32 - ERROR   :: mylar.runGit.49 : CP Server Thread-4 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:13:42 - ERROR   :: mylar.runGit.49 : CP Server Thread-10 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:14:28 - ERROR   :: mylar.runGit.49 : CP Server Thread-10 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:17:04 - ERROR   :: mylar.runGit.49 : CP Server Thread-2 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:22:47 - ERROR   :: mylar.runGit.49 : MAIN : Command https://github.com/mylar3/mylar3 describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:22:47 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:22:47 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:23:08 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-8 : Error not an encryption that I recognize.
30-Jul-2020 18:23:13 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-9 : Error not an encryption that I recognize.
30-Jul-2020 18:23:20 - ERROR   :: mylar.runGit.49 : CP Server Thread-5 : Command https://github.com/mylar3/mylar3 log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:23:20 - ERROR   :: mylar.runGit.49 : CP Server Thread-5 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:29:17 - ERROR   :: mylar.runGit.49 : CP Server Thread-8 : Command https://github.com/mylar3/mylar3 log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:29:17 - ERROR   :: mylar.runGit.49 : CP Server Thread-8 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:29:38 - ERROR   :: mylar.runGit.49 : MAIN : Command https://github.com/mylar3/mylar3 describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:29:38 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:29:38 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:30:08 - ERROR   :: mylar.runGit.49 : MAIN : Command https://github.com/mylar3/mylar3 describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:30:08 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:30:08 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:32:07 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-9 : Error not an encryption that I recognize.
30-Jul-2020 18:32:41 - ERROR   :: mylar.runGit.49 : CP Server Thread-6 : Command https://github.com/mylar3/mylar3 log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:32:41 - ERROR   :: mylar.runGit.49 : CP Server Thread-6 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:35:41 - ERROR   :: mylar.runGit.49 : MAIN : Command /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:35:41 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:35:41 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:36:22 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-7 : Error not an encryption that I recognize.
30-Jul-2020 18:36:26 - ERROR   :: mylar.runGit.49 : CP Server Thread-2 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:36:26 - ERROR   :: mylar.runGit.49 : CP Server Thread-2 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:36:54 - ERROR   :: mylar.runGit.49 : CP Server Thread-7 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:36:54 - ERROR   :: mylar.runGit.49 : CP Server Thread-7 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:37:02 - ERROR   :: mylar.runGit.49 : CP Server Thread-3 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:37:02 - ERROR   :: mylar.runGit.49 : CP Server Thread-3 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:52:09 - ERROR   :: mylar.runGit.49 : MAIN : Command /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:52:09 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:52:09 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:53:20 - ERROR   :: mylar.runGit.49 : MAIN : Command /usr/bin/git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:53:20 - ERROR   :: mylar.runGit.49 : MAIN : Command git describe --exact-match --tags 2> /dev/null && git rev-parse HEAD --abbrev-ref HEAD didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:53:20 - ERROR   :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "/opt/mylar3/Mylar.py", line 386, in <module>
    main()
  File "/opt/mylar3/Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 86, in getVersion
    output, err = runGit('describe --exact-match --tags 2> %s && git rev-parse HEAD --abbrev-ref HEAD' % os.devnull)
  File "/opt/mylar3/mylar/versioncheck.py", line 69, in runGit
    return (output.stdout, output.stderr)
AttributeError: 'NoneType' object has no attribute 'stdout'

30-Jul-2020 18:53:38 - WARNING :: mylar.decrypt_it.45 : CP Server Thread-8 : Error not an encryption that I recognize.
30-Jul-2020 18:54:07 - ERROR   :: mylar.runGit.49 : CP Server Thread-3 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 18:54:07 - ERROR   :: mylar.runGit.49 : CP Server Thread-3 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 19:00:16 - ERROR   :: mylar.runGit.49 : CP Server Thread-9 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 19:00:16 - ERROR   :: mylar.runGit.49 : CP Server Thread-9 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 19:09:35 - ERROR   :: mylar.runGit.49 : CP Server Thread-5 : Command /usr/bin/git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
30-Jul-2020 19:09:35 - ERROR   :: mylar.runGit.49 : CP Server Thread-5 : Command git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 didn't work [__init__() got an unexpected keyword argument 'text']
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 in an LXC on a Debian host
 - Branch / commit: python3-dev 

**Additional information**
On the Settings/Information page, I see the following:

```
Mylar Version: python3-dev 
-- git (build None)
Python Version : 3.6.9
Language : en_US.UTF-8
```
Running git status in /opt/mylar3 returns:

```
On branch python3-dev
Your branch is up to date with 'origin/python3-dev'.

nothing to commit, working tree clean
```
It had previously referenced origin/Master, but I ran git checkout python3-dev as I had seen that as part of a possible solution in another post reporting a similar problem. Running git pull returns "Already up to date."

The git section in my original config.ini file was as follows:

```
[Git]
git_user = mylar3
check_github = True
git_path = None
check_github_on_startup = False
git_branch = None
```

However looking at other posts I tried updating to the following to see if it would resolve the issue (which it didn't):

```
[Git]
git_user = mylar3
check_github = True
git_path = /usr/bin/git
check_github_on_startup = False
git_branch = python3-dev
```
I have tried searching for a solution in Issues, but haven't been able to find anything. Any suggestions on what I've done wrong or how I can remedy this would be most appreciated.

--

**Comment by evilhero** [comment]
As per our readme - you're running an unsupported version of python with regards to Mylar. At a minimum, python 3.7.2 is required - of course, going higher into the 3.x is always better (we generally test using 3.8.1).

**Comment by dma9** [comment]
Ugh. I'm embarrassed. Sorry about that and thanks for the instructions. FWIW I had installed python3 but wasn't aware that point releases are separate packages for python or that there was a need to manually update alternatives. All fixed and thank you once again.
