### ISSUE TITLE
Startup Error on the last update (Docker)

### ISSUE THREAD

**Issue by NBSDEVApp** [mylar3/mylar3#418]
Hi, since the last update my mylar3 don't work, I have the same error on launch who block the app.

I use mylar3 on Docker with my Cloudbox server (ubuntu). Thanks

`
Error writing configuration file: [Errno 2] No such file or directory: '/config/mylar/config.ini'

log language set to en_US

Quiet logging mode enabled...

Initializing startup sequence....

Unable to make proper backup of config file in /config/mylar/config.ini.backup

Attempting to update configuration..

Updating Configuration from 0 to 10

Checking for existing torznab configuration...

No existing torznab configuration found. Just removing config references at this point..

Successfully removed outdated config entries.

Configuration upgraded to version 10

Traceback (most recent call last):

  File "/app/mylar/Mylar.py", line 386, in <module>

    main()

  File "/app/mylar/Mylar.py", line 203, in main

    mylar.initialize(mylar.CONFIG_FILE)

  File "/app/mylar/mylar/__init__.py", line 180, in initialize

    CONFIG = cc.read(startup=True)

  File "/app/mylar/mylar/config.py", line 562, in read

    logger.initLogger(console=not mylar.QUIET, log_dir=self.LOG_DIR, max_logsize=self.MAX_LOGSIZE, max_logfiles=self.MAX_LOGFILES, loglevel=mylar.LOG_LEVEL)

  File "/app/mylar/mylar/logger.py", line 275, in initLogger

    file_handler = RFHandler(filename, "a", maxBytes=max_logsize, backupCount=max_logfiles)

  File "/usr/local/lib/python3.8/logging/handlers.py", line 148, in __init__

    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)

  File "/usr/local/lib/python3.8/logging/handlers.py", line 55, in __init__

    logging.FileHandler.__init__(self, filename, mode, encoding, delay)

  File "/usr/local/lib/python3.8/logging/__init__.py", line 1143, in __init__

    StreamHandler.__init__(self, self._open())

  File "/usr/local/lib/python3.8/logging/__init__.py", line 1172, in _open

    return open(self.baseFilename, self.mode, encoding=self.encoding)

FileNotFoundError: [Errno 2] No such file or directory: '/config/mylar/logs/mylar.log'`

**Comment by barbequesauce** [comment]
Any word @nbsdevapp?
