### ISSUE TITLE
Search crashing with "could not convert string to float" on file with 2 sizes

### ISSUE THREAD

**Issue by Jookius** [mylar3/mylar3#440]
When Mylar is searching the DDL site for some reason one of the results gives 2 file sizes which is crashing the search and I have to restart Mylar.

Here is a partial list of the search results to parse:
2020-09-06 21:24:25 | DEBUG | 2020.07.29 Weekly Pack [2.7 G / 1.04 G]
2020-09-06 21:24:25 | DEBUG | 2020.08.19 Weekly Pack [3.7 G]

When the search parses 2020.07.29 Weekly Pack [2.7 G / 1.04 G], it crashes with this error:
2020-09-06 21:24:25 | ERROR | Uncaught exception: 
Traceback (most recent call last):
File "/home/pi/mylar3/mylar/search.py", line 921, in NZB_SEARCH
comsize_b = helpers.human2bytes(entry['size'])
File "/home/pi/mylar3/mylar/helpers.py", line 189, in human2bytes
assert float(num) and letter in symbols
ValueError: could not convert string to float: '2.7G/1.04'

I'm running Mylar3 [3af6bb1].

**Comment by Jookius** [comment]
Sorry, I think this is a duplicate of #413.
