### ISSUE TITLE
Webviewer broken in recent changes

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#457]
As per [this](https://github.com/linuxserver/docker-mylar3/issues/1) issue:

web viewer only opens the first page. There is a question mark button in the top left corner, but clicking it doesn't seem to do anything. I'm assuming there is supposed to be an overlay loaded with player controls but it doesn't seem to be loaded. I can open other pages only by changing the page_num in the url.

Console errors:

```
jquery-2.2.4.min.js:1 Failed to load resource: the server responded with a status of 404 ()
2materialize.min.js:1 Failed to load resource: the server responded with a status of 404 ()
read_comic?ish_id=763572&page_num=0&size=high:67 Uncaught ReferenceError: $ is not defined
    at read_comic?ish_id=763572&page_num=0&size=high:67
Roboto-Regular.woff2:1 Failed to load resource: the server responded with a status of 404 ()
Roboto-Regular.woff:1 Failed to load resource: the server responded with a status of 404 ()
Roboto-Regular.ttf:1 Failed to load resource: the server responded with a status of 404 ()
/favicon.ico:1 Failed to load resource: the server responded with a status of 500 ()
```

Error in the log:

```
192.168.13.12 - - [14/Sep/2020:05:50:02] "GET /read_comic?ish_id=763572&page_num=0&size=high HTTP/1.1" 200 1277 "http://192.168.13.40:8090/comicDetails?ComicID=112161" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/js/jquery-2.2.4.min.js HTTP/1.1" 404 465 "http://192.168.13.40:8090/read_comic?ish_id=763572&page_num=0&size=high" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/js/materialize.min.js HTTP/1.1" 404 463 "http://192.168.13.40:8090/read_comic?ish_id=763572&page_num=0&size=high" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/js/materialize.min.js HTTP/1.1" 404 463 "http://192.168.13.40:8090/read_comic?ish_id=763572&page_num=0&size=high" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/fonts/roboto/Roboto-Regular.woff2 HTTP/1.1" 404 468 "http://192.168.13.40:8090/interfaces/default/css/materialize.min.css" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/fonts/roboto/Roboto-Regular.woff HTTP/1.1" 404 466 "http://192.168.13.40:8090/interfaces/default/css/materialize.min.css" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
192.168.13.12 - - [14/Sep/2020:05:50:03] "GET /interfaces/default/fonts/roboto/Roboto-Regular.ttf HTTP/1.1" 404 465 "http://192.168.13.40:8090/interfaces/default/css/materialize.min.css" "Mozilla/5.0 (X11; CrOS aarch64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
[14/Sep/2020:05:50:04] HTTP
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
self._do_respond(path_info)
File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
response.body = self.handler()
File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
self.body = self.oldhandler(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
return self.callable(*self.args, **self.kwargs)
File "/usr/lib/python3.8/site-packages/cherrypy/_cptools.py", line 175, in handle_func
handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for argument 'filename'
```

**Comment by barbequesauce** [comment]
Fixed by #490
