### ISSUE TITLE
autoProcessComics not working correctly with Mylar's binary response

### ISSUE THREAD

**Issue by tjiddy** [mylar3/mylar3#498]
**Describe the bug**
I just upgraded to Mylar 3 and after copying the autoprocessComics and comicRN to my nzbget, the postprocessing was failing.  nzbget was calling into mylar, which was returning a success, but the autoprocess was failing trying to determing if mylar's response indicated a success or failure.  

You can see from the snippet below, Mylar's response type is binary, but autoProcessComics is doing a string comparison:
```
Sat Oct 17 22:37:22 2020        INFO    ComicRN: Opening URL for post-process of /downloads/Comics/Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire @ http://mylar:8090/api/forceProcess:
Sat Oct 17 22:37:22 2020        INFO    ComicRN: statuscode: 200
Sat Oct 17 22:37:22 2020        INFO    ComicRN: b'nzb name: Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire\nnzb folder: /downloads/Comics/Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire\nnzbname: Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire\nIssue Year: 2020\nPublisher: Marvel\nSeries: Star Wars: Bounty Hunters\nYear: 2020\nComic Location: /comics/Star Wars Bounty Hunters (2020)\nComic Version: None\nNo version # found for series - tag will not be available for renaming.\nMetatagging enabled - proceeding...\nSucessfully wrote metadata to .cbz - Continuing..\nOriginal Filename: Star Wars - Bounty Hunters 002 (2020) (Digital) (Kileko-Empire).cbz [.cbz]\nNew Filename: Star Wars Bounty Hunters 002 (2020)\nSource: /config/mylar/cache/mylar_oy70o4sp/Star Wars - Bounty Hunters 002 (2020) (Digital) (Kileko-Empire).cbz\nDestination: /comics/Star Wars Bounty Hunters (2020)/Star Wars Bounty Hunters 002 (2020).cbz\n[move] /config/mylar/cache/mylar_oy70o4sp/Star Wars - Bounty Hunters 002 (2020) (Digital) (Kileko-Empire).cbz -
Sat Oct 17 22:37:22 2020        INFO    ComicRN: Traceback (most recent call last):
Sat Oct 17 22:37:22 2020        INFO    ComicRN:   File "/config/scripts/ComicRN.py", line 49, in <module>
Sat Oct 17 22:37:22 2020        INFO    ComicRN:     result = autoProcessComics.processIssue(os.environ['NZBPP_DIRECTORY'], os.environ['NZBPP_NZBNAME'], failed=failit, comicrn_version=comicrn_version)
Sat Oct 17 22:37:22 2020        INFO    ComicRN:   File "/config/scripts/autoProcessComics.py", line 116, in processIssue
Sat Oct 17 22:37:22 2020        INFO    ComicRN:     if any("Post Processing SUCCESSFUL" in s for s in result.split('\n')):
Sat Oct 17 22:37:22 2020        INFO    ComicRN: TypeError: a bytes-like object is required, not 'str'
Sat Oct 17 22:37:22 2020        ERROR   Post-process-script ComicRN.py for Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire failed (terminated with unknown status)
Sat Oct 17 22:37:22 2020        INFO    Collection Star.Wars-Bounty.Hunters.002.2020.Digital.Kileko-Empire added to history

```

**Fix**
I was able to fix the issue by inserting the following condition at line 115 of autoProcessComics.py
```python
    elif type(result) == bytes:
        if b'Post Processing SUCCESSFUL' in result:
            return 0
        else:
            return 1
```

**Environment (please complete the following information):**
 - OS: Version: linux using linuxserver.io's mylar 3 docker.
 - Branch / commit: Mylar Version: master [v0.4.6]
     -- source (build eb7188e79801344910e573ba30a6580bd6f76070)

**Comment by barbequesauce** [comment]
That last merge should solve the issue for good - thanks!
