### ISSUE TITLE
Webviewer displays a large X in a circle when trying to view a comic

### ISSUE THREAD

**Issue by jwm-evans** [mylar3/mylar3#505]
**Describe the bug**
Whenever I try to read a comic using the built-in webviewer, all I see is a large X in a circle (screenshot attached). This occurs for any comic that I try to view. Looking at the console log, it seems that every comic appears to have 0 pages, though other readers do not have any issues.
```
192.168.0.35 - - [20/Oct/2020:20:05:53] "GET /read_comic?ish_id=721067&page_num=0&size=high HTTP/1.1" 200 1252 "http://192.168.0.46:8090/comicDetails?ComicID=115725" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
192.168.0.35 - - [20/Oct/2020:20:05:53] "GET /interfaces/carbon/fonts/roboto/Roboto-Regular.woff2 HTTP/1.1" 404 467 "http://192.168.0.46:8090/interfaces/carbon/css/materialize.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
192.168.0.35 - - [20/Oct/2020:20:05:54] "GET /interfaces/carbon/fonts/roboto/Roboto-Regular.woff HTTP/1.1" 404 466 "http://192.168.0.46:8090/interfaces/carbon/css/materialize.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
192.168.0.35 - - [20/Oct/2020:20:05:54] "GET /interfaces/carbon/fonts/roboto/Roboto-Regular.ttf HTTP/1.1" 404 465 "http://192.168.0.46:8090/interfaces/carbon/css/materialize.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
[20/Oct/2020:20:05:54] HTTP 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/cherrypy/_cptools.py", line 175, in handle_func
    handled = self.callable(*args, **self._merged_args(kwargs))
TypeError: staticfile() got multiple values for argument 'filename'
[20/Oct/2020:20:05:54] HTTP 
Request Headers:
  Remote-Addr: 192.168.0.35
  HOST: 192.168.0.46:8090
  CONNECTION: keep-alive
  USER-AGENT: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
  ACCEPT: image/avif,image/webp,image/apng,image/*,*/*;q=0.8
  REFERER: http://192.168.0.46:8090/read_comic?ish_id=721067&page_num=0&size=high
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-GB,en-US;q=0.9,en;q=0.8
  COOKIE: organizrLanguage=en; organizr_token_b8a23391-be4c-4e88-a69f-729f6d1a56ed=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImp0aSI6IjRmMWcyM2ExMmFhIn0.eyJpc3MiOiJPcmdhbml6ciIsImF1ZCI6Ik9yZ2FuaXpyIiwianRpIjoiNGYxZzIzYTEyYWEiLCJpYXQiOjE2MDI2OTUzMzgsImV4cCI6MTYxMTMzNTMzOCwidXNlcm5hbWUiOiJqYW1lcyIsImdyb3VwIjoiQWRtaW4iLCJncm91cElEIjowLCJlbWFpbCI6ImphbWVzLmJvdHN3YW5hQGdtYWlsLmNvbSIsImltYWdlIjoiaHR0cHM6XC9cL3d3dy5ncmF2YXRhci5jb21cL2F2YXRhclwvOTAwMmU5MDczOGExNGU4ZTJjZmE4MmViZjU1Y2I1Zjk_cz0xMDAmZD1tbSIsInVzZXJJRCI6MX0.uHWZ-0OeEI20AR8iz-vuWmCMMKD6KBJIcKk7A3EJUBM; theme=Dark; Auth-Type=http; library.filter.02SAV20MNM8HV=%7B%22readStatus%22%3A%5B%22UNREAD%22%5D%7D; Auth-Token=VClH68OTXJDPGTG0KYtRyqqSXHXg9za1iE90ZpqgMeQac3gS; cookie_comic=0; JSESSIONID=E17599E64BAEE703C326842E247040F5; session_id=e8160bd5c54adcd0bd3ce6c445ca6dc1171d99da
192.168.0.35 - - [20/Oct/2020:20:05:54] "GET /favicon.ico HTTP/1.1" 500 824 "http://192.168.0.46:8090/read_comic?ish_id=721067&page_num=0&size=high" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
```

**CarePackage**
Attached

**Environment :**
 - OS: [e.g. Windows10] MacOS 10.15.7 (client) Ubuntu 20.04 amd64 (server)
 - Branch / commit: [e.g. Dev/38aksi1] Version 0.4.7 master
[carepackage.zip](https://github.com/mylar3/mylar3/files/5411091/carepackage.zip)
![mylar3_webviewer_error](https://user-images.githubusercontent.com/3108559/96635086-549fd780-1313-11eb-8603-aad3be1f273d.png)

**Comment by evilhero** [comment]
At the moment it's a bug we're looking into - there is a quick workaround. 

If you click on the right-side of the X (as if you were advancing to the next page in the reader) it will advance and load the next page, then going back to the initial page (which is the cover) will load fine. 

It's some kind of caching / timing thing - just not sure what's going on atm.

**Comment by barbequesauce** [comment]
we ok to close?

**Comment by jwm-evans** [comment]
It seems to be fine now (running Version: v0.4.9, python3-dev ( master))
