### ISSUE TITLE
Missing Icon using Carbon theme

### ISSUE THREAD

**Issue by cloudycloud47** [mylar3/mylar3#507]
**Describe the bug**
When using Carbon theme, there is a icon_search.png missing when searching with StoryArcs.

This can be resolved temporarily by creating a folder 'images' under /mnt/media/iocage/jails/mylar/root/usr/local/mylar3/data/interfaces/default/
and copying the image file icon_search.png from folder /mnt/media/iocage/jails/mylar/root/usr/local/mylar3/data/images

**Environment (please complete the following information):**
 - OS: FreeNAS 12.1 iocage
 - Branch / commit: master v0.4.6 [build eb7188e79801344910e573ba30a6580bd6f76070]

**Additional information**
404 Not Found
The path '/interfaces/default/images/icon_search.png' was not found.

Traceback (most recent call last):
  File "/usr/local/virtual/mylar/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/virtual/mylar/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/virtual/mylar/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/virtual/mylar/lib/python3.7/site-packages/cherrypy/_cperror.py", line 416, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/interfaces/default/images/icon_search.png' was not found.")
Powered by CherryPy 18.6.0

**Comment by evilhero** [comment]
There's no need to do that.

Just update to the latest version since you're running an old version. 

This was fixed in v0.4.7.

**Comment by cloudycloud47** [comment]
seems fixed now.
I had to switch to Python3-dev branch and then back the master to get the latest master branch commit.
Thanks
