### ISSUE TITLE
API Usage Logging

### ISSUE THREAD

**Issue by jun6lee** [mylar3/mylar3#514]
I think this might be my API being locked for over-usage (probably fair for what I've been up to).
This said, it would be nice to know how much as a percentage if there's a clear limit is being used up.

My assumption comes from:

```

2020-10-25 00:51:53 | ERROR | Uncaught exception: Traceback (most recent call last):File "/share/CACHEDEV1_DATA/.qpkg/Mylar3/Mylar3/mylar/logger.py", line 337, in new_runold_run(*args, **kwargs)File "/opt/lib/python3.8/threading.py", line 870, in runFile "/share/CACHEDEV1_DATA/.qpkg/Mylar3/Mylar3/mylar/importer.py", line 109, in addComictoDBcomic = cv.getComic(comicid, 'comic')File "/share/CACHEDEV1_DATA/.qpkg/Mylar3/Mylar3/mylar/cv.py", line 160, in getComicreturn GetComicInfo(comicid, dom)File "/share/CACHEDEV1_DATA/.qpkg/Mylar3/Mylar3/mylar/cv.py", line 227, in GetComicInfotracks = dom.getElementsByTagName('issue')AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
-- | -- | --
2020-10-25 00:51:53 | WARNING | Error fetching data from ComicVine: HTTPSConnectionPool(host='comicvine.gamespot.com', port=443): Max retries exceeded with url: /api/volume/4050-84706/?api_key=##my_api_redacted##&format=xml&field_list=name,count_of_issues,issues,start_year,site_detail_url,image,publisher,description,first_issue,deck,aliases (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))


```

**Comment by evilhero** [comment]
If you're using Mylar with another program (ie.cvscrapper,or another version of comictagger) that uses the same CV API key you'll get this message, as then you're making requests > one every second (or other second can't remember).

There's no way for Mylar to track API hits outside of the program, as the CV API doesn't have an endpoint for API usage. Not sure of how much benefit it is for Mylar to track the API usage from within the program as under normal circumstances you'd only get tagged  for overusage if you go over their limit of 200 requests in an hr (they typically reset API overage limits every hr).

If you go to the CV API website, it will tell you what your hits are.

**Comment by jun6lee** [comment]
No, not using anything except Mylar (unless the qnap package has added anything but I don't think so).

Had a look at the CV API Page... Who say..
You have no current rate limits. Go forth and query.

**Comment by evilhero** [comment]
QNAP wouldn't add anything like that to the program.

If it says you're free to go query, you should be fine to try again (restart Myalr just to be sure)

**Comment by jun6lee** [comment]
Got me a new API too. Restarted. Still no joy.

Could you just check if you are able to add anything? 
Maybe it's just their end?

**Comment by jun6lee** [comment]
Resolved, was some DNS crap at my ISP end.
