### ISSUE TITLE
ModuleNotFoundError: No module named 'jaraco.collections'

### ISSUE THREAD

**Issue by x5nder** [mylar3/mylar3#543]
**Describe the bug**
Since my last apt update/upgrade and reboot, Mylar won't start anymore. Mylar was working fine this morning on Python 3.9 (using service start or manual run, see below).

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Branch / commit: Mylar3 4.9

**Additional information**

```
kraken@kraken:/opt/Mylar$ python3 --version
Python 3.9.0
```

```
kraken@kraken:/opt/Mylar$ pip3.9 install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
...
Requirement already satisfied: jaraco.classes in /home/kraken/.local/lib/python3.9/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.1.0)
Requirement already satisfied: jaraco.text in /home/kraken/.local/lib/python3.9/site-packages (from jaraco.collections->CherryPy>=18.5.0->-r requirements.txt (line 11)) (3.2.0)
```

```
kraken@kraken:/opt/Mylar$ python3 /opt/Mylar/Mylar.py 
Traceback (most recent call last):
  File "/opt/Mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/Mylar/mylar/__init__.py", line 36, in <module>
    import cherrypy
  File "/home/kraken/.local/lib/python3.9/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/home/kraken/.local/lib/python3.9/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/home/kraken/.local/lib/python3.9/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
ModuleNotFoundError: No module named 'jaraco.collections'
```

(additionally:

```
kraken@kraken:/opt/Mylar$ python3.8 /opt/Mylar/Mylar.py 
Traceback (most recent call last):
  File "/opt/Mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/Mylar/mylar/__init__.py", line 33, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'
```

```
kraken@kraken:/opt/Mylar$ python3.9 /opt/Mylar/Mylar.py 
Traceback (most recent call last):
  File "/opt/Mylar/Mylar.py", line 26, in <module>
    import mylar
  File "/opt/Mylar/mylar/__init__.py", line 24, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

)... anyone any idea how to fix this? :-(

**Comment by evilhero** [comment]
The python3.9 command looks like you didn't compile python with the sqlite option, so it didn't install the sqlite component (which normally when not compiling, is the default). See [here](https://github.com/mylar3/mylar3/issues/238)

The python3.8 command looks like you didn't run pip requirements.txt against that specific version of python using pip3.8. You have to do the install requirements.txt against each version of python that you wish to run mylar against (ie. it doesn't apply requirements.txt to every verison of python on your system)

Do you have more than one version of python3.9 installed on your system? Normally you don't symlink python3 and python3.9 as they would point to independent versions, so to have one version respond to both isn't unless it was intended.

The jaraco error is happening due to having the pip version of cherrypy in addition to the apt-version ( or something along those lines ). I've seen the error pop up on other programs, but no one has really given any insight as to actually fix it aside from going to a new virtual environment.  A previous problem was encountered with Mylar [here](https://github.com/mylar3/mylar3/issues/448), but the OP tailed off and no clue about any resolution.

You can try to get it lined up by doing a : 
```pip3.9 install -U jaraco.collections``` (change the pip3.9 to pip3 maybe).

Theoretically, if Mylar is your only python application that uses cherrypy, you can uninstall the pip version (provided you have the non-pip version installed), or vice-versa (uninstall the apt version, and keep the pip version).  Note that you might want to do this prior to do the pip install jaraco.collections line above since that might be a straggler.

**Comment by x5nder** [comment]
Ah! That's why... I installed Sabnzbd, and it installed jaroco.collections as one of its dependencies. I tried uninstalling the PIP versions (with pip3 uninstall jaraco.collections) but Mylar still wouldn't start. Reinstalled it and then removed Sabnzbd from apt, and that fixed the problem...

**Comment by x5nder** [comment]
I'll just keep Sab running on my NAS and forget about installing it on my Ubuntu machine. Don't want to end up going down a rabbit hole of fixes upon fixes ;p

**Comment by x5nder** [comment]
I do have one question-- 'Enable Completed Download Handling' only works with downloads initiated by Mylar, correct? As in: the only way to automatically post-process comic downloads that I manually send to Sab from NZB.SU or Dognzb is by using the ComicRN script? Or am I missing something?

**Comment by evilhero** [comment]
No that's correct.

Completed Download Handling (or CDH as we affectionately call it) will monitor downloads that have been sent by Mylar to SABnzbd. 

If you're wanting to post-process ones that are not initiate by Mylar, then you have 2 options:
- ComicRN script. Just set the category to something different than the one you use with CDH (you can probably keep them the same, but sometimes it can get messy). Mylar tracks by an id that sabnzbd utilizes so it won't grab something it's not actively monitoring, but with a different category you can then set the location to a different location if requried.
- Folder Monitoring. Manually downloaded items go into a specific folder that is monitored by Mylar every few minutes (set it to at least 2 minutes, preferably upwards of 5 minutes). These items will then be automatically post-processed on the schedule once the download is complete (Mylar won't post-process something until it stops being written to).

As far as the jaraco stuff, when you installed SABnzbd did you install it via the PPA ? Apparently the correct way to install it (if you need to keep your pip stuff), is to install SABnzbd from the Ubuntu repo, and upgrade via the JCFP PPA. Although I honestly don't know if then because the pip stuff is still there if it would cause any issues for either Mylar or SABnzbd...
