### ISSUE TITLE
Generate API key throws an error

### ISSUE THREAD

**Issue by BRTPOB** [mylar3/mylar3#55]
192.168.1.2 - - [02/Feb/2020:09:42:07] "GET /config HTTP/1.1" 200 153625 "http://192.168.1.36:8090/config" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[02/Feb/2020:09:42:22] HTTP 
Traceback (most recent call last):
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/offspring/.local/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 5663, in generateAPI
    apikey = hashlib.sha224(str(random.getrandbits(256))).hexdigest()[0:32]
TypeError: Unicode-objects must be encoded before hashing
[02/Feb/2020:09:42:22] HTTP 
Request Headers:
  Remote-Addr: 192.168.1.2
  HOST: 192.168.1.36:8090
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  ACCEPT-ENCODING: gzip, deflate
  X-REQUESTED-WITH: XMLHttpRequest
  DNT: 1
  CONNECTION: keep-alive
  REFERER: http://192.168.1.36:8090/config
192.168.1.2 - - [02/Feb/2020:09:42:22] "GET /generateAPI HTTP/1.1" 500 1654 "http://192.168.1.36:8090/config" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"

**Comment by evilhero** [comment]
Please to verify fix.

**Comment by BRTPOB** [comment]
Fixt.
