### ISSUE TITLE
Repeated search.py error

### ISSUE THREAD

**Issue by silentArtifact** [mylar3/mylar3#554]
**Describe the bug**
This seems to crop up fairly often, Mylar will grab an episode maybe once or twice a day, usually right after restarting, but otherwise won't search or find issues. The logs show this error repeating frequently:

`

2020-11-24 12:29:49 | ERROR | Traceback (most recent call last):  File "/app/mylar3/mylar/search.py", line 3093, in searchforissue    foundNZB, prov = search_init(  File "/app/mylar3/mylar/search.py", line 515, in search_init    findit = NZB_SEARCH(  File "/app/mylar3/mylar/search.py", line 2404, in NZB_SEARCH    searchresult = searcher(  File "/app/mylar3/mylar/search.py", line 4030, in searcher    ss = nzbget.NZBGet()  File "/app/mylar3/mylar/nzbget.py", line 38, in __init__    val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignmentTraceback (most recent call last):  File "/app/mylar3/mylar/search.py", line 3093, in searchforissue    foundNZB, prov = search_init(  File "/app/mylar3/mylar/search.py", line 515, in search_init    findit = NZB_SEARCH(  File "/app/mylar3/mylar/search.py", line 2404, in NZB_SEARCH    searchresult = searcher(  File "/app/mylar3/mylar/search.py", line 4030, in searcher    ss = nzbget.NZBGet()  File "/app/mylar3/mylar/nzbget.py", line 38, in __init__    val = (protocol,)UnboundLocalError: local variable 'protocol' referenced before assignment
-- | -- | --

`

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5590422/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Synology DSM / Docker
 - Branch / commit: v0.4.9 ( master) 

**Additional information**
Not sure if it's related, but searches only seem to work after restarting the docker container.

**Comment by evilhero** [comment]
You need to have the protocol in your nzbget host address - either http or https (there should be a small example beneath the nzbget host address line within Mylar).

**Comment by silentArtifact** [comment]
Hoo-boy, I feel dumb. Fixed it. Thanks for all your work on this!
