### ISSUE TITLE
ComicRN: ImportError: No module named configparser

### ISSUE THREAD

**Issue by phairplay** [mylar3/mylar3#576]
**Describe the bug**
running mylar3 on windows pc and when downloading and running process it fails with the follwing messages in NZBGET
```
ERROR	Tue Dec 22 2020 11:18:02	Post-process-script ComicRN.py for DCeased.006.2019.Variant.Cover.Digital.Phantom-SWA failed (terminated with unknown status)
INFO	Tue Dec 22 2020 11:18:02	ComicRN: ImportError: No module named configparser
INFO	Tue Dec 22 2020 11:18:02	ComicRN: import configparser.


```
**CarePackage**
On the config page, there is a button labelled "CarePackage". Pressing this button will download a zip file containing a redacted copy of your config, your database, a summary of your operating environment, and your logs. Upload that file here.

If you're uncomfortable with pasting your CarePackage, include a DEBUG log containing the error from disk. 

Do not paste from the GUI log.
Do not just paste a traceback/error.

**Environment (please complete the following information):**
 - OS: WINDOWS 10
 - Branch / commit: 813397ba3e70df7996909f04e009de91fae324b2

**Additional information**
I'm running both python2 and python3 
i pip installed configparser to be told I'm running version 5 in python3.

**Comment by evilhero** [comment]
I'm pretty sure you're using the autoProcessComics and ComicRN scripts from Mylar3, but you're using it with the python2 version of SABnzbd, and not the python3 version, which unfortunately creates some inconsistencies.

The module ```configparser``` changed from ```ConfigParser``` to ```configparser``` between python2 and python3. So the fact that it's not camel-cased, would indicate that you're using the newer Mylar3 scripts.

So what you can do just to confirm this, is get the autoProcessComics.py and ComicRN.py scripts from the python2 repo of Mylar and replace your existing versions with them. Then try again, and I'm betting it will work fine at that point.

**Comment by lamahmud** [comment]
I'm actually having the same issue.  My SABnzbd version is 3.3.1 [654302e] which doesn't support Python 2.  I'm running on MacOS 10.15.6.  My mylar3 build is python3-dev [b451165ce764c25a1f57204fcd7d70ccedda312c].  My python version reported by mylar is 3.9.7 while SABnzbd reports 3.9.5 (v3.9.5:0a7dcbdb13, May 3 2021, 13:17:02) [Clang 6.0 (clang-600.0.57)] [UTF-8]. ​

My SAB logs show the following error:
Traceback (most recent call last):
File "/Volumes/MacHD/Users/lam/Applications/mylar3/post-processing/sabnzbd/ComicRN.py", line 13, in <module>
import autoProcessComics
File "/Volumes/MacHD/Users/lam/Applications/mylar3/post-processing/sabnzbd/autoProcessComics.py", line 3, in <module>
import configparser
ImportError: No module named configparse

**Comment by evilhero** [comment]
If you have 2 different versions of python installed, you need to ``pip install configparser, requests`` (or ``pip3`` or ```pip3.9.7`` or however you access it) on the version that sabnzbd is running against - since that's the program that executes the ComicRN script on completion, not Mylar. The error is saying the python 3.9.5 cannot find the module configparser as it was not installed (and will probably be a subsequent  error for requests module) 

You can always just use Completed Download Handling (CDH) option within Mylar instead of the script and not have to worry about any of this type of stuff.

**Comment by evilhero** [comment]
Closing due to staleness. 

If it's still an issue, please open a new issue with the relevant information.
