### ISSUE TITLE
You're running an unknown version of Mylar

### ISSUE THREAD

**Issue by bebetec** [mylar3/mylar3#591]
**Describe the bug**
I followed the upgrade guide from v2 Experimental to v3. When I load mylar3, I get the following error on version:

`You're running an unknown version of Mylar`

Loading from command line shows:
```
python3 Mylar.py
log language set to en_AU
Initializing startup sequence....
[02/Jan/2021:20:26:33] ENGINE Serving on http://0.0.0.0:8090
02-Jan-2021 20:26:33 - ERROR :: mylar.excepthook.315 : MAIN : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0

Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 356, in main
    versioncheck.versionload()
  File "/opt/mylar3/mylar/versioncheck.py", line 364, in versionload
    version_info = getVersion()
  File "/opt/mylar3/mylar/versioncheck.py", line 114, in getVersion
    if git[0]['name'] is not None:
KeyError: 0
```

**CarePackage**
```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar3/mylar/webserve.py", line 5802, in carepackage
    cp = carePackage()
  File "/opt/mylar3/mylar/carepackage.py", line 86, in __init__
    self.cleaned_config()
  File "/opt/mylar3/mylar/carepackage.py", line 149, in cleaned_config
    shutil.copy(self.configpath, self.cleanpath)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/mylar3/data/config.ini'
```

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Branch / commit: Master (fresh pull)

**Additional information**
Add any other information about the problem here.

**Comment by bebetec** [comment]
Fixed it: https://github.com/mylar3/mylar3/issues/409#issuecomment-729666023
