### ISSUE TITLE
 language detected as non-English

### ISSUE THREAD

**Issue by hgourvest** [mylar3/mylar3#603]
The probleme seem to be here: https://github.com/mylar3/mylar3/blob/2100583ea0609c8c2c9243b2ff6dcfb42492e7de/Mylar.py#L146

same error was referenced here: https://github.com/evilhero/mylar/issues/1915

> language detected as non-English (fr_FR). Forcing specific logging module - errors WILL NOT be captured in the logs
Initializing startup sequence....
Unable to make proper backup of config file in /home/henri/dev/mylar3/config.ini.backup
Attempting to update configuration..
Updating Configuration from 0 to 10
Checking for existing torznab configuration...
No existing torznab configuration found. Just removing config references at this point..
Successfully removed outdated config entries.
Configuration upgraded to version 10
Traceback (most recent call last):
  File "Mylar.py", line 386, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/home/henri/dev/mylar3/mylar/__init__.py", line 185, in initialize
    CONFIG = cc.read(startup=True)
  File "/home/henri/dev/mylar3/mylar/config.py", line 544, in read
    self.writeconfig()
  File "/home/henri/dev/mylar3/mylar/config.py", line 771, in writeconfig
    logger.fdebug("Writing configuration to file")
  File "/home/henri/dev/mylar3/mylar/logger.py", line 168, in fdebug
    if mylar.LOG_LEVEL > 1:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by evilhero** [comment]
Please follow the template for issues.

The logger module doesn't control the initial value - this is in the config.py file and has long been fixed since the evilhero version.

Check your config.ini for duplicate references of log_level. What is it currently set to if you have only one reference? 

What does your startup command look like? 

Is this a migration from a previous version of mylar?

Again, just to reiterate, please follow the template next time.

**Comment by hgourvest** [comment]
it is a fresh install, 

git clone https://github.com/mylar3/mylar3.git
cd mylar3
pip3 install -r requirements.txt
python3 Mylar.py

the config.ini file is not yet here, I have to change None to 0 to be able to start the server.
after that I can revert my change because there is a config file.
I think it is related to my system language fr_FR

**Comment by hgourvest** [comment]
BTW, I didn't see there is a template because I created the issue referencing a line in a file, sorry

**Comment by evilhero** [comment]
what version of Mylar are you running?
what version of python are you running?
what OS are you running ?

If it's a fresh install Mylar forces the value to 1 on startup (ie. no config present), which is before all the logging actually starts, so at some point your installation is telling it to ignore the value that is set. At that particular point it has nothing to do with your language selected as it hasn't gotten that far as of yet.

**Comment by hgourvest** [comment]
I use the trunk with Pyhthon 3.8.5 on Ubuntu 20.04.1

**Comment by BRTPOB** [comment]
When you say trunk, you mean the main branch not development, right?

**Comment by hgourvest** [comment]
exactly

**Comment by evilhero** [comment]
Ok, I did some finagling and was able to reproduce the error. Fix should be in python3-dev shortly, but in the meantime just set your log_level to something other than None (or use the -v switch on startup for verbose logging, which is log_level 2).

**Comment by hgourvest** [comment]
Thank you!
