### ISSUE TITLE
Error when clicking on Download 0-Day from Weekly Pull section

### ISSUE THREAD

**Issue by edimusxero** [mylar3/mylar3#617]
**Describe the bug**
In the Weekly Pull section if you click on "Download 0-Day Pack" you get an error message.

**CarePackage**
[carepackage.zip](https://github.com/mylar3/mylar3/files/5842970/carepackage.zip)

**Environment (please complete the following information):**
 - OS: Ubuntu lts - 20
 - master

**Additional information**
Seems like it actually functions as expected, I assume this is just a logging issue.  Here is the stack trace.

    Traceback (most recent call last):
        File "/usr/local/src/mylar3/vmylar/mylar/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 638, in respond
			self._do_respond(path_info)
		File "/usr/local/src/mylar3/vmylar/mylar/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond
			response.body = self.handler()
		File "/usr/local/src/mylar3/vmylar/mylar/lib/python3.8/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
			self.body = self.oldhandler(*args, **kwargs)
		File "/usr/local/src/mylar3/vmylar/mylar/lib/python3.8/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
			return self.callable(*self.args, **self.kwargs)
		File "/usr/local/src/mylar3/mylar/webserve.py", line 6443, in download_0day
			foundcom, prov = search.search_init('%s.%s.%s Weekly Pack' % (week[:4],week[5:7],week[8:]), None, week[:4], None, None, week, week, None, allow_packs=True, oneoff=True)
		File "/usr/local/src/mylar3/mylar/search.py", line 340, in search_init
			elif len(c_number) == 1:
	UnboundLocalError: local variable 'c_number' referenced before assignment

**Comment by evilhero** [comment]
That option should only appear if you have 32p enabled as a provider. If you do disable it, as 32p is longer with us.

The option, when it worked, was only for 32p. There will be one for DDL coming soon, but until then make sure you don't have  32p enabled.

**Comment by edimusxero** [comment]
Perfect, thanks
