### ISSUE TITLE
Cannot add wanted comics, all show as "None"

### ISSUE THREAD

**Issue by JakeShirley** [mylar3/mylar3#654]
**Describe the bug**
Can't add "wanted" comics.  Every time I add a comic it doesn't actually add and I get this in the logs:
```
Feb-2021 20:39:41 - INFO    :: mylar.dbUpdate.116 : ThreadPoolExecutor-0_1 : [1/1] Refreshing :Comic ID: 116557 (None) [116557]
24-Feb-2021 20:39:41 - INFO    :: mylar.addComictoDB.87 : ThreadPoolExecutor-0_1 : aliases currently: None
24-Feb-2021 20:41:27 - WARNING :: mylar.havetotals.1419 : CP Server Thread-8 : Comic ID: 116557 has not finished loading. Nulling some values so things display properly until they can populate.
24-Feb-2021 20:43:39 - INFO    :: mylar.addComictoDB.131 : Thread-13 : Now adding/updating: The Devil Is A Part-Timer!
24-Feb-2021 20:43:39 - INFO    :: mylar.addComictoDB.184 : Thread-13 : Sucessfully retrieved details for The Devil Is A Part-Timer!
24-Feb-2021 20:43:39 - INFO    :: mylar.addComictoDB.195 : Thread-13 : Previous version detected as None - seeing if update required
24-Feb-2021 20:43:39 - ERROR   :: mylar.excepthook.315 : Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar3/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/mylar3/mylar/importer.py", line 228, in addComictoDB
    comvalues = dothedew.folder_create()
  File "/app/mylar3/mylar/filers.py", line 213, in folder_create
    ddir = pathlib.PurePath(mylar.CONFIG.DESTINATION_DIR)
  File "/app/mylar3/lib/pathlib.py", line 585, in __new__
    return cls._from_parts(args)
  File "/app/mylar3/lib/pathlib.py", line 613, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/app/mylar3/lib/pathlib.py", line 603, in _parse_args
    raise TypeError(
TypeError: argument should be a path or str object, not <class 'NoneType'>
```

**CarePackage**
Included

[carepackage.zip](https://github.com/mylar3/mylar3/files/6040531/carepackage.zip)\

**Environment (please complete the following information):**
- OS: Linux docker
Mylar Version: master [v0.4.9.5, python3-dev]
-- source (build b245a63f864e1a242a79fed53e28a02ce251fbf8)
Python Version : 3.8.7
Language : en_US.UTF-8

**Additional information**

**Comment by evilhero** [comment]
As per the readme / main page tidbit, you need to set your Comic Location path in the configuration:
```
Helpful hints:

Ensure Comic Location is specified in the configuration (Configuration --> Web Interface --> Comic Location)
- Mylar auto-creates the Comic Series directories under the Comic Location. The directory is displayed on the Comic Detail page).
- If you do not want directories to be created until there are issues present, set create_folders = False in the config.ini.
```

**Comment by JakeShirley** [comment]
Oh man that totally fixed it.

Sorry a ton, I swear I read the readme (I even got a CV API key).  

Thanks for being so prompt.  I guess my old feedback is to make this clearer in the setup/config page, but I can't complain.

Thanks a ton!
