### ISSUE TITLE
KeyError: 'links' crash

### ISSUE THREAD

**Issue by adispi** [mylar3/mylar3#664]
my log is full of errors like this, on different comics, and every time this crash happens, mylar will not download new comic until i restart it.

mylar info:
Mylar Version: master
-- source (build 69fc804b048407986add632dc13544120cb8a5e9)
Python Version : 3.8.7
Language : en_US.UTF-8

running in docker image linuxserver/mylar3:nightly

11-Mar-2021 22:48:07 - INFO    :: mylar.NZB_SEARCH.1266 : SEARCH-QUEUE : sending Truth & Justice to experimental search
11-Mar-2021 22:48:18 - ERROR   :: mylar.searchforissue.3198 : SEARCH-QUEUE : Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 156, in __getattr__
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 65, in __getitem__
    for link in dict.__getitem__(self, 'links')
KeyError: 'links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3126, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 1267, in NZB_SEARCH
    bb = findcomicfeed.Startit(
  File "/app/mylar3/mylar/findcomicfeed.py", line 122, in Startit
    urlParse = feed.entries[countUp].enclosures[0]
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 158, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'enclosures'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 156, in __getattr__
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 65, in __getitem__
    for link in dict.__getitem__(self, 'links')
KeyError: 'links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3126, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 1267, in NZB_SEARCH
    bb = findcomicfeed.Startit(
  File "/app/mylar3/mylar/findcomicfeed.py", line 122, in Startit
    urlParse = feed.entries[countUp].enclosures[0]
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 158, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'enclosures'

**Comment by evilhero** [comment]
What version is your feedparser at?  

You're using a version that's not compatible for some reason - did you  install the requirements.txt as per the readme?

**Comment by adispi** [comment]
as this is a docker image i did not install anything but the image.
however the docker shell pip list tell me the version is 6.0.2

**Comment by evilhero** [comment]
Turn off experimental then as a provider option. There's something going on with their feed, and/or you've hit some temporary ban and you can't hit the required url.

**Comment by adispi** [comment]
confirmed. after removing experimental, for the last 15 minutes i have no exceptions.
is there something i can do to check why experimental is crashing?

**Comment by evilhero** [comment]
They throw around temp bans pretty easily depending on how often you're searching. Since they have no API, Mylar's just parsing the returned feed so that might trigger if you do enough I suppose (it pauses for a few seconds between each query). There's really been no rhyme or reason from what I could recall, but it's usually only for a few minutes. 

Can you reach nzbindex.nl from a webpage from the machine running mylar?

**Comment by evilhero** [comment]
Should be resolved in latest versions.

Closing, if it's still an issue please open a new issue with the relevant information.
