### ISSUE TITLE
Folder.jpg & Series.json

### ISSUE THREAD

**Issue by Budlyte** [mylar3/mylar3#686]
I very much appreciate the work to add-in these features that support the Comixology Ubooquity theme.

Here are a few things I noticed.
- Folder.jpg is saved as 80x80px and becomes too low resolution to view.  The originals are 320x320px.
- The description in Series.json is labeled as "Description_text", "Description" is needed for the theme and seems to also work for Mylar.
- Could the click on a yellow "series.json" button, that generates a new json file, not run if a json already exists or generate a popup first, or maybe just append sections that don't already exist? CV doesn't always have series descriptions, currently one bad click/tap and a good json file can be wiped out.

**Comment by evilhero** [comment]
I'll briefly run these down, altho it's probably easier to fine-tune things in irc:
- folder.jpg isn't being shrunk or anything by Mylar - it's the thumbnail that's being returned from the CV API. If there are different size thumbnails, then I couldn't find them in the API when I was attempting to finagle the images (and we're not going to parse the CV site as that's a no-no).
- ```description_text``` is used to indicate the description with no line breaks, formatting, etc. ```description_formatted``` is used to to indicate the description with line breaks, et all. While not everyone uses description_formatted, the object is being saved since that's what's being shown in the Mylar GUI. The field name in the json has no bearing on actual Mylar usage. We could just drop the text wording, and leave the formatted as is ? 
- Are you planning on editing the json directly and thus the need to not overwrite ? I'm guessing you're renaming the ```description_text``` field in the json to just ```description``` and then when it writes a new one it hammer.

**Comment by scooterpsu** [comment]
Since adding support for `description`, `description_text` and `description_formatted` makes more sense on the use-side, I pushed an update to my Ubooquity skin [here](https://github.com/scooterpsu/Comixology_Ubooquity_2/releases/tag/v3.5.1).

**Comment by evilhero** [comment]
@scooterpsu I remembered you mentioning that the other day. What I was meaning about the description is to just rename ```description_text``` to ```description```, which might break your recent pushes to your branch?

**Comment by scooterpsu** [comment]
@evilhero Since I wasn't looking to remake all of my existing files, my current script checks for all 3. So there'd be no harm in renaming `description_text` to `description` or leave it as-is.

Currently `description_formatted` overwrites `description_text` which overwrites `description`.

**Comment by Budlyte** [comment]
I believe Scott's newest branch now supports all 3 options, so that solves the issue of `description_text`. I just tested his update and it works great. - I know you guys covered this, but I've had a lot of this written up and needed to complete my testing before hitting "Comment".

That's a real bummer about CV's API returning smaller thumbnails than what it throws on their webpage. Nothing we can do about that one if that's what they give though. 

The current issue with series.json overwriting existing files is that if a series exists in a folder, but not Mylar, and already has a series.json file, then when it is imported into Mylar it wipes out the old file for a new series.json and may actually have less info.

**Comment by evilhero** [comment]
I think if we load the json upon loading the Serie detail page, it will show as the description. If it gets edit or changed it will get written out. If it doesn't change, it won't overwrite (or if it does it'll be the same thing).

Does that sound feasible to you guys? (sorry, in a drive -thru atm so just brainstorming)

**Comment by Budlyte** [comment]
Here's my attempt.  This should:
- Check for the existence of series.json
- parse it for an existing 'description'
- set it to a variable
- use that variable in the 'description_text' to be used in the metadata section

--- Need to import configparser, it's all I've ever used and only know how. The rest goes around line 7072 in webserve.py.  

`import configparser

            metadata = {}
            metaread = configparser.ConfigParser()
            if not os.path.exists(os.path.join(comic['ComicLocation']), 'series.json'):
                write_file()
            metaread.read('series.json')
            try:
                self.read_description = (metaread['metadata']['description'])
            except:
                self.read_description = cdes_removed
            finally:
                metadata['metadata'] = [(
                                        {'type': 'comicSeries',
                                         'publisher': comic['ComicPublisher'],
                                         'imprint': comic['PublisherImprint'],
                                         'name': comic['ComicName'],
                                         'comicid': comicid,
                                         'year': SeriesYear,
                                         'description_text': self.read_description,
                                         'description_formatted': cdes_formatted,
                                         'volume': comicVol,
                                         'booktype': booktype,
                                         'collects': clean_issue_list,
                                         'ComicImage': comic['ComicImageURL'],
                                         'total_issues': comic['Total'],
                                         'publication_run': comic['ComicPublished'],
                                         'status': seriesStatus}
                )]
            try:
                with open(os.path.join(comic['ComicLocation'], 'series.json'), 'w', encoding='utf-8') as outfile:
                    json.dump(metadata, outfile, indent=4, ensure_ascii=False)
            except Exception as e:
                logger.error('Unable to write series.json to %s. Error returned: %s' % (comic['ComicLocation'], e))
            else:
                logger.fdebug('Successfully written series.json file to %s' % comic['ComicLocation'])`

**Comment by evilhero** [comment]
Yeah you don't need configparser - since the series.json is valid json you can just do a json.load(filename) to load it into a dictionary.

But I'll run this thru in a bit, just getting the kids to do something other than fight each other.

**Comment by evilhero** [comment]
Give that fix a try if you guys are on the python3-dev branch. It should address your concerns about the pre-existing description field being over-written, however it still uses the ```description_text``` naming within the json (forgot to change that but it's also what I used to determine if it'a s pre-existing json vs one that Mylar generated).

If it works as intended, we'll look into adding the checks for more data points aside from just the description (cause ya know it's going to come up at some point)

**Comment by scooterpsu** [comment]
I copied over an old series.json for a totally different series, refreshed the comic in Mylar and it rebuilt the json using the test description. So this works 100% as expected now.

I can't imagine why anyone would want to mess with the other fields, but who knows what sort of weird use cases there might be out there.

**Comment by Budlyte** [comment]
Tested it as well, and while it tripped me up at first, it does take the value of "description" of and apply it to "description_text" & "description_formatted".  Thank you, so much!

**Comment by arqcan** [comment]
I thought i'd add to this, i've tried to add a comics that already has a folder and series.json file however i get the following error;

500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\Programs\Mylar\mylar\webserve.py", line 285, in comicDetails
    if os.path.exists(os.path.join(comic['ComicLocation'], 'series.json')):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\ntpath.py", line 78, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

however the comics does get added to the database after the error, thought it was worth mentioning.

**Comment by evilhero** [comment]
@arqcan, it says you don't have a Comic Location path set - are you waiting for the series to finish being added before clicking on the series.json indicator? 

I'm guessing that it's still in a Loading status, so the path has generated yet and you clicked on the series.json and it threw that error - since that error is from the clickable aspect, and not the actual adding of the series.

**Comment by Budlyte** [comment]
This occurs when up clicking "Add to Library" for any new comic, not something I thought to try after the changes, it lands on the "500 Internal Server Error" page. The comic does populate you just have to go back navigate to it, the automatic redirect doesn't work.

Huh, the last couple of lines of ours are different...  This is after I pulled the Dev branch yesterday.

Traceback (most recent call last):
  File "C:\Users\xbmc\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "C:\Users\xbmc\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "C:\Users\xbmc\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Users\xbmc\AppData\Local\Programs\Python\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Users\xbmc\Desktop\Mylar\mylar3-0.5.0-dev\mylar\webserve.py", line 279, in comicDetails
    if os.path.exists(os.path.join(comic['ComicLocation'], 'series.json')):
  File "C:\Users\xbmc\AppData\Local\Programs\Python\Python37\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by arqcan** [comment]
Yeah, its after i click on "Add to Library" from a search for new comics. It just so happened the one I was trying to add had a series.json file already in place.

**Comment by barbequesauce** [comment]
Closing due to staleness, we welcome contributions for new features. If this is an issue and you are still experiencing it, please open a new ticket with a care package attached.
