### ISSUE TITLE
Newznab search not looking extensively for different issue numbers

### ISSUE THREAD

**Issue by gympickle** [mylar3/mylar3#689]
**Describe the bug**

I'm trying to use NZBGeek as a newsnav provider and noticed that I wasn't getting any results through there.
I enabled verbose and investigated a bit and found out that we are looking the format for the search was not correct.

This is an example search:

`https://api.nzbgeek.info/api?t=search&q=strange%20adventures%20007&o=xml&cat=7030&apikey=MY_API_KEY`

which basically searches for `strange adventures 007` even though most of the comics on NZBGeek are using only double digits. If I modify the search to:

`https://api.nzbgeek.info/api?t=search&q=strange%20adventures%2007&o=xml&cat=7030&apikey=MY_API_KEY`

Then I actually can see results. I notice we have this behaviour already in the experimental search. Can we add it to the Newznab stuff ? This is probably the source of #685 .

**Environment (please complete the following information):**
 - OS: raspberry
 - Branch / commit: linux docker image

**Comment by evilhero** [comment]
Mylar iterates thru all iterations of the padding depending on the number (```7```,```07```,```007```), but it has to stagger the queries to each provider by 60s so it could take from 3 mins upwards to get results (if you have alternate search names, or there are special characters in the series name)

This has been in Mylar for the past decade, so there's nothing to add. If you're not getting search results, you probably have an error /traceback related to the search and why it's failing in your logs.if you ha e Experimental enabled as a provider, you probably need to disable it, as it's been causing problems for the past few weeks due to either them temp banning users for hammering, throttling users, or just general timeouts.

**Comment by gympickle** [comment]
```
31-Mar-2021 15:19:30 - INFO    :: mylar.search_init.633 : SEARCH-QUEUE : Could not find Issue 8 of Strange Adventures (2020) using DDL [rss]
31-Mar-2021 15:19:30 - DEBUG   :: mylar.search_init.355 : SEARCH-QUEUE : Initiating Search via : api
31-Mar-2021 15:19:30 - DEBUG   :: mylar.NZB_SEARCH.775 : SEARCH-QUEUE : Using Newznab host of : NZBgeek
31-Mar-2021 15:19:30 - INFO    :: mylar.NZB_SEARCH.807 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Strange Adventures issue: 8 (2021) using NZBgeek (newznab).
31-Mar-2021 15:19:30 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : findloop: 0 / findcount: 1
31-Mar-2021 15:19:30 - INFO    :: mylar.NZB_SEARCH.1126 : SEARCH-QUEUE : Pausing for 60 seconds before continuing to avoid hammering.
31-Mar-2021 15:19:30 - DEBUG   :: mylar.NZB_SEARCH.1151 : SEARCH-QUEUE : [SSL: True] Search URL: https://api.nzbgeek.info/api?t=search&q=strange%20adventures%20008&o=xml&cat=7030&apikey=MYAPIKEY
31-Mar-2021 15:19:34 - DEBUG   :: mylar.NZB_SEARCH.1263 : SEARCH-QUEUE : no errors on data retrieval...proceeding
31-Mar-2021 15:19:34 - DEBUG   :: mylar.NZB_SEARCH.2494 : SEARCH-QUEUE : booktype:Print / chktpb: 0 / findloop: 0
31-Mar-2021 15:19:34 - INFO    :: mylar.search_init.633 : SEARCH-QUEUE : Could not find Issue 8 of Strange Adventures (2020) using NZBgeek [api]
31-Mar-2021 15:19:34 - INFO    :: mylar.NZB_SEARCH.807 : SEARCH-QUEUE : Shhh be very quiet...I'm looking for Strange Adventures issue: 8 (2021) using experimental.
31-Mar-2021 15:19:34 - DEBUG   :: mylar.NZB_SEARCH.867 : SEARCH-QUEUE : findloop: 0 / findcount: 1
31-Mar-2021 15:19:34 - INFO    :: mylar.NZB_SEARCH.1266 : SEARCH-QUEUE : sending Strange Adventures to experimental search
31-Mar-2021 15:19:34 - DEBUG   :: mylar.Startit.93 : SEARCH-QUEUE : Now searching experimental for issue number: 8 to try and ensure all the bases are covered
31-Mar-2021 15:19:39 - DEBUG   :: mylar.Startit.93 : SEARCH-QUEUE : Now searching experimental for issue number: 08 to try and ensure all the bases are covered
31-Mar-2021 15:19:45 - DEBUG   :: mylar.Startit.93 : SEARCH-QUEUE : Now searching experimental for issue number: 008 to try and ensure all the bases are covered
31-Mar-2021 15:19:50 - ERROR   :: mylar.searchforissue.3198 : SEARCH-QUEUE : Traceback (most recent call last):
31-Mar-2021 15:19:50 - ERROR   :: mylar.searchforissue.3198 : SEARCH-QUEUE : Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 156, in __getattr__
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 65, in __getitem__
    for link in dict.__getitem__(self, 'links')
KeyError: 'links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3126, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 1267, in NZB_SEARCH
    bb = findcomicfeed.Startit(
  File "/app/mylar3/mylar/findcomicfeed.py", line 122, in Startit
    urlParse = feed.entries[countUp].enclosures[0]
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 158, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'enclosures'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 156, in __getattr__
    return self.__getitem__(key)
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 65, in __getitem__
    for link in dict.__getitem__(self, 'links')
KeyError: 'links'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/mylar3/mylar/search.py", line 3126, in searchforissue
    foundNZB, prov = search_init(
  File "/app/mylar3/mylar/search.py", line 520, in search_init
    findit = NZB_SEARCH(
  File "/app/mylar3/mylar/search.py", line 1267, in NZB_SEARCH
    bb = findcomicfeed.Startit(
  File "/app/mylar3/mylar/findcomicfeed.py", line 122, in Startit
    urlParse = feed.entries[countUp].enclosures[0]
  File "/usr/lib/python3.8/site-packages/feedparser/util.py", line 158, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'enclosures'

```

does experimental fail make the whole search fails too ?

**Comment by evilhero** [comment]
It makes it fail for that particular issue search, yes. It'll search subsequent series that are wanted, but it'll throw the same error and appear as if it's not searching, especially if experimental is listed before your other providers in the search provider order within Mylar.

Like I said ( as well as in #670 where this was brought up as well), remove experimental and you won't have any searching problems. It's labelled as experimental for a reason, that it can break at any time and no idea if it can be resolved (as it's not our site, and it has no API to hit).

Looking into a fix, but since it involves parsing the rss which can be rate limited, it makes it difficult to pinpoint if it's a timing issue vs something else.

**Comment by barbequesauce** [comment]
Did that last dev commit solve the issue?

**Comment by evilhero** [comment]
stale. and probably fixed.
