### ISSUE TITLE
Installation hiccups [win10, building via CLI]

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#75]
**Describe the bug**
error when running pip install -r requirements.txt

**Screenshots/Logs**
I don't know where logs are even dumped at this point in the install, sorry.

``

> C:\ProgramData\mylar3>pip install -r requirements.txt
Collecting APScheduler>=3.6.3
  Using cached APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
Collecting beautifulsoup4>=4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting cfscrape>=2.0.8
  Using cached cfscrape-2.0.8-py3-none-any.whl (11 kB)
Collecting cheroot==8.2.1
  Using cached cheroot-8.2.1-py2.py3-none-any.whl (79 kB)
Collecting CherryPy>=18.5.0
  Using cached CherryPy-18.5.0-py2.py3-none-any.whl (418 kB)
Collecting configparser>=4.0.2
  Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting feedparser>=5.2.1
  Using cached feedparser-5.2.1.tar.bz2 (192 kB)
Collecting Mako>=1.1.0
  Using cached Mako-1.1.1.tar.gz (468 kB)
Collecting natsort>=3.5.2
  Using cached natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting Pillow>=7.0.0
  Using cached Pillow-7.0.0-cp38-cp38-win_amd64.whl (2.0 MB)
Collecting portend>=2.6
  Using cached portend-2.6-py2.py3-none-any.whl (5.1 kB)
Collecting pyinstaller>=3.5
  Using cached PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting PyPDF2>=1.24
  Using cached PyPDF2-1.26.0.tar.gz (77 kB)
Collecting PyQt5==5.12.2
  Using cached PyQt5-5.12.2-5.12.3-cp35.cp36.cp37.cp38-none-win_amd64.whl (47.5 MB)
Collecting PyQt5-sip==12.7.0
  Using cached PyQt5_sip-12.7.0-cp38-cp38-win_amd64.whl (59 kB)
Collecting pytz>=2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting requests>=2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting simplejson>=3.17.0
  Using cached simplejson-3.17.0.tar.gz (83 kB)
Collecting six>=1.13.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting tzlocal>=2.0.0
  Using cached tzlocal-2.0.0-py2.py3-none-any.whl (15 kB)
Collecting unrar>=0.3
  Using cached unrar-0.4-py3-none-any.whl (25 kB)
Collecting unrar-cffi==0.1.0a5
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-bbe_rqos\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-bbe_rqos\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nicholas\AppData\Local\Temp\pip-install-bbe_rqos\unrar-cffi\pip-egg-info'
         cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-install-bbe_rqos\unrar-cffi\
    Complete output (107 lines):
    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Nicholas\AppData\Local\Temp\easy_install-pk94ezb5\cffi-1.14.0\setup.py", line 127, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\easy_install-pk94ezb5\cffi-1.14.0\setup.py", line 105, in uses_msvc
      File "c:\python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\pip-install-bbe_rqos\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Nicholas\AppData\Local\Temp\easy_install-pk94ezb5\cffi-1.14.0\setup.py", line 127, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\easy_install-pk94ezb5\cffi-1.14.0\setup.py", line 105, in uses_msvc
      File "c:\python38\lib\distutils\command\config.py", line 225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\python38\lib\distutils\command\config.py", line 132, in _compile
        self.compiler.compile([src], include_dirs=include_dirs)
      File "c:\python38\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

``

**Environment (please complete the following information):**
 - OS: Win10-64
 - Branch / commit: python3-dev, 47d0bde

**Additional information**
Grabbed python-2.7.17.amd64.msi and python-3.8.1-amd64.exe to update 2.7 and install 3.x.  Confirmed 'python' command was calling 3.x and not 2.7.  Updated pip.  Ran 'pip install -r requirements.txt' and errors.

Tried to manually grab and install MSVC++ runtime from the URL it spat out (it was already installed but hey who knows), ran pip again.  Error.  Tried reinstalling pythin 3.8, ran pip again.  Error.

**Comment by Bart274** [comment]
@professionaltart can you check whether or not the location of the msvc++ is in your path?

**Comment by evilhero** [comment]
Try updating setuptools first maybe : ```pip install --upgrade setuptools```, and if that doesn't work you might have to download the visual build tools for VS2017 - I don't think that link in the error works correctly however.

**Comment by professionaltart** [comment]
@Bart274 path contains AppData\Local\Programs\Microsoft VS Code\bin in my local user path, which looks close but not quite right.  Nothing in my global path.  

@evilhero, I upgraded setuptools, from 41.2.0 to 45.2.0, but I still get to the same section, just after unrar-cffi==0.1.0a5, when it spits errors again.  Different errors, this time:

>    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-4k_8ue7g\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-4k_8ue7g\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nicholas\AppData\Local\Temp\pip-install-4k_8ue7g\unrar-cffi\pip-egg-info'
         cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-install-4k_8ue7g\unrar-cffi\
    Complete output (48 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: 'c:\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-wheel-3yq_nb2g\\pycparser\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-wheel-3yq_nb2g\\pycparser\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Nicholas\AppData\Local\Temp\pip-wheel-omeifbzv'
           cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-wheel-3yq_nb2g\pycparser\
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pycparser
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "c:\python38\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\python38\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\tmpesyh10bh', '--quiet', 'pycparser']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\pip-install-4k_8ue7g\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "c:\python38\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
        return installer(requirement)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\python38\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['c:\\python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\tmpesyh10bh', '--quiet', 'pycparser']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by professionaltart** [comment]
after pip install wheel, it's down to one error:

>Collecting unrar-cffi==0.1.0a5
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-optxp_5g\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-optxp_5g\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nicholas\AppData\Local\Temp\pip-install-optxp_5g\unrar-cffi\pip-egg-info'
         cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-install-optxp_5g\unrar-cffi\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\pip-install-optxp_5g\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\python38\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "c:\python38\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\nicholas\appdata\local\temp\pip-install-optxp_5g\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\nicholas\appdata\local\temp\pip-install-optxp_5g\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "c:\python38\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "c:\python38\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\python38\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by professionaltart** [comment]
C:\ProgramData\mylar3>pip uninstall -r requirements.txt

>WARNING: Skipping APScheduler as it is not installed.
WARNING: Skipping beautifulsoup4 as it is not installed.
WARNING: Skipping cfscrape as it is not installed.
WARNING: Skipping cheroot as it is not installed.
WARNING: Skipping CherryPy as it is not installed.
WARNING: Skipping configparser as it is not installed.
WARNING: Skipping feedparser as it is not installed.
WARNING: Skipping Mako as it is not installed.
WARNING: Skipping natsort as it is not installed.
WARNING: Skipping Pillow as it is not installed.
WARNING: Skipping portend as it is not installed.
WARNING: Skipping pyinstaller as it is not installed.
WARNING: Skipping PyPDF2 as it is not installed.
WARNING: Skipping PyQt5 as it is not installed.
WARNING: Skipping PyQt5-sip as it is not installed.
WARNING: Skipping pytz as it is not installed.
WARNING: Skipping requests as it is not installed.
WARNING: Skipping simplejson as it is not installed.
WARNING: Skipping six as it is not installed.
WARNING: Skipping tzlocal as it is not installed.
WARNING: Skipping unrar as it is not installed.
WARNING: Skipping unrar-cffi as it is not installed.
WARNING: Skipping urllib3 as it is not installed.

C:\ProgramData\mylar3>pip install -r requirements.txt
>Collecting APScheduler>=3.6.3
  Using cached APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
Collecting beautifulsoup4>=4.8.2
  Using cached beautifulsoup4-4.8.2-py3-none-any.whl (106 kB)
Collecting cfscrape>=2.0.8
  Using cached cfscrape-2.0.8-py3-none-any.whl (11 kB)
Collecting cheroot==8.2.1
  Using cached cheroot-8.2.1-py2.py3-none-any.whl (79 kB)
Collecting CherryPy>=18.5.0
  Using cached CherryPy-18.5.0-py2.py3-none-any.whl (418 kB)
Collecting configparser>=4.0.2
  Using cached configparser-4.0.2-py2.py3-none-any.whl (22 kB)
Collecting feedparser>=5.2.1
  Using cached feedparser-5.2.1.tar.bz2 (192 kB)
Collecting Mako>=1.1.0
  Using cached Mako-1.1.1.tar.gz (468 kB)
Collecting natsort>=3.5.2
  Using cached natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting Pillow>=7.0.0
  Using cached Pillow-7.0.0-cp38-cp38-win_amd64.whl (2.0 MB)
Collecting portend>=2.6
  Using cached portend-2.6-py2.py3-none-any.whl (5.1 kB)
Collecting pyinstaller>=3.5
  Using cached PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting PyPDF2>=1.24
  Using cached PyPDF2-1.26.0.tar.gz (77 kB)
Collecting PyQt5==5.12.2
  Using cached PyQt5-5.12.2-5.12.3-cp35.cp36.cp37.cp38-none-win_amd64.whl (47.5 MB)
Collecting PyQt5-sip==12.7.0
  Using cached PyQt5_sip-12.7.0-cp38-cp38-win_amd64.whl (59 kB)
Collecting pytz>=2019.3
  Using cached pytz-2019.3-py2.py3-none-any.whl (509 kB)
Collecting requests>=2.22.0
  Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)
Collecting simplejson>=3.17.0
  Using cached simplejson-3.17.0.tar.gz (83 kB)
Collecting six>=1.13.0
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting tzlocal>=2.0.0
  Using cached tzlocal-2.0.0-py2.py3-none-any.whl (15 kB)
Collecting unrar>=0.3
  Using cached unrar-0.4-py3-none-any.whl (25 kB)
Collecting unrar-cffi==0.1.0a5
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)

so far so good, (and then):
>    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-7sa0saf_\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-7sa0saf_\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nicholas\AppData\Local\Temp\pip-install-7sa0saf_\unrar-cffi\pip-egg-info'
         cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-install-7sa0saf_\unrar-cffi\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\pip-install-7sa0saf_\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\python38\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "c:\python38\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\nicholas\appdata\local\temp\pip-install-7sa0saf_\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\nicholas\appdata\local\temp\pip-install-7sa0saf_\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "c:\python38\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "c:\python38\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\python38\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by professionaltart** [comment]
Installed VSC++ runtime, VS Community 2019 with python dev module, and VS build tools 2019 with c++ and .net desktop build tools.

C:\ProgramData\mylar3>pip install unrar-cffi
>Collecting unrar-cffi
  Using cached unrar-cffi-0.1.0a5.tar.gz (253 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-z0bsig7k\\unrar-cffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\Nicholas\\AppData\\Local\\Temp\\pip-install-z0bsig7k\\unrar-cffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Nicholas\AppData\Local\Temp\pip-install-z0bsig7k\unrar-cffi\pip-egg-info'
         cwd: C:\Users\Nicholas\AppData\Local\Temp\pip-install-z0bsig7k\unrar-cffi\
    Complete output (31 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Nicholas\AppData\Local\Temp\pip-install-z0bsig7k\unrar-cffi\setup.py", line 14, in <module>
        setup(
      File "c:\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\python38\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "c:\python38\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "c:\python38\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "c:\users\nicholas\appdata\local\temp\pip-install-z0bsig7k\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "c:\users\nicholas\appdata\local\temp\pip-install-z0bsig7k\unrar-cffi\.eggs\cffi-1.14.0-py3.8-win-amd64.egg\cffi\setuptools_ext.py", line 57, in add_cffi_module
        ffi = ffi()      # maybe it's a function instead of directly an ffi
      File "buildconf.py", line 77, in create_builder
        preprocess = subprocess.check_output(PREPROCESS_CMD, universal_newlines=True)
      File "c:\python38\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "c:\python38\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "c:\python38\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\python38\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Also, for posterity:

>C:\ProgramData\mylar3>pip install unrar_cffi-0.1.0a5-cp37-cp37m-win_amd64.whl
ERROR: unrar_cffi-0.1.0a5-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

**Comment by professionaltart** [comment]
Install python 3.7.6
``git clone https://github.com/mylar3/mylar3.git -b python3-dev c:\programdata\Mylar3
``cd c:\programdata\Mylar3
``python -m pip install --upgrade pip
``pip install -r requirements.txt

...I think that should get it going, for Win10-64, for anyone else having issues.

Still NFI why unrar-cffi won't build on 3.8.1
