### ISSUE TITLE
Care Package failure

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#80]
**Describe the bug**
Carepackage button broken, possibly only within windows?

**CarePackage**
haha.  Nope.

http://localhost:8090/mylar/carepackage gives:

> 500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "c:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\ProgramData\mylar3\mylar\webserve.py", line 5606, in carepackage
    from mylar.carepackage import carePackage
  File "c:\ProgramData\mylar3\mylar\carepackage.py", line 213
    if path.exists(self.lastrelpath)
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
Powered by CherryPy 18.5.0

Log with debug enabled shows nothing for hitting the button and getting the error.

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: Dev/build 9246809

**Additional information**
Ticket as per @barbequesauce  request on irc.

There is no archive generated and downloaded by the browser.

The only log generated while replicating is when clicking on the gear icon to load /config:

> 

2020-02-12 02:29:53 | DEBUG | Git  output: CompletedProcess(args='git log --encoding=UTF-8  --pretty=format:"%h - %cr - %an - %s" -n 5', returncode=0,  stdout='9246809 - 17 hours ago - evilhero - Merge pull request #78 from  mylar3/updated_readme_for_windows\n395a323 - 17 hours ago - evilhero -  updated README.md to include python version limitation when running on  Windows systems\nf3d4da1 - 19 hours ago - Barbeque Sauce - Merge pull  request #77 from mylar3/git-stderr-for-everybody\n1b8ee87 - 19 hours ago  - Barbeque Sauce - Fixing how we handle git output, reduce false  alarms\n3946f55 - 23 hours ago - Barbeque Sauce - Merge pull request #76  from mylar3/readme', stderr='')
-- | -- | --
2020-02-12 02:29:53 | DEBUG | Trying to execute: git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 with shell in c:\ProgramData\mylar3

**Comment by barbequesauce** [comment]
fixed in #84

**Comment by professionaltart** [comment]
Good news, it takes slightly longer before the error pops up?

Dev, [661bb57] (latest build)

>500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "c:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\ProgramData\mylar3\mylar\webserve.py", line 5607, in carepackage
    cp = carePackage()
  File "c:\ProgramData\mylar3\mylar\carepackage.py", line 27, in __init__
    self.panicbutton()
  File "c:\ProgramData\mylar3\mylar\carepackage.py", line 213, in panicbutton
    if path.exists(self.lastrelpath):
NameError: name 'path' is not defined
