### ISSUE TITLE
UI slowness/page load times

### ISSUE THREAD

**Issue by professionaltart** [mylar3/mylar3#81]
**Describe the bug**
Slow page-loads when RSS Feeds being parsed

**CarePackage**
No CP as per other ticket, but also nothing in the debug logs.

**Environment (please complete the following information):**
 - OS: Win10-64
 - Branch / commit: Dev/build 9246809

**Additional information**
Manage and Logs both load quickly.  All other links across the top take considerable time to load.
After pausing RSS, pages still unresponsive (30+s sometimes).  After restarting Mylar, pages once more load quickly.

Attempts to repro:
Manually force start RSS feed scan via http://localhost:8090/mylar/manage
First few minutes so far and UI is responsive as expected.
CPU activity as per Task Manager is less spike-y than when having to manually restart mylar.
Cropped from debug logs:

>12-Feb-2020 02:31:48 - INFO    :: mylar.clearLogs.3997 : CP Server Thread-11 : Web logs cleared
12-Feb-2020 02:32:11 - INFO    :: mylar.schedulerForceCheck.2642 : CP Server Thread-8 : [RSS Feeds (trigger: interval[0:30:00], next run at: 2020-02-11 15:39:26 UTC)] Now force submitting job for jobid rss
12-Feb-2020 02:32:11 - INFO    :: mylar.run.37 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] RSS Feed Check Initalizing....
12-Feb-2020 02:32:11 - INFO    :: mylar.run.92 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] Initiating RSS Feed Check for NZB Providers.
12-Feb-2020 02:32:11 - DEBUG   :: mylar.nzbs.500 : ThreadPoolExecutor-0_3 : [RSS] You have enabled 1 NZB RSS search providers.
12-Feb-2020 02:32:11 - DEBUG   :: mylar._parse_feed.466 : ThreadPoolExecutor-0_3 : [RSS] Fetching items from nzbHydra2
12-Feb-2020 02:32:11 - DEBUG   :: mylar.nzbs.573 : ThreadPoolExecutor-0_3 : [RSS] (nzbHydra2) now being updated...
12-Feb-2020 02:32:11 - INFO    :: mylar.nzbs.605 : ThreadPoolExecutor-0_3 : [RSS] (nzbHydra2) 0 entries indexed.
12-Feb-2020 02:32:11 - INFO    :: mylar.run.97 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] RSS Feed Check/Update Complete
12-Feb-2020 02:32:11 - INFO    :: mylar.run.98 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] Watchlist Check for new Releases
12-Feb-2020 02:32:11 - INFO    :: mylar.searchforissue.1608 : ThreadPoolExecutor-0_3 : Initiating RSS Search Scan at the scheduled interval of 30 minutes
12-Feb-2020 02:32:11 - INFO    :: mylar.searchforissue.1660 : ThreadPoolExecutor-0_3 : Storyarcs to be searched for : 219

...snip...

>12-Feb-2020 02:32:51 - INFO    :: mylar.searchforissue.1774 : ThreadPoolExecutor-0_3 : Completed RSS Search scan
12-Feb-2020 02:32:51 - INFO    :: mylar.run.100 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] Watchlist Check complete.
12-Feb-2020 02:32:51 - INFO    :: mylar.run.102 : ThreadPoolExecutor-0_3 : [RSS-FEEDS] Successfully ran a forced RSS Check.
12-Feb-2020 02:32:51 - DEBUG   :: mylar.job_management.3549 : ThreadPoolExecutor-0_3 : ReScheduled job: RSS Feeds to 2020-02-11 16:02:51

When the RSS feed scan is called automatically, sometimes it runs fine but also sometimes it feels like it takes much longer than 40 seconds - these are the times when the web UI for mylar tends to grind, and CPU usage is more aggressive.

I had this issue in the 2.7 version, too, and would need to manually restart mylar a few times a week for it to actually grab comics and behave.  Well, something similar.

Quick look at a log file - a full 10mb one - makes it seem like, until I paused and restarted mylar - it had been going for ~20 minutes.

**Comment by professionaltart** [comment]
Just waited 30 mins for it to do a scheduled start, and it happened as fast as the most recent manual start.

Will see how it's responding after i wake up, and it's had a few hours to do it's thing over and over.

**Comment by professionaltart** [comment]
After a reboot, I noticed the CPU spike - those couple of cores going up down like that happens whenever mylar seems to 'do that thing'.  After clearing out RSS from the db yesterday, it seemed to behave.  In /manage, it was showing the auto-search as active until I hit pause (perhaps a few too many times)

![image](https://user-images.githubusercontent.com/28383689/74459029-b84d4780-4ede-11ea-86e3-99c246b4aa77.png)
![image](https://user-images.githubusercontent.com/28383689/74459038-bd11fb80-4ede-11ea-88f4-03f523491c4b.png)
Normal/almost instant page loads for eg /logs, but ~24s load times for eg /config.  Just confirmed with new edge/chromium, similar issues wrt load times.

[carepackage.zip](https://github.com/mylar3/mylar3/files/4199725/carepackage.zip)

**Comment by professionaltart** [comment]
Fresh care package after sleeping most of the day and noticing it doing 'the thing' again.

Also, some attempts at gathering metrics from dev console in ff and edge.

[carepackage(1).zip](https://github.com/mylar3/mylar3/files/4203066/carepackage.1.zip)
[edge.zip](https://github.com/mylar3/mylar3/files/4203068/edge.zip)
[firefox.zip](https://github.com/mylar3/mylar3/files/4203069/firefox.zip)

**Comment by barbequesauce** [comment]
From the performance graphs, it's definitely a server-side thing (despite my wanting to hate on Edge) - look at this:
<img width="336" alt="Screen Shot 2020-02-14 at 12 07 11 PM" src="https://user-images.githubusercontent.com/25070944/74552150-94abf080-4f22-11ea-8e26-451d9b1c4692.png">
The red circle is showing that you're waiting for a response... and once it's received the browser  processes it quick.

Looking at the log, it seems it is still processing an rss search when the new thread is kicked off.. so you wind up with backlogs of searches on top of each other. This isnt surprising given the number of items on your wanted list.

Try changing your RSS search interval to something less aggressive, from 30 minutes to maybe 300 just for giggles, to see how it behaves overnight.

**Comment by professionaltart** [comment]
[carepackage(0).zip](https://github.com/mylar3/mylar3/files/4224172/carepackage.0.zip)
I haven't been home in the past ~5 days, and I know Win10 did at least one restart for updates, but from the few times I've checked in to see if anything new (and interesting looking) is coming out this week, the UI has responded as I'd expect, and the logs look like there's periods of actual inactivity, after setting RSS search from 30 to 300 mins.

Unsure if this is just an edgecase of too many wanted things going on, given the (from memory) default timing intervals, or was something else.

**Comment by professionaltart** [comment]
[carepackage(3).zip](https://github.com/mylar3/mylar3/files/4225139/carepackage.3.zip)
Getting ready for bed and notice that CPU utilisation is showing pattern again in task manager.  Check Process tab and it shows 'python' is the highest process sorted by CPU usage.  Restart Mylar - which log showed was not really doing much of anything - and CPU usage is back to flat 🤷‍♀️

I'll have a poke around tomorrow if I get some time and make sure SAB isn't weirding out too much with python3 installed (it's been paused for the last handful of hours, FWIW) and making mylar look bad.

**Comment by professionaltart** [comment]
Not sure what's going on.  Mylar did RSS scan or something, I noticed pull list/CV has updated, so manually trigger searches for the new issues, RSS scan finishes, DB updates, it's seemingly doing nothing else but not getting my new comics.  RSS feed says it's still running.  

/config page is getting slower to load up again, tho' as soon as I click to open it, the logs show the git output trigger a good 10+ seconds before it actually loads.

Is a memory dump of the python running with high CPU usage at all useful?

[carepackage(4).zip](https://github.com/mylar3/mylar3/files/4229568/carepackage.4.zip)

**Comment by barbequesauce** [comment]
I'm entirely lost on what is happening here now that we're past overrunning RSS checks. Hopefully someone else will have their lightbulb light up...

**Comment by evilhero** [comment]
So the RSS thing returning 0 results is due to how Mylar is querying nzbhydra - by default it polls against the /rss, but in order for it to return results it has to be against the /api (or something like that).  What you can do to get the RSS to actually return results, is to add ```[nzbhydra]``` to the end of the provider name within Mylar, so it would look like this for Newznab Name: ```nzbHydra2 [nzbhydra]```.

As far as providers you have within your nzbhdyra2 instance - can you provide which ones you have ? I tested against an nzb provider within nzbhydra2 and it came back fine when I did the addition above. I'm wondering if you might have some torrent providers within your nzbhydra instance (or perhaps you have a jacket instance attached to your nzbhydra) - which might be confusing the responses expected since newznab is only for nzbs.

**Comment by barbequesauce** [comment]
@professionaltart closing this due to inactivity - please feel free to reopen when you have an update.

**Comment by professionaltart** [comment]
Sorry, crazy past month. 

I've updated the name of the search entry as suggested. I'll update in a few days when I see how the server is behaving when left to its own devices. 

Only thing to note so far is that the 'test' button for the search entry doesn't seem to work. Not saying it's related to the rename, I don't test it very often, but it gives no feedback and no log entry.

**Comment by barbequesauce** [comment]
There was a lot of work done around torznabs - including that pesky test button - since 9246809 (the commit you started this issue under). If you havent updated recently, you probably should...

**Comment by professionaltart** [comment]
Yep, I updated and tried again, same result. 
Testing download client responds and appears in logs, not for search client. 
From memory/my expectation is it'd be a similar entry/process to the download client: contacts search, sends API key, shows whether it's accepted or rejected. 

Minor issue, anyway. Will see if the torznab changes and explicit tagging of nzbhydra resolve this!

**Comment by professionaltart** [comment]
I haven't been home for a few days, so I guess the last restart may've been the last update, around 5 days ago (  Version: 2b4a14e90beffa6587fc5fd8ad3adbec23598abd (python3-dev)  )
~30 seconds to load up non-log pages.

For what it's worth:

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last):
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 638, in respond
    self._do_respond(path_info)
  File "c:\Python37\lib\site-packages\cherrypy\_cprequest.py", line 697, in _do_respond
    response.body = self.handler()
  File "c:\Python37\lib\site-packages\cherrypy\lib\encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Python37\lib\site-packages\cherrypy\_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\ProgramData\mylar3\mylar\webserve.py", line 5647, in carepackage
    cp = carePackage()
  File "c:\ProgramData\mylar3\mylar\carepackage.py", line 86, in __init__
    self.panicbutton()
  File "c:\ProgramData\mylar3\mylar\carepackage.py", line 296, in panicbutton
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\ProgramData\\mylar3\\logs\\carepackage\\mylar.log'
```

See also:
```
2020-03-26 20:58:26 | DEBUG | removed 71997 keys from C:\ProgramData\mylar3\logs\mylar.log
-- | -- | --
2020-03-26 20:58:25 | DEBUG | analyzing C:\ProgramData\mylar3\logs\mylar.log
2020-03-26 20:58:25 | DEBUG | Configuration cleaned of keys/passwords and written to temporary location.
2020-03-26 20:58:19 | INFO | config file has been loaded from: c:\ProgramData\mylar3\config.ini
2020-03-26 20:58:19 | DEBUG | If you can read this message, debug logging is now working
2020-03-26 20:58:19 | INFO | Verbose (DEBUG) logging is enabled
2020-03-26 20:58:18 | INFO | Web logs cleared
```

Same error on older and latest build.

I'm kind of mitigating around the issue for now by the fact that I only really care about checking Mylar near the weekend, and there's still a lot of dev builds coming out that force a restart.

**Comment by professionaltart** [comment]
[carepackage.zip](https://github.com/mylar3/mylar3/files/4392689/carepackage.zip)
Didn't even think to check for the archive in the folder, d'oh.

Just pulled to latest build, I'll be home this weekend to pay a bit more attention to when it's taking forever to load pages again.

**Comment by professionaltart** [comment]
>
> 
> As far as providers you have within your nzbhdyra2 instance - can you provide which ones you have ? I tested against an nzb provider within nzbhydra2 and it came back fine when I did the addition above. I'm wondering if you might have some torrent providers within your nzbhydra instance (or perhaps you have a jacket instance attached to your nzbhydra) - which might be confusing the responses expected since newznab is only for nzbs.

Sorry @evilhero , I forgot this bit of info - in Hydra2, I'm running the following indexers: 
nzb.su
nzbgeek
revott and tpb via jackett (manual searches only afaik, not hit from the API*)

* Doing some digging to try and confirm this atm.  Hopefully this is meaningful/helpful:
Newznab API endpoint: | https://localhost:443/hydra
Torznab API endpoint: | https://localhost:443/hydra/torznab

huh.  Looks like jackett was being pulled in for api searches also - just disabled those two.

**Comment by professionaltart** [comment]
CPU usage looks like what I'd expect for this problem.


```
29-Mar-2020 11:13:22 - DEBUG   :: mylar.runGit.44 : CP Server Thread-5 : Trying to execute: git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5 with shell in c:\ProgramData\mylar3
29-Mar-2020 11:13:22 - DEBUG   :: mylar.runGit.46 : CP Server Thread-5 : Git output: CompletedProcess(args='git log --encoding=UTF-8 --pretty=format:"%h - %cr - %an - %s" -n 5', returncode=0, stdout='830e0bf - 25 hours ago - Barbeque Sauce - Merge pull request #230 from mylar3/api_response_fix\n3809920 - 25 hours ago - evilhero - FIX(#229) API response was not being handled properly by cherrypy\n47567d5 - 33 hours ago - Barbeque Sauce - Merge pull request #227 from mylar3/db_error_message\ne0ad6c2 - 33 hours ago - evilhero - FIX: fix for incorrect error reference when encountering an SQlite error trap\n331a799 - 33 hours ago - Barbeque Sauce - Merge pull request #226 from mylar3/git_check_patch', stderr='')
29-Mar-2020 11:13:47 - DEBUG   :: mylar.dbUpdate.84 : ThreadPoolExecutor-0_5 : Refresh sequence set to fire every 5 minutes for 7 day(s)
```

 Version: 830e0bf0a55e73b3b37d4b593369c705537291b3 (python3-dev) 

If I try to load /config, I get the above - it's clearly seeing something happen, but /config has been trying to load for almost 3 minutes now with no result.
/home also having issues.

When I jumped on to check Mylar about 15 minutes ago, even /logs was quirking out: the page framework was displaying, but the log area was completely empty.  /home and /config would both load as expected.

A few minutes later, and they swapped: now I have /logs but /home, /config, and /pullist are not loading.  Individual comic titles will load, if I can get to/find them.  /searchit eventually loads.

It looks like /config took somewhere around 4-5 minutes to load in, seeing if other pages will do the same.

I assume the below traceback is from trying to do too many things at once to see what loads up first:
```
29-Mar-2020 11:23:46 - ERROR   :: mylar.excepthook.315 : Thread-74 : Uncaught exception: Traceback (most recent call last):
  File "c:\ProgramData\mylar3\mylar\db.py", line 129, in action
    self.connection.commit()
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ProgramData\mylar3\mylar\logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "c:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\ProgramData\mylar3\mylar\importer.py", line 99, in addComictoDB
    myDB.upsert("comics", newValueDict, controlValueDict)
  File "c:\ProgramData\mylar3\mylar\db.py", line 169, in upsert
    self.action(query, list(valueDict.values()) + list(keyDict.values()))
  File "c:\ProgramData\mylar3\mylar\db.py", line 132, in action
    if any(['unable to open database file' in e, 'database is locked' in e]):
TypeError: argument of type 'OperationalError' is not iterable
```

Restarting Firefox has taken /config load time down to ~30 seconds, /pullist to ~18s.  /home is down to ~24s

When I hit refresh on /config, /logs shows the git log command straight away.

**Comment by professionaltart** [comment]
For what it's worth:  I added the Doom Marvel title while testing this out to see what did and didn't respond.

```
29-Mar-2020 11:29:17 - INFO    :: mylar.addbyid.433 : CP Server Thread-3 : Attempting to add directly by ComicVineID: 121896
29-Mar-2020 11:29:22 - DEBUG   :: mylar.GetComicInfo.233 : Thread-83 : number of issues I counted: 6
29-Mar-2020 11:29:22 - DEBUG   :: mylar.GetComicInfo.234 : Thread-83 : number of issues CV says it has: 6
29-Mar-2020 11:29:22 - DEBUG   :: mylar.GetComicInfo.240 : Thread-83 : vari is set to: no
29-Mar-2020 11:29:22 - DEBUG   :: mylar.GetComicInfo.523 : Thread-83 : comic[ComicVersion]:None
29-Mar-2020 11:29:22 - DEBUG   :: mylar.GetComicInfo.523 : Thread-83 : comic[ComicVersion]:None
29-Mar-2020 11:29:22 - INFO    :: mylar.addComictoDB.128 : Thread-83 : Now adding/updating: Doctor Doom
29-Mar-2020 11:29:22 - INFO    :: mylar.addComictoDB.181 : Thread-83 : Sucessfully retrieved details for Doctor Doom
29-Mar-2020 11:29:22 - INFO    :: mylar.addComictoDB.187 : Thread-83 : Previous version detected as None - seeing if update required
29-Mar-2020 11:29:22 - DEBUG   :: mylar.folder_create.90 : Thread-83 : No version # found for series, removing from folder format
29-Mar-2020 11:29:22 - DEBUG   :: mylar.folder_create.91 : Thread-83 : new folder format: $Series ($Year)
29-Mar-2020 11:29:22 - WARNING :: mylar.validateAndCreateDirectory.1713 : Thread-83 : [DIRECTORY-CHECK] Could not find comic directory: E:\Usenet\comics\Doctor Doom (2019)
29-Mar-2020 11:29:22 - INFO    :: mylar.validateAndCreateDirectory.1716 : Thread-83 : [DIRECTORY-CHECK] Creating comic directory (0777) : E:\Usenet\comics\Doctor Doom (2019)
29-Mar-2020 11:29:24 - INFO    :: mylar.getImage.3710 : Thread-83 : Attempting to retrieve the comic image for series
29-Mar-2020 11:29:25 - DEBUG   :: mylar.getImage.3719 : Thread-83 : comic image retrieval status code: 200
29-Mar-2020 11:29:27 - DEBUG   :: mylar.addComictoDB.297 : Thread-83 : comicIssues: 6
29-Mar-2020 11:29:27 - DEBUG   :: mylar.addComictoDB.298 : Thread-83 : seriesyear: 2019 / currentyear: 2020
29-Mar-2020 11:29:27 - DEBUG   :: mylar.addComictoDB.299 : Thread-83 : comicType: Print
29-Mar-2020 11:29:51 - DEBUG   :: mylar.getComic.137 : Thread-83 : there are 6 search results...
29-Mar-2020 11:29:51 - DEBUG   :: mylar.getComic.142 : Thread-83 : querying range from 0 to 100
29-Mar-2020 11:29:51 - INFO    :: mylar.addComictoDB.343 : Thread-83 : Sucessfully retrieved issue details for Doctor Doom
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1052 : Thread-83 : issuedata call references...
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1053 : Thread-83 : comicid: 121896
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1054 : Thread-83 : comicname: Doctor Doom
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1055 : Thread-83 : comicissues: 6
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1056 : Thread-83 : calledfrom: None
29-Mar-2020 11:29:51 - DEBUG   :: mylar.updateissuedata.1057 : Thread-83 : issuechk: None
29-Mar-2020 11:29:52 - DEBUG   :: mylar.updateissuedata.1058 : Thread-83 : latestissueinfo: None
29-Mar-2020 11:29:52 - DEBUG   :: mylar.updateissuedata.1059 : Thread-83 : issuetype: None
29-Mar-2020 11:29:52 - DEBUG   :: mylar.annual_check.1437 : Thread-83 : checking annual db
29-Mar-2020 11:29:52 - DEBUG   :: mylar.annual_check.1466 : Thread-83 : [IMPORTER-ANNUAL] - Annual Year:2019
29-Mar-2020 11:30:01 - DEBUG   :: mylar.findComic.147 : Thread-83 : there are 0 search results...
29-Mar-2020 11:30:01 - DEBUG   :: mylar.annual_check.1575 : Thread-83 : [IMPORTER-ANNUAL] - No results, removing the year from the agenda and re-querying.
29-Mar-2020 11:30:19 - DEBUG   :: mylar.findComic.147 : Thread-83 : there are 0 search results...
29-Mar-2020 11:30:19 - DEBUG   :: mylar.updateissuedata.1083 : Thread-83 : Finished Annual checking.
29-Mar-2020 11:30:19 - INFO    :: mylar.updateissuedata.1100 : Thread-83 : Now adding/updating issues for Doctor Doom
29-Mar-2020 11:30:19 - DEBUG   :: mylar.updateissuedata.1315 : Thread-83 : initiating issue updating - info & status
29-Mar-2020 11:30:24 - WARNING :: mylar.havetotals.1409 : CP Server Thread-2 : Doctor Doom has not finished loading. Nulling some values so things display properly until they can populate.
29-Mar-2020 11:30:25 - DEBUG   :: mylar.addComictoDB.378 : Thread-83 : no update required - lastissueid [None] = latestissueid [739556]
29-Mar-2020 11:30:25 - INFO    :: mylar.addComictoDB.403 : Thread-83 : Updating complete for: Doctor Doom
29-Mar-2020 11:30:25 - DEBUG   :: mylar.addComictoDB.424 : Thread-83 : issue: 6 status before chk :Wanted
29-Mar-2020 11:30:25 - INFO    :: mylar.forceRescan.945 : Thread-83 : [FILE-RESCAN] Now checking files for Doctor Doom (2019) in E:\Usenet\comics\Doctor Doom (2019)
29-Mar-2020 11:30:25 - INFO    :: mylar.traverse_directories.1492 : Thread-83 : there are 0 files.
29-Mar-2020 11:30:25 - DEBUG   :: mylar.forceRescan.1028 : Thread-83 : No issues with identical issue numbering were detected for this series
29-Mar-2020 11:30:25 - DEBUG   :: mylar.forceRescan.1050 : Thread-83 : [ANNUAL-CHK] No annuals with identical issue numbering across annual volumes were detected for this series
29-Mar-2020 11:30:25 - INFO    :: mylar.forceRescan.1499 : Thread-83 : [FILE-RESCAN] Total files located: 0
29-Mar-2020 11:30:26 - DEBUG   :: mylar.forceRescan.1606 : Thread-83 : [FILE-RESCAN] Ensuring permissions/ownership enforced for series: Doctor Doom
29-Mar-2020 11:30:26 - INFO    :: mylar.forceRescan.1608 : Thread-83 : [FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 0 / 6 ]
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.427 : Thread-83 : issue: 6 status after chk :Wanted
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.429 : Thread-83 : pullupd: None
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.430 : Thread-83 : lastpubdate: Present
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.431 : Thread-83 : series_status: Active
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.436 : Thread-83 : latestissue: #6
29-Mar-2020 11:30:26 - DEBUG   :: mylar.addComictoDB.443 : Thread-83 : latestissue status: Wanted
29-Mar-2020 11:30:26 - INFO    :: mylar.addComictoDB.445 : Thread-83 : Checking this week pullist for new issues of Doctor Doom
29-Mar-2020 11:30:32 - INFO    :: mylar.addComictoDB.473 : Thread-83 : Attempting to grab wanted issues for : Doctor Doom
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 1
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 2
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 3
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 4
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 5
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.476 : Thread-83 : Searching for : 6
29-Mar-2020 11:30:32 - DEBUG   :: mylar.addComictoDB.477 : Thread-83 : Status of : Wanted
29-Mar-2020 11:30:32 - INFO    :: mylar.searchforissue.1604 : Thread-83 : A search is currently in progress....queueing this up again to try in a bit.
29-Mar-2020 11:30:32 - INFO    :: mylar.addComictoDB.481 : Thread-83 : Finished grabbing what I could.
29-Mar-2020 11:30:32 - INFO    :: mylar.addComictoDB.519 : Thread-83 : Sucessfully added Doctor Doom (2019) to the watchlist
```

From what I can see, Hydra has received no API hits to search for it, it's not in Sab, and there's nothing else currently searching in Mylar.

```
RSS Feeds | 2020-03-29 11:02:51 | 300 mins | 2020-03-29 11:02:51 | Running
```
(that's 34 minutes ago, but logs say nothing about it)

This is the last set of RSS mentions in Logs, which lines up with above timestamp:
```
29-Mar-2020 11:02:51 - INFO    :: mylar.run.37 : ThreadPoolExecutor-0_11 : [RSS-FEEDS] RSS Feed Check Initalizing....
29-Mar-2020 11:02:51 - INFO    :: mylar.run.102 : ThreadPoolExecutor-0_11 : [RSS-FEEDS] Initiating RSS Feed Check for NZB Providers.
29-Mar-2020 11:02:51 - DEBUG   :: mylar.nzbs.502 : ThreadPoolExecutor-0_11 : [RSS] You have enabled 1 NZB RSS search providers.
29-Mar-2020 11:02:51 - DEBUG   :: mylar._parse_feed.468 : ThreadPoolExecutor-0_11 : [RSS] Fetching items from nzbHydra2 [nzbhydra]
29-Mar-2020 11:02:55 - DEBUG   :: mylar.nzbs.575 : ThreadPoolExecutor-0_11 : [RSS] (nzbHydra2 [nzbhydra]) now being updated...
29-Mar-2020 11:02:55 - INFO    :: mylar.nzbs.607 : ThreadPoolExecutor-0_11 : [RSS] (nzbHydra2 [nzbhydra]) 100 entries indexed.
29-Mar-2020 11:02:55 - INFO    :: mylar.nzbs.611 : ThreadPoolExecutor-0_11 : [RSS] 100 entries have been indexed and are now going to be stored for caching.
29-Mar-2020 11:02:58 - DEBUG   :: mylar.rssdbupdate.644 : ThreadPoolExecutor-0_11 : Completed adding new data to RSS DB. Next add in 300 minutes
29-Mar-2020 11:02:58 - INFO    :: mylar.run.107 : ThreadPoolExecutor-0_11 : [RSS-FEEDS] RSS Feed Check/Update Complete
29-Mar-2020 11:02:59 - INFO    :: mylar.run.108 : ThreadPoolExecutor-0_11 : [RSS-FEEDS] Watchlist Check for new Releases
```

Unsure if this is still RSS interfering with everything else, again.

**Comment by professionaltart** [comment]
I'll tentatively close this for now and re-open/bump if it resurfaces.
