### ISSUE TITLE
NZBGet b64encode TypeError

### ISSUE THREAD

**Issue by barbequesauce** [mylar3/mylar3#9]
```
  415 13-Jan-2020 14:17:48 - DEBUG   :: mylar.searcher.2229 : SEARCH-QUEUE : [PAYLOAD-NONE] Download URL: hxYOUDONTNEEDTOKNOWTHISx [VerifySSL: True]
  416 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2249 : SEARCH-QUEUE : Status code returned: 200
  417 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2271 : SEARCH-QUEUE : filename within nzb: Dr.Strange.-.Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
  418 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2288 : SEARCH-QUEUE : [FILENAME] filename (remove chars): Dr.Strange.-.Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
  419 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2291 : SEARCH-QUEUE : [FILENAME] nzbname (\s): Dr.Strange.-.Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
  420 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2293 : SEARCH-QUEUE : [FILENAME] end nzbname: Dr.Strange.-.Surgeon.Supreme.001.2020.Digital.Zone-Empire.nzb
  421 13-Jan-2020 14:17:50 - DEBUG   :: mylar.searcher.2304 : SEARCH-QUEUE : Cache Directory successfully found at : /opt/mylar.py3/cache. Ensuring proper permissions.
  422 13-Jan-2020 14:17:50 - ERROR   :: mylar.setperms.1774 : SEARCH-QUEUE : Could not change permissions : /opt/mylar.py3/cache. Exiting...
  423 13-Jan-2020 14:17:50 - ERROR   :: mylar.excepthook.315 : SEARCH-QUEUE : Uncaught exception: Traceback (most recent call last):
  424   File "/opt/mylar.py3/mylar/logger.py", line 337, in new_run
  425     old_run(*args, **kwargs)
  426   File "/opt/pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
  427     self._target(*self._args, **self._kwargs)
  428   File "/opt/mylar.py3/mylar/helpers.py", line 3177, in search_queue
  429     ss_queue = mylar.search.searchforissue(item['issueid'])
  430   File "/opt/mylar.py3/mylar/search.py", line 1862, in searchforissue
  431     foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsschec
  432   File "/opt/mylar.py3/mylar/search.py", line 359, in search_init
  433     findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=Issue
  434   File "/opt/mylar.py3/mylar/search.py", line 1489, in NZB_SEARCH
  435     searchresult = searcher(nzbprov, nzbname, mylar.COMICINFO, links, IssueID, ComicID, tmpprov, newznab=newznab_host, torznab=torznab_host, rss=RSS)
  436   File "/opt/mylar.py3/mylar/search.py", line 2494, in searcher
  437     send_to_nzbget = ss.sender(nzbpath)
  438   File "/opt/mylar.py3/mylar/nzbget.py", line 72, in sender
  439     nzbcontent64 = standard_b64encode(nzbcontent)
  440   File "/opt/pyenv/versions/3.8.1/lib/python3.8/base64.py", line 95, in standard_b64encode
  441     return b64encode(s)
  442   File "/opt/pyenv/versions/3.8.1/lib/python3.8/base64.py", line 58, in b64encode
  443     encoded = binascii.b2a_base64(s, newline=False)
  444 TypeError: a bytes-like object is required, not 'str'
```

**Comment by barbequesauce** [comment]
Fixed by #2
