### ISSUE TITLE
Crash after updating to latest version - AttributeError: 'PosixPath' object has no attribute 'read_text'

### ISSUE THREAD

**Issue by WedgeSparda** [mylar3/mylar3#940]
**Describe the bug**
I have a Docker container running Mylar3 with no problem, but after updating to most recent version (v0.5.9.5), is unable to start running.

This is what I can see being displayed over and over on the console

```
Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar3/mylar/__init__.py", line 39, in <module>
    import cherrypy
  File "/usr/lib/python3.8/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/lib/python3.8/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/lib/python3.8/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/lib/python3.8/site-packages/jaraco/collections.py", line 10, in <module>
    import jaraco.text
  File "/usr/lib/python3.8/site-packages/jaraco/text/__init__.py", line 228, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

**Environment (please complete the following information):**
 - OS: Synology DSM 7.0.1, Python 3.7.12-20
 - Branch / commit: master / 4a54f5f28d587b4f877ad163cae36f27d42c3135

**Comment by barbequesauce** [comment]
See this thread: https://github.com/linuxserver/docker-mylar3/issues/16

**Comment by WedgeSparda** [comment]
@barbequesauce Ah, thanks 👍  I'll close this then.

**Comment by aptalca** [comment]
Reported upstream: https://github.com/jaraco/jaraco.text/issues/8
