### ISSUE TITLE
Upgrade from evilhero issues.

### ISSUE THREAD

**Issue by neuikc** [mylar3/mylar3#945]
I've followed the steps to upgrade from my evilhero install to the python3 version here but am receiving errors when attempting to run "sudo python3 Mylar.py"

Traceback (most recent call last):
  File "Mylar.py", line 26, in <module>
    import mylar
  File "/opt/mylar3/mylar/__init__.py", line 39, in <module>
    import cherrypy
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/local/lib/python3.8/dist-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/local/lib/python3.8/dist-packages/jaraco/collections.py", line 10, in <module>
    import jaraco.text
  File "/usr/local/lib/python3.8/dist-packages/jaraco/text/__init__.py", line 228, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
AttributeError: 'PosixPath' object has no attribute 'read_text'

Any advice would be helpful. Thanks.

**Comment by evilhero** [comment]
What version/branch are you running?

You should never run it as sudo as that has different files that it could use as opposed to an actual user.

The problem is that you have cherrypy installed twice (pip and apt usually) and running it as sudo probably isn't helping to distinguish what's what.

Try doing a ```pip3 uninstall cherrypy``` (replace pip with whatever you  all your pip3 instance with if needbe) and see if that runs as a non-root user. If it complains about it not being installed, then do a ```pip3 install cherrypy``` and see if that fixes things.

**Comment by neuikc** [comment]
Honestly, it's been awhile since the evilhero version was running on my machine and I can't recall the build number when it was last successfully running. I attempted to move out of /opt and run under my /home (editing config to reflect path changes) with my non-sudo login and got the below output:

user@host:~/.mylar$ python3 Mylar.py
log language set to en_US
Initializing startup sequence....
06-Nov-2021 10:28:31 - ERROR :: mylar.initialize.205 : MainThread : Cannot connect to the database: attempt to write a readonly database
06-Nov-2021 10:28:31 - WARNING :: mylar.fetch.102 : MainThread : DB error: no such column: intLatestIssue
06-Nov-2021 10:28:31 - ERROR :: mylar.excepthook.315 : MainThread : Uncaught exception: Traceback (most recent call last):
  File "Mylar.py", line 388, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/home/user/.mylar/mylar/__init__.py", line 315, in initialize
    helpers.latestissue_update()
  File "/home/user/.mylar/mylar/helpers.py", line 3101, in latestissue_update
    cck = myDB.select('SELECT ComicID, LatestIssue FROM comics WHERE intLatestIssue is NULL')
  File "/home/user/.mylar/mylar/db.py", line 148, in select
    sqlResults = self.fetch(query, args).fetchall()
  File "/home/user/.mylar/mylar/db.py", line 89, in fetch
    sqlResult = cursor.execute(query)
sqlite3.OperationalError: no such column: intLatestIssue

Traceback (most recent call last):
  File "Mylar.py", line 388, in <module>
    main()
  File "Mylar.py", line 203, in main
    mylar.initialize(mylar.CONFIG_FILE)
  File "/home/user/.mylar/mylar/__init__.py", line 315, in initialize
    helpers.latestissue_update()
  File "/home/user/.mylar/mylar/helpers.py", line 3101, in latestissue_update
    cck = myDB.select('SELECT ComicID, LatestIssue FROM comics WHERE intLatestIssue is NULL')
  File "/home/user/.mylar/mylar/db.py", line 148, in select
    sqlResults = self.fetch(query, args).fetchall()
  File "/home/user/.mylar/mylar/db.py", line 89, in fetch
    sqlResult = cursor.execute(query)
sqlite3.OperationalError: no such column: intLatestIssue

Change username and host to generics for this posting.

**Comment by evilhero** [comment]
It says the db is read-only so it can't write any updates to the db schema. Try chown-ing the db file for your user and see if that helps.

**Comment by neuikc** [comment]
So much closer, thanks, it's running now with a complaint of: You're running an unknown version of Mylar. Update or Close

Update doesn't seem to do anything though.

Appreciate the weekend assists.

**Comment by evilhero** [comment]
I'm guessing that when you moved out of /opt into /home, the ownership is still set to root (as that's the default for opt), so it can't modify any files.

Try chown-ing the entire mylar directory recursively under your /home, as well as possibly chmod ding the entire Myalr directory recursively 775 (try that if the ownership doesn't allow you to do the update check)

**Comment by neuikc** [comment]
Thanks again. Yep, took the suggestions chmod and chown and it's still complaining about the version. 

I might consider a fresh install, but is there a best practice for this since I have access to the service now? Can I do a db and config export/import kind of thing with mylar3? No worries, if not, appreciate the time.

**Comment by evilhero** [comment]
Once you started up mylar successfully it modified the db file so as to update it for mylar3 usage (I don't think it deletes any fields, just adds new ones if I recall). All of your existing series that were being watched should be present in mylar3 upon startup - no need to export/import anything. 
The update warning is due to it being unable to find either the git executable (if you installed via git), or the fact that some files may have been modified as to what it expects (usually more so happens with people changing code related stuff).

So how did you install mylar3?

**Comment by barbequesauce** [comment]
Closing due to inactivity
