### ISSUE TITLE
500 on opds feed "latest" and read list

### ISSUE THREAD

**Issue by francispeixoto** [mylar3/mylar3#979]
**Describe the bug**
i get a 500 when i browse to the latest and readlisr feeds of the opds path. publishers and folders works.

Version[v0.6.1] docker
Python Version : 3.9.5 

error message:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.
Traceback (most recent call last): File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 638, in respond self._do_respond(path_info) File "/usr/lib/python3.9/site-packages/cherrypy/_cprequest.py", line 697, in _do_respond response.body = self.handler() File "/usr/lib/python3.9/site-packages/cherrypy/lib/encoding.py", line 223, in __call__ self.body = self.oldhandler(*args, **kwargs) File "/usr/lib/python3.9/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__ return self.callable(*self.args, **self.kwargs) File "/app/mylar3/mylar/webserve.py", line 6566, in opds data = op.fetchData() File "/app/mylar3/mylar/opds.py", line 87, in fetchData result = methodToCall(**self.kwargs) File "/app/mylar3/mylar/opds.py", line 491, in _Recent issuedetails = mylar.helpers.IssueDetails(fileloc).get('metadata', None) File "/app/mylar3/mylar/helpers.py", line 1571, in IssueDetails file_info = getimage.extract_image(filelocation, single=True, imquality='issue', comicname=comicname) File "/app/mylar3/mylar/getimage.py", line 189, in extract_image return {'ComicImage': ComicImage, 'metadata': metadata, 'rawImage': RawImage} UnboundLocalError: local variable 'RawImage' referenced before assignment

**Comment by evilhero** [comment]
Please post a full debug log / carepackage which will (hopefully) show the leadup to the given error. Just posting the error without the context leading up to it isn't very helpful when it comes to troubleshooting, so we need to see the debug logs.

**Comment by francispeixoto** [comment]
Sorry I opened the issue on the mobile app so I couldn't easily paste that data.

here's the debug log showing my calls to each OPDS comand. ReadList and Recent both gave 500 errors, while the other commands worked. I'd rather not blindly share the whole carepackage.

<html>
<body>


Timestamp | Level | Message
-- | -- | --
2021-12-21 14:55:38 | DEBUG | Recieved OPDS command: StoryArcs
2021-12-21 14:55:25 | DEBUG | Recieved OPDS command: AllTitles
2021-12-21 14:55:14 | DEBUG | Recieved OPDS command: Publishers
2021-12-21 14:54:33 | DEBUG | Recieved OPDS command: Recent
2021-12-21 14:54:05 | DEBUG | Recieved OPDS command: ReadList
2021-12-21 14:53:39 | DEBUG | {'42233': {'comicid': '42233'}}
2021-12-21 14:53:39 | DEBUG | Recieved OPDS command: root
2021-12-21 14:53:22 | INFO | config file has been loaded from: /config/mylar/config.ini
2021-12-21 14:53:22 | DEBUG | If you can read this message, debug logging is now working
2021-12-21 14:53:22 | INFO | Verbose (DEBUG) logging is enabled


</body>
</html>

**Comment by barbequesauce** [comment]
Thanks - this came from the Logs screen. There's a lot more in the actual log on disk - can you attach that file please?

**Comment by barbequesauce** [comment]
Closing due to inactivity
